### ISSUE TITLE
An error occurs when running make build and make run commands for the OpenDevin application after adding SANDBOX_TYPE=exec inside the config.toml file. The error message indicates an invalid date or number in the TOML configuration file.

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1024]
## Bug Description
An error occurs when running `make build` and `make run` commands for the OpenDevin application after adding `SANDBOX_TYPE=exec` inside the `config.toml` file. The error message indicates an invalid date or number in the TOML configuration file.

## Setup and Configuration
**Current Version**:

```bash
commit 51b3ae56c75d3f00bc717849e43a600e54b9683d (HEAD -> main, origin/main, origin/HEAD)
Author: PierrunoYT <95778421+PierrunoYT@users.noreply.github.com>
Date:   Thu Apr 11 04:59:46 2024 +0200

    Add German Translation (#851)

    * Update index.ts

    * Update translation.json

    * Update index.ts

    * Remove comment and ident JSON

    ---------

    Co-authored-by: Jim Su <jimsu@protonmail.com>
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="XYZG"
LLM_EMBEDDING_MODEL=""
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE=exec
```

**My model and agent** (you can see these settings in the UI):
* Model: 
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

## Steps to Reproduce
1. Add `SANDBOX_TYPE=exec` inside the `config.toml` file
2. Run `make build` to build the OpenDevin application
3. Run `make run` to start the application

## Logs, Error Messages, and Screenshots
```
Traceback (most recent call last):
  File "/home/pierre/.cache/pypoetry/virtualenvs/opendevin-lPNnzAY--py3.12/lib/python3.12/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pierre/.cache/pypoetry/virtualenvs/opendevin-lPNnzAY--py3.12/lib/python3.12/site-packages/toml/decoder.py", line 737, in load_line
    raise ValueError("Invalid date or number")
ValueError: Invalid date or number

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/config.py", line 34, in <module>
    tomlConfig = toml.loads(config_str)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pierre/.cache/pypoetry/virtualenvs/opendevin-lPNnzAY--py3.12/lib/python3.12/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid date or number (line 5 column 1 char 148)
```

## Additional Context
- The issue occurs after adding `SANDBOX_TYPE=exec` inside the `config.toml` file.
- The error message indicates an invalid date or number in the TOML configuration file at line 5, column 1, character 148.
- The error occurs during the parsing of the TOML configuration file using the `toml.loads()` function.
- The latest commit `51b3ae56c75d3f00bc717849e43a600e54b9683d` from April 11, 2024, at 04:59:46 is being used.
- The commit includes updates related to adding German translation and making changes to `index.ts` and `translation.json` files.

**Comment by PierrunoYT** [comment]
> SANDBOX_TYPE=exec invalid format the correct format is SANDBOX_TYPE="exec"

Oh okay thx
