### ISSUE TITLE
Frontend not serving on WSL

### ISSUE THREAD

**Issue by semiautomatix** [OpenDevin/OpenDevin#1036]
#### Describe the bug
Since updating yesterday (and again today) I've have been unable to start OpenDevin. The problem appears outwardly to be with the front end.

#### Setup and configuration
**Current version**:

```bash
commit 9fd95cc35fb1cb05ee72412b6188debda44d25d5 (HEAD -> main, origin/main, origin/HEAD)
Author: Redrum624 <lauzon624@gmail.com>
Date:   Thu Apr 11 22:12:23 2024 -0400

    Fix: local files in the browser (at least for Windows) (#839)

    * Fix: local files in the browser (at least for Windows)

    The Browser works for screenshoting websites, but when the LLM tries to display a local file that he created, it can't access the full directory on Windows.

    * Update browse.py

    ---------

    Co-authored-by: Robert Brennan <accounts@rbren.io>
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="sk-xxxx"
LLM_EMBEDDING_MODEL=""
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: n/a
* Agent: n/a

**Commands I ran to install and run OpenDevin**:
```
//
```

**Steps to Reproduce**:
1. `make run` on WSL
2. Navigate to http://localhost:3001 on Windows

**Logs, error messages, and screenshots**:

```bash
> make start-backend
Starting backend...
The currently activated Python version 3.10.12 is not supported by the project (^3.11).
Trying to find and use a compatible version.
Using python3.12 (3.12.2)
/home/user/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/user/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/user/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/user/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/user/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [9496]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)

> make start-frontend
Starting frontend...

> opendevin-frontend@0.1.0 start
> vite


  VITE v5.2.8  ready in 619 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
```

#### Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/20738236/1263a499-6ec2-4e1d-98b7-ab658fe1febc)

![image](https://github.com/OpenDevin/OpenDevin/assets/20738236/a6bf1a94-76b3-480e-bb8b-c6239793e85f)

**Comment by semiautomatix** [comment]
Note: performed the same steps on Ubuntu without an issue

**Comment by rbren** [comment]
Instead of `make start-frontend`, can you try `npm run start -- --port 3001 --host 0.0.0.0`?

**Comment by pmiriyev** [comment]
and how to access UI?

**Comment by semiautomatix** [comment]
> Instead of `make start-frontend`, can you try `npm run start -- --port 3001 --host 0.0.0.0`?

Thanks, I'll get back to you.

**Comment by semiautomatix** [comment]
@rbren 

Opening the address at `http://172.31.154.121:3001/` seems to run the UI, but with errors.

```bash
$ npm run start -- --port 3001 --host 0.0.0.0

> opendevin-frontend@0.1.0 start
> vite --port 3001 --host 0.0.0.0


  VITE v5.2.8  ready in 1048 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: http://172.31.154.121:3001/
  ➜  Network: http://172.25.0.1:3001/
  ➜  press h + enter to show help
```

Frontend:

![image](https://github.com/OpenDevin/OpenDevin/assets/20738236/0e251f75-f319-48b0-99b8-05d4279afdb4)

Backend:

```bash
$ make start-backend
Starting backend...
The currently activated Python version 3.10.12 is not supported by the project (^3.11).
Trying to find and use a compatible version.
Using python3.12 (3.12.2)
modules.json: 100%|████████████████████████████████████████████████████████| 349/349 [00:00<00:00, 1.88MB/s]
config_sentence_transformers.json: 100%|████████████████████████████████████| 124/124 [00:00<00:00, 674kB/s]
README.md: 100%|████████████████████████████████████████████████████████| 94.8k/94.8k [00:00<00:00, 415kB/s]
sentence_bert_config.json: 100%|██████████████████████████████████████████| 52.0/52.0 [00:00<00:00, 296kB/s]
config.json: 100%|█████████████████████████████████████████████████████████| 743/743 [00:00<00:00, 4.27MB/s]
model.safetensors: 100%|█████████████████████████████████████████████████| 133M/133M [00:06<00:00, 19.6MB/s]
tokenizer_config.json: 100%|███████████████████████████████████████████████| 366/366 [00:00<00:00, 2.38MB/s]
vocab.txt: 100%|█████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 1.03MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████| 711k/711k [00:00<00:00, 1.64MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████| 125/125 [00:00<00:00, 910kB/s]
1_Pooling/config.json: 100%|███████████████████████████████████████████████| 190/190 [00:00<00:00, 1.17MB/s]
INFO:     Started server process [1496]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 56208) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJiODA1YzBiZC03OTk1LTQ0ZWItYjM4YS1kYTBjZGQzNWVlM2MifQ.yfHOKrPDAE41xy21GBmamd8iCaStXiSHGojBhKgbtKo" [accepted]
Starting loop_recv for sid: b805c0bd-7995-44eb-b38a-da0cdd35ee3c
INFO:     connection open
INFO:     127.0.0.1:56232 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:56228 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:56222 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:41872 - "GET /refresh-files HTTP/1.1" 200 OK
16:20:01 - opendevin:INFO: ssh_box.py:81 - Using workspace directory: /home/tim/Documents/git/OpenDevin/workspace
16:20:01 - opendevin:INFO: ssh_box.py:280 - Container stopped
16:20:01 - opendevin:INFO: ssh_box.py:312 - Container started
16:20:02 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
16:20:02 - opendevin:INFO: ssh_box.py:170 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 52587 opendevin@localhost` with the password '5ea6f3af-24c4-474d-9aff-40ec08046c97' and report the issue on GitHub.
16:20:03 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/home/tim/Documents/git/OpenDevin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/controller/agent_controller.py", line 95, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/controller/command_manager.py", line 29, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/sandbox/ssh_box.py", line 99, in __init__
    self.start_ssh_session()
  File "/home/tim/Documents/git/OpenDevin/opendevin/sandbox/ssh_box.py", line 173, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/home/tim/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
INFO:     127.0.0.1:41892 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:41878 - "GET /configurations HTTP/1.1" 200 OK
16:20:06 - opendevin:INFO: ssh_box.py:81 - Using workspace directory: /home/tim/Documents/git/OpenDevin/workspace
16:20:07 - opendevin:INFO: ssh_box.py:280 - Container stopped
16:20:08 - opendevin:INFO: ssh_box.py:312 - Container started
16:20:09 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
16:20:09 - opendevin:INFO: ssh_box.py:170 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 45053 opendevin@localhost` with the password '1ef54afd-23cc-4000-8be3-84fb48bf6e93' and report the issue on GitHub.
16:20:09 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/home/tim/Documents/git/OpenDevin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/controller/agent_controller.py", line 95, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/controller/command_manager.py", line 29, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/sandbox/ssh_box.py", line 99, in __init__
    self.start_ssh_session()
  File "/home/tim/Documents/git/OpenDevin/opendevin/sandbox/ssh_box.py", line 173, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/home/tim/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
INFO:     127.0.0.1:41896 - "DELETE /messages HTTP/1.1" 200 OK
16:20:45 - opendevin:INFO: session.py:39 - WebSocket disconnected, sid: b805c0bd-7995-44eb-b38a-da0cdd35ee3c
INFO:     connection closed
cd^CReceived signal 2, exiting...
ERROR:    Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 216, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 397, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 402, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 377, in uvloop.loop.Loop._ceval_process_signals
  File "/home/tim/Documents/git/OpenDevin/opendevin/server/agent/manager.py", line 40, in handle_signal
    exit(0)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 741, in lifespan
    await receive()
  File "/home/tim/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

^Cmake: *** [Makefile:111: start-backend] Interrupt
```

Logs:

```bash
16:20:01 - opendevin:INFO: ssh_box.py:81 - Using workspace directory: /home/tim/Documents/git/OpenDevin/workspace
16:20:01 - opendevin:INFO: ssh_box.py:280 - Container stopped
16:20:01 - opendevin:INFO: ssh_box.py:312 - Container started
16:20:02 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
16:20:02 - opendevin:INFO: ssh_box.py:170 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 52587 opendevin@localhost` with the password '5ea6f3af-24c4-474d-9aff-40ec08046c97' and report the issue on GitHub.
16:20:03 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/home/tim/Documents/git/OpenDevin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/controller/agent_controller.py", line 95, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/controller/command_manager.py", line 29, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/sandbox/ssh_box.py", line 99, in __init__
    self.start_ssh_session()
  File "/home/tim/Documents/git/OpenDevin/opendevin/sandbox/ssh_box.py", line 173, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/home/tim/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
16:20:06 - opendevin:INFO: ssh_box.py:81 - Using workspace directory: /home/tim/Documents/git/OpenDevin/workspace
16:20:07 - opendevin:INFO: ssh_box.py:280 - Container stopped
16:20:08 - opendevin:INFO: ssh_box.py:312 - Container started
16:20:09 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
16:20:09 - opendevin:INFO: ssh_box.py:170 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 45053 opendevin@localhost` with the password '1ef54afd-23cc-4000-8be3-84fb48bf6e93' and report the issue on GitHub.
16:20:09 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/home/tim/Documents/git/OpenDevin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/controller/agent_controller.py", line 95, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/controller/command_manager.py", line 29, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/tim/Documents/git/OpenDevin/opendevin/sandbox/ssh_box.py", line 99, in __init__
    self.start_ssh_session()
  File "/home/tim/Documents/git/OpenDevin/opendevin/sandbox/ssh_box.py", line 173, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/home/tim/.cache/pypoetry/virtualenvs/opendevin-9dS3dFVn-py3.12/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
16:20:45 - opendevin:INFO: session.py:39 - WebSocket disconnected, sid: b805c0bd-7995-44eb-b38a-da0cdd35ee3c
```

**Comment by SmartManoj** [comment]
set `SANDBOX_TYPE="exec"` in config

**Comment by semiautomatix** [comment]
> set `SANDBOX_TYPE="exec"` in config

Thanks, hopefully it's related to https://github.com/OpenDevin/OpenDevin/issues/911

I'll give this a try and close the issue, if resolved

**Comment by semiautomatix** [comment]
> Yup, the docker connect issue is a separate one, so I'm going to close this issue. But feel free to open another one if you're still having trouble!

Frontend issue on WSL2 still persisting: https://github.com/OpenDevin/OpenDevin/issues/1206

**Comment by rbren** [comment]
@semiautomatix can you open a new issue reproducing the frontend issue with docker commands?

**Comment by semiautomatix** [comment]
> @semiautomatix can you open a new issue reproducing the frontend issue with docker commands?

Will do so, I haven't been able to access remotely. I will have to attempt directly from the server.

**Comment by semiautomatix** [comment]
> @semiautomatix can you open a new issue reproducing the frontend issue with docker commands?

Thanks @rbren, I've run Docker directly on the server and everything is running as expected. I appreciate the hard work!
