### ISSUE TITLE
the web server fail to start, `validateDOMNesting` issue

### ISSUE THREAD

**Issue by zhaoweihan2017** [OpenDevin/OpenDevin#1044]
#### Describe the bug
when i run make run, the terminal does not appear any errors. but the web shows fail to start。it always call http://{ip}:3002/api/auth
but response is html. 

use docker image ollama/ollama

error: 

react-dom.development.js:86 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at http://{ip}:3002/node_modules/.vite/deps/@nextui-org_react.js?v=b1e2d44c:39136:7
    at div
    at div
    at span
    at div
    at button
    at h2
    at div
    at http://{ip}:3002/node_modules/.vite/deps/@nextui-org_react.js?v=b1e2d44c:36922:7
    at LayoutGroup (http://{ip}:3002/node_modules/.vite/deps/@nextui-org_react.js?v=b1e2d44c:36044:22)
    at div
    at http://{ip}:3002/node_modules/.vite/deps/@nextui-org_react.js?v=b1e2d44c:38085:7
    at div
    at div
    at Files (http://{ip}:3002/src/components/Files.tsx:35:3)
    at div
    at div
    at CodeEditor (http://{ip}:3002/src/components/CodeEditor.tsx:26:51)
    at div
    at Workspace (http://{ip}:3002/src/components/Workspace.tsx:31:17)
    at div
    at div
    at Container (http://{ip}:3002/src/components/Resizable.tsx:26:3)
    at div
    at div
    at Container (http://{ip}:3002/src/components/Resizable.tsx:26:3)
    at div
    at div
    at App (http://{ip}:3002/src/App.tsx:63:41)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (http://{ip}:3002/node_modules/.vite/deps/@nextui-org_react.js?v=b1e2d44c:11823:32)
    at $f57aed4a881a3485$export$178405afcd8c5eb (http://{ip}:3002/node_modules/.vite/deps/@nextui-org_react.js?v=b1e2d44c:11790:9)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (http://{ip}:3002/node_modules/.vite/deps/@nextui-org_react.js?v=b1e2d44c:5247:9)
    at NextUIProvider (http://{ip}:3002/node_modules/.vite/deps/@nextui-org_react.js?v=b1e2d44c:12040:3)
    at Provider (http://{ip}:3002/node_modules/.vite/deps/react-redux.js?v=b1e2d44c:1093:3)
printWarning @ react-dom.development.js:86
Show 1 more frame
{ip}/:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
{ip}/:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
{ip}/:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
{ip}/:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

#### Setup and configuration
**Current version**:
1、make build
2、make setup-config
3、make run

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```
LLM_API_KEY="ollama"
LLM_MODEL="llama2:7b"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434/chat"
WORKSPACE_DIR="./workspace

**My model and agent** (you can see these settings in the UI):
* Model: llama2:7b
* Agent:

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1、make build
2、make setup-config
3、make run

**Logs, error messages, and screenshots**:

#### Additional Context
ollama use docker image ollama/ollama

**Comment by rbren** [comment]
Where are you seeing that error message? In the browser console? Or in the frontend server logs?

**Comment by SmartManoj** [comment]
@rbren  Shall we have a label as `frontend`?

**Comment by rbren** [comment]
This should be fixed now that we're running in docker!
