### ISSUE TITLE
Ollama Infinite Loop

### ISSUE THREAD

**Issue by kjenney** [OpenDevin/OpenDevin#1057]
#### Describe the bug
I'm running OpenDevin with the latest code as of the time of this writing. I created a new virtual environment and set it up according to the documentation. When I ask OpenDevin to "Build me a calculator app written in Python 3.11" it got stuck in a loop that lasted 30 steps and included multiple errors.

#### Setup and configuration
**Current version**:
```bash
commit 5d5106c51042fe3479bbf19b14f2b14a2d9c3c26 (HEAD -> main, origin/main, origin/HEAD)
Author: namtacs <95915765+namtacs@users.noreply.github.com>
Date:   Fri Apr 12 16:20:47 2024 +0300

    Response recognition for weak llms (#523)

    * Tweak for weak llms

    * Update to the latest commits

    * Update to the latest commits

    * Fix lint errors

    * Remove merge artifact

    ---------

    Co-authored-by: Jim Su <jimsu@protonmail.com>
```

**My config.toml and environment vars**:
```toml
LLM_MODEL="ollama/llama2:latest"
LLM_API_KEY="ollama"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"
```

**My model and agent**:
* Model: ollama/ollama2:latest
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. git clone https://github.com/OpenDevin/OpenDevin.git
2. cd OpenDevin
3. python -m venv .venv
4. source .venv/bin/activate
5. make build
6. make setup-config
7. Edit config.toml to use Ollama using [this documentation](https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/LOCAL_LLM_GUIDE.md)
8. make run
9. Load localhost:3001
10. Type into the prompt: `Build me a calculator app written in Python 3.11`

**Logs, error messages, and screenshots**:

```
ERROR:
"'action' key is not found in action={'thought': 'making a list of basic arithmetic operations'}"
Traceback (most recent call last):
  File "/Users/ken/devel/ai/OpenDevin/opendevin/controller/agent_controller.py", line 136, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/devel/ai/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/devel/ai/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 176, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/devel/ai/OpenDevin/opendevin/action/__init__.py", line 33, in action_from_dict
    raise KeyError(f"'action' key is not found in {action=}")
KeyError: "'action' key is not found in action={'thought': 'making a list of basic arithmetic operations'}"

OBSERVATION:
"'action' key is not found in action={'thought': 'making a list of basic arithmetic operations'}"
```

```
ERROR:
Invalid response: no JSON found
Traceback (most recent call last):
  File "/Users/ken/devel/ai/OpenDevin/opendevin/controller/agent_controller.py", line 136, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/devel/ai/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/devel/ai/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 159, in parse_action_response
    action_dict = json.loads(response)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/devel/ai/OpenDevin/agenthub/monologue_agent/utils/json.py", line 34, in loads
    raise ValueError('Invalid response: no JSON found')
ValueError: Invalid response: no JSON found
```

**Comment by yufansong** [comment]
```
KeyError: "'action' key is not found in action={'thought': 'making a list of basic arithmetic operations'}"

OBSERVATION:
"'action' key is not found in action={'thought': 'making a list of basic arithmetic operations'}"
```

```
  File "/Users/ken/devel/ai/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 159, in parse_action_response
    action_dict = json.loads(response)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/devel/ai/OpenDevin/agenthub/monologue_agent/utils/json.py", line 34, in loads
    raise ValueError('Invalid response: no JSON found')
ValueError: Invalid response: no JSON found

```
Seems the LLM did not return a predefined actions. The LLM sending back malformed actions, which is somewhat expected.  Currently, we don't have too much methods to improve the LLM quality. 😔

**Comment by rbren** [comment]
Deduping with https://github.com/OpenDevin/OpenDevin/issues/326
