### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by arwahdevops** [OpenDevin/OpenDevin#1060]
#### Describe the bug

An error occurred when running the `make build` command

**Commands I ran to install and run OpenDevin**:
```
make build
```

**Logs, error messages, and screenshots**:
```
Traceback (most recent call last):
  File "/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/bin/pre-commit", line 5, in <module>
    from pre_commit.main import main
  File "/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/lib/python3.11/site-packages/pre_commit/main.py", line 14, in <module>
    from pre_commit.commands.clean import clean
  File "/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/lib/python3.11/site-packages/pre_commit/commands/clean.py", line 6, in <module>
    from pre_commit.store import Store
  File "/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/lib/python3.11/site-packages/pre_commit/store.py", line 6, in <module>
    import sqlite3
  File "/usr/local/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
make[1]: *** [Makefile:105: install-precommit-hooks] Error 1
make: *** [Makefile:27: build] Error 2
```

**Comment by yufansong** [comment]
Maybe you can check whether #831 can help.

**Comment by anthonyrawlins** [comment]
I built Python 3.12 from source and got this error. I then installed libsqlite3-dev using apt and then rebuilt Python3.12. I ran make build again with no errors.

**Comment by arwahdevops** [comment]
Thanks @anthonyrawlins i was success by installing `libsqlite3-dev` and rebuild with this :
```
sudo apt update

sudo apt install build-essential libsqlite3-dev zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget

cd /tmp

wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz

tar -xf Python-3.11.9.tgz

cd Python-3.11.9

./configure --enable-optimizations

sudo make altinstall

sudo make install
```

**Comment by arwahdevops** [comment]
i have more problem while `make run` :
```
Running the app...
Starting backend server...
Waiting for the backend to start...
/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/xrick/.cache/pypoetry/virtualenvs/opendevin-xfiXNSGw-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
 ```
 My config : 
 ```
LLM_MODEL="gpt-3.5-turbo-1106"
LLM_API_KEY="sk-*******************"
LLM_EMBEDDING_MODEL="openai"
WORKSPACE_DIR="./workspace"
```

**Comment by SmartManoj** [comment]
those are just warnings; run  `poetry update litellm`

**Comment by arwahdevops** [comment]
> those are just warnings; run `poetry update litellm`

thanks my friend
