### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by ls-cnr** [OpenDevin/OpenDevin#1073]
#### Describe the bug
Mybe you aready know, but since a few days, make build command return with errors
here the output copied and paste from my terminal:

```
Building project...
Checking dependencies...
Checking Python installation...
Python 3.10.4 is already installed.
Checking npm installation...
npm 10.5.0 is already installed.
Checking Docker installation...
Docker version 26.0.0, build 2ae903e86c is already installed.
Checking Poetry installation...
Poetry (version 1.8.2) is already installed.
Dependencies checked successfully.
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:b051045dd07803ec72da0342fca84d287f77c46ebde0ee2d57f551b863c8894e
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
Docker image pulled successfully.
Installing Python dependencies...
/bin/sh: chroma-hnswlib: command not found
Installing ...
Creating virtualenv opendevin-CzhE0puH-py3.12 in /Users/luca/Library/Caches/pypoetry/virtualenvs
Collecting chroma-hnswlib
  Downloading chroma-hnswlib-0.7.3.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/Users/luca/Library/Caches/pypoetry/virtualenvs/opendevin-CzhE0puH-py3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/luca/Library/Caches/pypoetry/virtualenvs/opendevin-CzhE0puH-py3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/luca/Library/Caches/pypoetry/virtualenvs/opendevin-CzhE0puH-py3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/z6/q0ffqlp91x78611qxm07p9hc0000gn/T/pip-build-env-5qwbsb2i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/z6/q0ffqlp91x78611qxm07p9hc0000gn/T/pip-build-env-5qwbsb2i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/z6/q0ffqlp91x78611qxm07p9hc0000gn/T/pip-build-env-5qwbsb2i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 73, in <module>
        File "<string>", line 90, in BuildExt
      ValueError: list.remove(x): x not in list
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
make[1]: *** [install-python-dependencies] Error 1
make: *** [build] Error 2

```

#### Setup and configuration
**Current version**:
```
commit 2326312d3a297a5027b83018c0a5e0421ff74285 (HEAD -> main, origin/main, origin/HEAD)
Author: Leo <ifuryst@gmail.com>
Date:   Sat Apr 13 10:18:34 2024 +0800
```

I am playing on a MacBook M1 with sonoma

**Commands I ran to install and run OpenDevin**:
```
git clone https://github.com/OpenDevin/OpenDevin.git
cd OpenDevin
make build
```

**Comment by ls-cnr** [comment]
Maybe I solved: the problem was I added SANDBOX_TYPE=exec to config whereas the right way is SANDBOX_TYPE="exec" with ""
