### ISSUE TITLE
Failed to run llama2 locally

### ISSUE THREAD

**Issue by hugozanini** [OpenDevin/OpenDevin#1079]
#### Describe the bug
I tried to run the llama2 model locally using ollama, but I'm getting the following error when running the prompt "hello" in the interface:

````
PLAN:
hello

ERROR:
Extra data: line 1 column 5 (char 4)
Traceback (most recent call last):
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/opendevin/controller/agent_controller.py", line 145, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/agenthub/monologue_agent/agent.py", line 203, in step
    self._initialize(state.plan.main_goal)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/agenthub/monologue_agent/agent.py", line 190, in _initialize
    self._add_event(action.to_dict())
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/agenthub/monologue_agent/agent.py", line 121, in _add_event
    self.memory.add_event(event)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/agenthub/monologue_agent/utils/memory.py", line 86, in add_event
    self.index.insert(doc)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 242, in insert
    self.insert_nodes(nodes, **insert_kwargs)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 330, in insert_nodes
    self._insert(nodes, **insert_kwargs)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 312, in _insert
    self._add_nodes_to_index(self._index_struct, nodes, **insert_kwargs)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 233, in _add_nodes_to_index
    nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 141, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
                      ^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/utils.py", line 138, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 211, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 326, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/embeddings/ollama/base.py", line 64, in _get_text_embeddings
    embeddings = self.get_general_text_embedding(text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/embeddings/ollama/base.py", line 96, in get_general_text_embedding
    optional_detail = response.json().get("error")
                      ^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)

OBSERVATION:
Extra data: line 1 column 5 (char 4)
16:05:08 - opendevin:INFO: agent_controller.py:124 - Exited before finishing the task.

````

When looking into the Ollama server, I saw that it receives requests, but return 404 in all cases:

````
[GIN] 2024/04/13 - 16:05:08 | 404 |       3.965µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |       4.364µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |       3.975µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |       5.402µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |       3.616µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |         5.1µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |       3.983µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |        5.04µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |        9.09µs |       127.0.0.1 | POST     "//api/embeddings"
[GIN] 2024/04/13 - 16:05:08 | 404 |       5.291µs |       127.0.0.1 | POST     "//api/embeddings"
````

#### Setup and configuration
**Current version**:
```
Author: Akki <akhilvc10@gmail.com>
Date:   Sat Apr 13 19:52:26 2024 +0400

    fix(editor): ui enhancements and code refactor (#1069)
```

**My config.toml and environment vars**:
```
LLM_MODEL="ollama/llama2"
LLM_API_KEY="ollama"
LLM_BASE_URL="http://localhost:11434/"
LLM_EMBEDDING_MODEL="llama2"
WORKSPACE_DIR="/Users/hugo.zanini/Documents/projects/devin-experiments/devin-dir/"
```

**My model and agent** (from the UI):
* Model: empty
* Agent: MonologueAgent

**Comment by enyst** [comment]
Can you try with LLM_EMBEDDING_MODEL="local" ?

**Comment by hugozanini** [comment]
Thanks for answering. Yes, I just ran and got the same error:

````
PLAN:
hello

ERROR:
Extra data: line 1 column 5 (char 4)
Traceback (most recent call last):
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/opendevin/controller/agent_controller.py", line 145, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/agenthub/monologue_agent/agent.py", line 203, in step
    self._initialize(state.plan.main_goal)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/agenthub/monologue_agent/agent.py", line 190, in _initialize
    self._add_event(action.to_dict())
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/agenthub/monologue_agent/agent.py", line 121, in _add_event
    self.memory.add_event(event)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/agenthub/monologue_agent/utils/memory.py", line 86, in add_event
    self.index.insert(doc)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 242, in insert
    self.insert_nodes(nodes, **insert_kwargs)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 330, in insert_nodes
    self._insert(nodes, **insert_kwargs)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 312, in _insert
    self._add_nodes_to_index(self._index_struct, nodes, **insert_kwargs)
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 233, in _add_nodes_to_index
    nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 141, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
                      ^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/indices/utils.py", line 138, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 211, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 326, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/embeddings/ollama/base.py", line 64, in _get_text_embeddings
    embeddings = self.get_general_text_embedding(text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/llama_index/embeddings/ollama/base.py", line 96, in get_general_text_embedding
    optional_detail = response.json().get("error")
                      ^^^^^^^^^^^^^^^
  File "/Users/hugo.zanini/Documents/projects/devin-experiments/OpenDevin/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)
````

Ollama server also answered 404

**Comment by enyst** [comment]
So it does get to Ollama server but it doesn't find something. The model? According to [this documentation](https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/LOCAL_LLM_GUIDE.md#5-modify-config-file), the Ollama model needs to be the full name of the model. Can you identify and try another name, a full name?

**Comment by hugozanini** [comment]
I tried with `ollama/llama2:13b-chat-q4_K_M` and got the same error :(

**Comment by enyst** [comment]
Run this to verify what models you have downloaded:
```
ollama list
```

You may need to check out all the steps of the guide I linked, particularly the first steps, how to set up Ollama to serve the model you want to use. Here: https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/LOCAL_LLM_GUIDE.md#1-install-models

**Comment by hugozanini** [comment]
These are the models I have:

<img width="530" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/18446486/f85586ed-2e16-4e15-b5a0-704a49a940c0">

I have already tried all of them, I also had followed multiple times the steps to build, run and configure the `.toml`.  Are local models working for you? I guess there is a problem with the payload being used when calling the ollama endpoint, but I'm not being able to figure our what it is.

**Comment by teohhc** [comment]
I am also running ollama locally but in docker compose. Was having trouble until i changed a few things:
1. LLM_MODEL: must be exactly what you see in the "ollama list"
2. LLM_EMBEDDING_MODEL: needs to be local
3. SANDBOX_TYPE: needs to be exec, was getting ssh error I think.
4. LLM_BASE_URL: localhost just to be sure it can resolve the hostname

LLM_MODEL="ollama/dolphin-mistral:latest"
LLM_API_KEY="ollama"
LLM_BASE_URL="http://localhost:11434"
LLM_EMBEDDING_MODEL="local"
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE="exec"

Hope this helps

**Comment by hugozanini** [comment]
It solved! Thanks a lot
