### ISSUE TITLE
RuntimeError: Cannot close a running event loop

### ISSUE THREAD

**Issue by Maindraster** [OpenDevin/OpenDevin#1201]
#### The promblem
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 534, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 300, in uvloop.loop.Loop._setup_or_resume_signals
  File "/usr/local/lib/python3.12/socket.py", line 609, in socketpair
    a, b = _socket.socketpair(family, type, proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 70, in close
    _cancel_all_tasks(loop)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 205, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 518, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 193, in run
    with Runner(debug=debug, loop_factory=loop_factory) as runner:
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 62, in __exit__
    self.close()
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 77, in close
    loop.close()
  File "uvloop/loop.pyx", line 1391, in uvloop.loop.Loop.close
  File "uvloop/loop.pyx", line 561, in uvloop.loop.Loop._close
RuntimeError: Cannot close a running event loop
Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<Server.serve() running at /app/.venv/lib/python3.12/site-packages/uvicorn/server.py:67> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767]>
sys:1: RuntimeWarning: coroutine 'Server.serve' was never awaited

#### Setup and configuration

**My operating system**:Ubuntu 20.04

**My model and agent** (you can see these settings in the UI):
* Model:gpt-3.5-turbo-1106
I think there is no problem with my api key.

**Commands I ran to install and run OpenDevin**:
git clone ……
make build
make setup-config
export WORKSPACE_DIR=/home/indra/OpenDevin/workspace
docker run \
    -e LLM_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR \
    -v $WORKSPACE_DIR:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:main

**Comment by Umpire2018** [comment]
Please upload full log. I can't reproduce your error.

```shell
 docker run \
    -e LLM_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR \
    -v $WORKSPACE_DIR:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:main
Unable to find image 'ghcr.io/opendevin/opendevin:main' locally
main: Pulling from opendevin/opendevin
26070551e657: Pull complete 
a86293a104ae: Pull complete 
72bc35340845: Pull complete 
14d203a4c9c5: Pull complete 
09f0810bb722: Pull complete 
9a8f56145c1f: Pull complete 
b3cccd99c770: Pull complete 
6293b0c6a529: Pull complete 
bb838c83cf51: Pull complete 
18e8f228f1c9: Pull complete 
7cd4f916bd5d: Pull complete 
607d76ead4a8: Pull complete 
287c16fc93cc: Pull complete 
Digest: sha256:e5963aef0d4815b48299fe469ef5cd544e34a313d452dbf23e1af8a0f095dda2
Status: Downloaded newer image for ghcr.io/opendevin/opendevin:main
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
```

**Comment by rbren** [comment]
Strange, this is a pretty happy install path--everything works fine for me on ubuntu.

```
a, b = _socket.socketpair(family, type, proto)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied
```

This suggests maybe you don't have permission to listen on port 3000?
