### ISSUE TITLE
OOB instructions fail: ExceptionPxssh('Could not establish connection to host')

### ISSUE THREAD

**Issue by dagelf** [OpenDevin/OpenDevin#1249]
#### Describe the bug
When following the instructions on the main page, the app fails

#### Setup and configuration
**Current version**:
Also, the bug report template doesn't accomodate for docker deployment as recommended on the front page. 
```bash
$ docker exec -ti 696 git log -n1
OCI runtime exec failed: exec failed: unable to start container process: exec: "git": executable file not found in $PATH: unknown
But it's 0.3.1
```

**My operating system**:
The point of docker is to make the OS irrelevant, but it is Ubuntu 22.04 fully updated.

**My environment vars and other configuration**
```bash
LLM_API_KEY=xxx # if the key should be OPENAI_API_KEY, etc, it should clearly be stipulated, and a false environment variable shouldn't be in the docs. 
```

**My model and agent** 
Whatever the defaults are

**Commands I ran to install and run OpenDevin**:
```
LLM_API_KEY=sk-... docker run     -e LLM_API_KEY     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR     -v $WORKSPACE_DIR:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     ghcr.io/opendevin/opendevin:0.3.1

```

**Steps to Reproduce**:
1. `LLM_API_KEY=sk-  docker run     -e LLM_API_KEY     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR     -v $WORKSPACE_DIR:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     ghcr.io/opendevin/opendevin:0.3.1`

**Logs, error messages, and screenshots**:
```
 LLM_API_KEY=sk-  docker run     -e LLM_API_KEY     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR     -v $WORKSPACE_DIR:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     ghcr.io/opendevin/opendevin:0.3.1
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     172.17.0.1:39412 - "GET /index.html HTTP/1.1" 304 Not Modified
INFO:     172.17.0.1:39420 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     172.17.0.1:39420 - "GET /api/configurations HTTP/1.1" 200 OK
INFO:     172.17.0.1:39426 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:39420 - "GET /index.html HTTP/1.1" 304 Not Modified
INFO:     172.17.0.1:39428 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     172.17.0.1:39428 - "GET /api/configurations HTTP/1.1" 200 OK
INFO:     172.17.0.1:39442 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     ('172.17.0.1', 39458) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIwM2U4NjNlYi01MDI2LTQ3YmQtOGNkMS1hZDI4MmNiMzYwY2MifQ.z9PtK22gw64K9kyjguAk2LImT01jwCTl9oP7_PKiYUY" [accepted]
INFO:     connection open
INFO:     ('172.17.0.1', 39470) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIwM2U4NjNlYi01MDI2LTQ3YmQtOGNkMS1hZDI4MmNiMzYwY2MifQ.z9PtK22gw64K9kyjguAk2LImT01jwCTl9oP7_PKiYUY" [accepted]
INFO:     connection open
Starting loop_recv for sid: 03e863eb-5026-47bd-8cd1-ad282cb360cc
Starting loop_recv for sid: 03e863eb-5026-47bd-8cd1-ad282cb360cc
INFO:     172.17.0.1:39442 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:39428 - "GET /api/configurations HTTP/1.1" 200 OK
11:50:41 - opendevin:INFO: ssh_box.py:271 - Container stopped
11:50:41 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
11:50:41 - opendevin:INFO: ssh_box.py:309 - Container started
11:50:42 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
11:50:43 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 51349 root@host.docker.internal` with the password '217bec29-ffa5-4399-932e-ec97e2743c63' and report the issue on GitHub.
11:50:43 - opendevin:ERROR: agent.py:127 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 118, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 51, in __init__
    self.command_manager = CommandManager(self.id, container_image)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/command_manager.py", line 26, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/ssh_box.py", line 90, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/ssh_box.py", line 164, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
Mounting workspace directory:  /home/coenraad/devin
INFO:     172.17.0.1:39442 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:39428 - "GET /api/configurations HTTP/1.1" 200 OK
11:50:44 - opendevin:INFO: ssh_box.py:271 - Container stopped
11:50:44 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
11:50:45 - opendevin:INFO: ssh_box.py:309 - Container started
11:50:46 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
11:50:46 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 35697 root@host.docker.internal` with the password '596adc00-c062-4819-bd82-e27743faa860' and report the issue on GitHub.
11:50:46 - opendevin:ERROR: agent.py:127 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 118, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 51, in __init__
    self.command_manager = CommandManager(self.id, container_image)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/command_manager.py", line 26, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/ssh_box.py", line 90, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/ssh_box.py", line 164, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
Mounting workspace directory:  /home/coenraad/devin
INFO:     172.17.0.1:39428 - "DELETE /api/messages HTTP/1.1" 200 OK
INFO:     172.17.0.1:39832 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     172.17.0.1:39832 - "GET /api/litellm-agents HTTP/1.1" 200 OK
11:51:27 - opendevin:INFO: ssh_box.py:271 - Container stopped
11:51:27 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
11:51:28 - opendevin:INFO: ssh_box.py:309 - Container started
11:51:29 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
11:51:29 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 51049 root@host.docker.internal` with the password 'fa294f8b-a3c0-4cf9-bfcb-b9bbca181960' and report the issue on GitHub.
11:51:29 - opendevin:ERROR: agent.py:127 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 118, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 51, in __init__
    self.command_manager = CommandManager(self.id, container_image)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/command_manager.py", line 26, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/ssh_box.py", line 90, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/ssh_box.py", line 164, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
^CINFO:     Shutting down
11:51:32 - opendevin:INFO: session.py:39 - WebSocket disconnected, sid: 03e863eb-5026-47bd-8cd1-ad282cb360cc
11:51:32 - opendevin:INFO: session.py:39 - WebSocket disconnected, sid: 03e863eb-5026-47bd-8cd1-ad282cb360cc
INFO:     connection closed
INFO:     connection closed
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1]

Aborted!
Mounting workspace directory:  /home/coenraad/devin
^CException ignored in atexit callback: <bound method Client.join of <posthog.client.Client object at 0x7f37f3f34ce0>>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/posthog/client.py", line 416, in join
    consumer.join()
  File "/usr/local/lib/python3.12/threading.py", line 1147, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.12/threading.py", line 1167, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
11:51:32 - opendevin:INFO: manager.py:36 - Closing 1 agent(s)...
11:51:32 - opendevin:INFO: manager.py:37 - Saving sessions...
11:51:32 - opendevin:INFO: msg_stack.py:42 - Saving messages...

```

#### Additional Context
Build community by having a great first run out-of-box experience without any tweaking or too much reading required.

**Comment by rbren** [comment]
@dagelf watch out for those API keys in your logs! I edited to redact them

Deduping with https://github.com/OpenDevin/OpenDevin/issues/1156

**Comment by dagelf** [comment]
Loving the fast response on here :+1:
