### ISSUE TITLE
[WSL] Local mistral model not sent to litellm

### ISSUE THREAD

**Issue by emirhantasdemirtg** [OpenDevin/OpenDevin#1395]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

im having this error on windows on wsl 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

02:15:30 - opendevin:ERROR: agent_controller.py:103 - Error in loop
Traceback (most recent call last):
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 373, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 581, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1232, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1012, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/main.py", line 1010, in completion
    raise e
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/main.py", line 983, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 420, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: 404 page not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emir/OpenDevin/opendevin/controller/agent_controller.py", line 99, in _run
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/home/emir/OpenDevin/opendevin/controller/agent_controller.py", line 212, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/OpenDevin/agenthub/monologue_agent/agent.py", line 226, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/emir/OpenDevin/opendevin/llm/llm.py", line 79, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 2977, in wrapper
    raise e
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 2875, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2137, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8665, in exception_type
    raise e
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7461, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: OpenAIException - 404 page not found

### Current Version

```bash
ghcr.io/opendevin/sandbox:main
```

### Installation and Configuration

```bash
debian wsl on windows
```

### Model and Agent

mistral local

### Reproduction Steps

123

### Logs, Errors, Screenshots, and Additional Context

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

02:15:30 - opendevin:ERROR: agent_controller.py:103 - Error in loop
Traceback (most recent call last):
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 373, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 581, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1232, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1012, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/main.py", line 1010, in completion
    raise e
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/main.py", line 983, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 420, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: 404 page not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emir/OpenDevin/opendevin/controller/agent_controller.py", line 99, in _run
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/home/emir/OpenDevin/opendevin/controller/agent_controller.py", line 212, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/OpenDevin/agenthub/monologue_agent/agent.py", line 226, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/emir/OpenDevin/opendevin/llm/llm.py", line 79, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 2977, in wrapper
    raise e
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 2875, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2137, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8665, in exception_type
    raise e
  File "/home/emir/.cache/pypoetry/virtualenvs/opendevin-yfq3wX0t-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7461, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: OpenAIException - 404 page not found

**Comment by SmartManoj** [comment]
value of LLM_MODEL?

**Comment by rbren** [comment]
@emirhantasdemirtg we'll need more info about your setup. Did you follow the guide here? https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/LocalLLMs.md

**Comment by SmartManoj** [comment]
`LLM_MODEL` is not used in 2.1 in the docs.
