### ISSUE TITLE
[Bug]: [SSH box] could not set shell prompt from agent.py

### ISSUE THREAD

**Issue by fkeet** [OpenDevin/OpenDevin#1396]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

Agent never finishes initializing

### Current Version

```bash
ghcr.io/opendevin/opendevin:0.4.0
```

### Installation and Configuration

```bash
Ran it with

LLM_API_KEY="11111111111111111111"
WORKSPACE_DIR="workspace"
LLM_BASE_URL="http://localhost:11434"
LLM_MODEL= "ollama/llama2"
LLM_EMBEDDING_MODEL="llama2"
docker run \
    -e LLM_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.4.0
```

### Model and Agent

gpt-3.5-turbo
MonologueAgent

### Reproduction Steps

Just run it as specified in the 'install and configuration' data.

### Logs, Errors, Screenshots, and Additional Context

INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)

INFO:     172.17.0.1:54586 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     ('172.17.0.1', 54598) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJkNjg4ZmEyNS01OTBjLTRm
NjktODI0ZS0zMjRhY2NiNTFkMDUifQ.59989QLgSv3FWjXanHlHJ7KpnpjeGYMxOLJd7AOTbXg" [accepted]
INFO:     connection open
Starting loop_recv for sid: d688fa25-590c-4f69-824e-324accb51d05
INFO:     172.17.0.1:54626 - "GET /apple-touch-icon.png HTTP/1.1" 200 OK
INFO:     172.17.0.1:54640 - "GET /favicon-16x16.png HTTP/1.1" 200 OK
INFO:     172.17.0.1:54646 - "GET /api/refresh-files HTTP/1.1" 200 OK
03:55:30 - opendevin:INFO: agent.py:144 - Creating agent MonologueAgent using LLM gpt-3.5-turbo
03:55:30 - opendevin:INFO: llm.py:51 - Initializing LLM with model: gpt-3.5-turbo
03:55:32 - opendevin:INFO: ssh_box.py:353 - Container stopped
03:55:32 - opendevin:INFO: ssh_box.py:373 - Mounting workspace directory: /opt/workspace_base
03:55:32 - opendevin:INFO: ssh_box.py:396 - Container started
03:55:33 - opendevin:INFO: ssh_box.py:413 - waiting for container to start: 1, container status: running
03:55:33 - opendevin:INFO: ssh_box.py:178 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, yo
u can try `ssh -v -p 42679 root@host.docker.internal` with the password '7a559858-7077-4dca-86bf-c75fe3c47adf' and report th
e issue on GitHub.

03:56:15 - opendevin:ERROR: agent.py:155 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_C
OMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '
\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 147, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 57, in __init__
    self.action_manager = ActionManager(self.id)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 33, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/docker/ssh_box.py", line 91, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/docker/ssh_box.py", line 181, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset pro
mpt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
INFO:     172.17.0.1:54646 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     172.17.0.1:54662 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:54646 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     172.17.0.1:56432 - "DELETE /api/messages HTTP/1.1" 200 OK

**Comment by isavita** [comment]
I am getting the same error when try to run a container with setup for `ollama`
```bash
INFO:     192.168.65.1:36418 - "GET /api/refresh-files HTTP/1.1" 200 OK
09:48:16 - opendevin:INFO: agent.py:144 - Creating agent MonologueAgent using LLM gpt-3.5-turbo
09:48:16 - opendevin:INFO: llm.py:52 - Initializing LLM with model: gpt-3.5-turbo
09:48:17 - opendevin:INFO: ssh_box.py:353 - Container stopped
09:48:17 - opendevin:INFO: ssh_box.py:373 - Mounting workspace directory: /Users/isavita/code/workspace
09:48:17 - opendevin:INFO: ssh_box.py:396 - Container started
09:48:18 - opendevin:INFO: ssh_box.py:413 - waiting for container to start: 1, container status: running
09:48:18 - opendevin:INFO: ssh_box.py:178 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 58857 root@host.docker.internal` with the password 'be199796-fa72-4d92-b999-dee6212ac431' and report the issue on GitHub.
09:48:18 - opendevin:ERROR: agent.py:155 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 147, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 58, in __init__
    self.action_manager = ActionManager(self.id)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 33, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/docker/ssh_box.py", line 91, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/docker/ssh_box.py", line 181, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
INFO:     192.168.65.1:36418 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     192.168.65.1:36423 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     192.168.65.1:36418 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     192.168.65.1:36418 - "GET /api/messages HTTP/1.1" 200 OK
```
When I run `ssh -v -p 58857 root@host.docker.internal`
```bash
$> ssh -v -p 58857 root@host.docker.internal
OpenSSH_9.6p1, LibreSSL 3.3.6
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to host.docker.internal port 58857.
ssh: Could not resolve hostname host.docker.internal: nodename nor servname provided, or not known
```
This is my `docker ps` output
```bash
$> docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS                    NAMES
7594257b4080   ghcr.io/opendevin/sandbox:main     "/usr/sbin/sshd -D -…"   36 seconds ago   Up 35 seconds                            opendevin-sandbox-dedd3ce7-3e20-4793-aa6a-15308bf4a69f
f9d37600ff54   ghcr.io/opendevin/opendevin:main   "uvicorn opendevin.s…"   27 minutes ago   Up 27 minutes   0.0.0.0:3000->3000/tcp   strange_easley
```
When I try to connect from the sandbox container to ollama on the host machine all works perfectly
```bash
$> docker exec -it a5853e0b00df curl http://host.docker.internal:1143                                                                
Ollama is running
```
It seems the issue is when the `opendevin` container tries to connect to the `sandbox` container. Any idea how to fix this issue?

### Here is information for my setup
1. I am running on macos
```bash
$> sw_vers
ProductName:		macOS
ProductVersion:		14.4.1
BuildVersion:		23E224
```
2. Here is the output from `docker version`
```bash
$> docker version
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

**Comment by rbren** [comment]
🤔 This seems distinct from https://github.com/OpenDevin/OpenDevin/issues/1156

**Comment by rbren** [comment]
@isavita you should look at https://github.com/OpenDevin/OpenDevin/issues/1156 and the relevant troubleshooting section. OP's issue seems different

**Comment by rbren** [comment]
CC @xingyaoww

**Comment by isavita** [comment]
I have a little be more info.
When I run `docker inspect ddb2cf27f183` (this is the sandbox container).
```bash
$> docker inspect ddb2cf27f183
[
    {
        "Id": "ddb2cf27f1839cc...",
        "Created": "2024-04-27T10:12:49.700099011Z",
        "Path": "/usr/sbin/sshd",
        "Args": [
            "-D",
            "-p",
            "60465",
            "-o",
            "PermitRootLogin=yes"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 6110,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-04-27T10:12:49.770992178Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:1c70cf6ee5a4b4de696b1f6c07b76a6b9e72e502144ccb207e8f26b5c90e9bf3",
        "ResolvConfPath": "/var/lib/docker/containers/ddb2cf27f1839cc.../resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ddb2cf27f1839cc.../hostname",
        "HostsPath": "/var/lib/docker/containers/ddb2cf27f1839cc.../hosts",
        "LogPath": "/var/lib/docker/containers/ddb2cf27f1839cc.../ddb2cf27f1839cc...-json.log",
        "Name": "/opendevin-sandbox-dedd3ce7-3e20-4793-aa6a-15308bf4a69f",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/Users/myuser/code/workspace:/workspace:rw",
                "/tmp/cache:/root/.cache:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/9f40b774667a21a...-init/diff:/var/lib/docker/overlay2/35a21a21f4872790cac51165fd06473b9423355d9177918fd85539ec03dda982/diff:/var/lib/docker/overlay2/75ab1c08331247ad01bf20efeb8bd2f86a264aa0a52f35521083469c07ad5833/diff:/var/lib/docker/overlay2/c6fc09f73c2060a9d5a63b1e55003bfa85fc4667dc082f36fd4ec4906a676590/diff:/var/lib/docker/overlay2/239eea644434a0e5cf9bfa687ef5a0378035dfbf024608417370751893eee1cf/diff",
                "MergedDir": "/var/lib/docker/overlay2/9f40b774667a21a.../merged",
                "UpperDir": "/var/lib/docker/overlay2/9f40b774667a21a.../diff",
                "WorkDir": "/var/lib/docker/overlay2/9f40b774667a21a.../work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/myuser/code/workspace",
                "Destination": "/workspace",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/tmp/cache",
                "Destination": "/root/.cache",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "opendevin_sandbox",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/usr/sbin/sshd",
                "-D",
                "-p",
                "60465",
                "-o",
                "PermitRootLogin=yes"
            ],
            "Image": "ghcr.io/opendevin/sandbox:main",
            "Volumes": {
                "/root/.cache": {},
                "/workspace": {}
            },
            "WorkingDir": "/workspace",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.version": "22.04"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "48150f241c98f35e6312744b361d857a652689056505b07b4976916ed4d6379d",
            "SandboxKey": "/var/run/docker/netns/default",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "MacAddress": "",
                    "NetworkID": "9b0e3f1018ff800...",
                    "EndpointID": "b6081ca52b1368c...",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": null
                }
            }
        }
    }
]
```
When I connect to `opendevin` docker and try to connect to the sandbox I get
```bash
$> docker exec -it eed7df2a4fe6 /bin/bash
root@eed7df2a4fe6:/app# ssh -p 60465 root@host.docker.internal
ssh: connect to host host.docker.internal port 60465: Connection refused
```
It seems like I simply cannot connect from `opendevin` to `sandbox`.
When I inspect 
```bash
$> docker exec -it ddb2cf27f183 /bin/bash 
root@opendevin_sandbox:/workspace# grep 'Port' /etc/ssh/sshd_config
#Port 22
#GatewayPorts no
```
I cannot see `Port 60465`.

**Comment by xingyaoww** [comment]
@rbren do you this is an issue caused by `network=host` for the `app` container?

Will https://github.com/OpenDevin/OpenDevin/pull/1404 (`v0.4.1`) fix it?

**Comment by isavita** [comment]
@xingyaoww @rbren pulling the latest image fix the problem

**Comment by xingyaoww** [comment]
Thanks for letting us know! It seems like `network=host` on the DooD setup causes the issue

**Comment by SmartManoj** [comment]
Pass `-e SANDBOX_TYPE=exec` in the command to switch to the ExecBox docker container

**Comment by SmartManoj** [comment]
But the OP's issues is different.
