### ISSUE TITLE
[Bug]: OpenDevin can't initialize agent

### ISSUE THREAD

**Issue by elhakimz** [OpenDevin/OpenDevin#1498]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I am using Docker Desktop for Windows 11  for running OpenDevin, 
this is my batch file

@echo off
setlocal

:: Check if the workspace base path parameter is provided
if "%~1"=="" (
    echo Usage: %~nx0 [WORKSPACE_BASE_PATH]
    exit /b
)

:: Set the WORKSPACE_BASE environment variable
set "WORKSPACE_BASE=%~1"

:: Run the Docker command with the environment variable
docker run ^
    -e LLM_API_KEY="ollama" ^
    -e LLM_BASE_URL="http://host.docker.internal:11434" ^
    -e WORKSPACE_MOUNT_PATH=%WORKSPACE_BASE% ^
    -v %WORKSPACE_BASE%:/opt/workspace_base ^
    -v c:/var/run/docker.sock:/var/run/docker.sock ^
    -p 3000:3000 ^
    ghcr.io/opendevin/opendevin:main

endlocal

the agent cant be initialized 

![image](https://github.com/OpenDevin/OpenDevin/assets/616176/8149e573-9c44-485e-bda1-83755fcea5de)

and this is last error I've found in the log

19:06:48 - opendevin:INFO: agent.py:144 - Creating agent MonologueAgent using LLM ollama/codellama
19:06:48 - opendevin:INFO: llm.py:67 - Initializing LLM with model: ollama/codellama
19:06:48 - opendevin:ERROR: ssh_box.py:69 - Error creating controller. Please check Docker is running and visit `https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md` for more debugging information.
19:06:48 - opendevin:ERROR: agent.py:155 - Error creating controller: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 213, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 236, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 147, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 58, in __init__
    self.action_manager = ActionManager(self.id)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 36, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/docker/ssh_box.py", line 71, in __init__
    raise ex
  File "/app/opendevin/sandbox/docker/ssh_box.py", line 67, in __init__
    self.docker_client = docker.from_env()
                         ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/client.py", line 94, in from_env
    return cls(
           ^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 220, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused')) 

how to work around this ?

Thank you

### Current Version

```bash
ghcr.io/opendevin/opendevin:main
```

### Installation and Configuration

```bash
opendevin.bat

@echo off
setlocal

:: Check if the workspace base path parameter is provided
if "%~1"=="" (
    echo Usage: %~nx0 [WORKSPACE_BASE_PATH]
    exit /b
)

:: Set the WORKSPACE_BASE environment variable
set "WORKSPACE_BASE=%~1"

:: Run the Docker command with the environment variable
docker run ^
    -e LLM_API_KEY="ollama" ^
    -e LLM_BASE_URL="http://host.docker.internal:11434" ^
    -e WORKSPACE_MOUNT_PATH=%WORKSPACE_BASE% ^
    -v %WORKSPACE_BASE%:/opt/workspace_base ^
    -v c:/var/run/docker.sock:/var/run/docker.sock ^
    -p 3000:3000 ^
    ghcr.io/opendevin/opendevin:main

endlocal
```

**Comment by xingyaoww** [comment]
Are you using MacOS? Did you lauched your `Docker Desktop` Application?

**Comment by rbren** [comment]
@elhakimz it looks like you're trying to run inside of windows directly. Can you try running inside WSL?

**Comment by elhakimz** [comment]
> @elhakimz it looks like you're trying to run inside of windows directly. Can you try running inside WSL?

done doing it in WSL and add -e sandbox=exec at docker call, anyway it wouldn't run 
the agents are running.. but the result are messy... even it cant create a simple "hello world" program in python correctly

**Comment by xingyaoww** [comment]
Can you attach the full error log if you are not adding `-e sandbox`? Which agent & model are you using? Our next release will come soon, and hopefully, it resolve the issue. :)
