### ISSUE TITLE
OpenAIException - Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

### ISSUE THREAD

**Issue by G0erman** [OpenDevin/OpenDevin#1504]
## Describe your question

Hi,

I am testing OpenDevin on my Mac, I am using the development image `ghcr.io/opendevin/opendevin:main` because with version 0.4.0 I ran into this issue: `https://github.com/OpenDevin/OpenDevin/issues/1156`.

However, I am now facing a new issue, I got the message `litellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}`.

## Additional context

* I am using Colima on Darwin Kernel Version 23.2.0.
* I set the Azure OpenAI environment variables.

```
#export LLM_MODEL="azure/gpt-35-turbo-0613"
export LLM_MODEL="azure/gpt-4-1106-preview"
export LLM_API_VERSION="2023-07-01-preview"
```

I tested those models and credentials with `litellm.completion` and it worked.

Logs:

```bash
docker run \
    -e LLM_BASE_URL \
    -e LLM_API_KEY \
    -e LLM_MODEL \
    -e LLM_API_VERSION \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:main
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     172.17.0.1:38286 - "GET /index.html HTTP/1.1" 304 Not Modified
INFO:     ('172.17.0.1', 38290) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIyODVmMTBjOS0zMzI0LTRiZDUtOGQwZi1lNjY4ODA0ZWJkNmMifQ.fWQyq0UJ-evKznWgq4jvmVMeqBlloEU2EsDYtoOQPCA" [accepted]
INFO:     connection open
Starting loop_recv for sid: 285f10c9-3324-4bd5-8d0f-e668804ebd6c
INFO:     172.17.0.1:38286 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     172.17.0.1:38286 - "GET /api/litellm-models HTTP/1.1" 200 OK
23:09:27 - opendevin:INFO: agent.py:144 - Creating agent MonologueAgent using LLM gpt-3.5-turbo
23:09:27 - opendevin:INFO: llm.py:67 - Initializing LLM with model: gpt-3.5-turbo
23:09:27 - opendevin:INFO: ssh_box.py:323 - Container stopped
23:09:27 - opendevin:WARNING: ssh_box.py:335 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
23:09:27 - opendevin:INFO: ssh_box.py:343 - Mounting workspace directory: /Users/user/OpenDevin/workspace/devin_code
23:09:28 - opendevin:INFO: ssh_box.py:366 - Container started
23:09:29 - opendevin:INFO: ssh_box.py:383 - waiting for container to start: 1, container status: running
23:09:29 - opendevin:INFO: ssh_box.py:178 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 47255 root@host.docker.internal` with the password 'b2c6ce65-7215-482a-b2cd-3b9dea6717f7' and report the issue on GitHub.
INFO:     172.17.0.1:38292 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:38286 - "GET /api/agents HTTP/1.1" 200 OK


==============
STEP 0

23:09:55 - PLAN
Write a Python function that sum two numbers.
23:09:56 - opendevin:ERROR: agent_controller.py:103 - Error in loop
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai.py", line 373, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 579, in create
    return self._post(
           ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1232, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1012, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1014, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 987, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai.py", line 420, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 99, in _run
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 212, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/monologue_agent/agent.py", line 236, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 112, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3113, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3011, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2186, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 8906, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 7700, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
```

**Comment by rbren** [comment]
@G0erman did you set the model name in the UI settings?

**Comment by G0erman** [comment]
Nop, that was the think. Thank you!

![image](https://github.com/OpenDevin/OpenDevin/assets/20327812/c38f1d53-356e-49f3-a722-9e0853861b75)
