### ISSUE TITLE
[Bug]: AttributeError when adding subtasks with None parent_id with PlannerAgent

### ISSUE THREAD

**Issue by isavita** [OpenDevin/OpenDevin#1578]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

An **AttributeError** occurs when attempting to add a subtask with a **None** **parent_id**. This happens because the **parent_id** is not checked for **None** before attempting to use the split method on it. This bug affects the **Plan.add_subtask()** method where it fails to gracefully handle a **None** **parent_id** passed from actions such as **AddTaskAction**.

### Current Version

```bash
Running main branch commit 1d92e9a27bf67b856e71aa9d5c8f18d3919024ab
```

### Installation and Configuration

```bash
Standard installation and configuration used. I setup the model and the Agent using the UI.
```

### Model and Agent

**Model:** **ollama/llama3:8b-instruct-q8_0**
**Agent:** **PlannerAgent**

### Reproduction Steps

1. Initialize the **PlannerAgent** using the **ollama/llama3:8b-instruct-q8_0** model.
2. Attempt to add a subtask without specifying a **parent_id**, which defaults to **None**.
3. Observe the **AttributeError** triggered by the **add_subtask** method due to None being passed as **parent_id**.

### Logs, Errors, Screenshots, and Additional Context

<details>
<summary>Logs</summary>

```bash
15:37:19 - opendevin:INFO: browser_env.py:38 - Starting browser env...
INFO:     127.0.0.1:57305 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:57306 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:57311 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:57307 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:57312 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:57314 - "GET /api/agents HTTP/1.1" 200 OK
15:37:22 - opendevin:INFO: browser_env.py:51 - Browser env started.
INFO:     127.0.0.1:57318 - "DELETE /api/messages HTTP/1.1" 200 OK
INFO:     127.0.0.1:57320 - "GET /api/refresh-files HTTP/1.1" 200 OK
15:37:43 - opendevin:INFO: agent.py:156 - Creating agent PlannerAgent using LLM ollama/llama3:8b-instruct-q8_0
15:37:43 - opendevin:INFO: llm.py:71 - Initializing LLM with model: ollama/llama3:8b-instruct-q8_0
15:37:43 - opendevin:INFO: ssh_box.py:67 - SSHBox is running as opendevin user with USER_ID=501 in the sandbox
15:37:43 - opendevin:INFO: ssh_box.py:370 - Container stopped
15:37:43 - opendevin:WARNING: ssh_box.py:382 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
15:37:43 - opendevin:INFO: ssh_box.py:391 - Mounting workspace directory: /Users/isavita/code/workspace
15:37:44 - opendevin:INFO: ssh_box.py:412 - Container started
15:37:45 - opendevin:INFO: ssh_box.py:428 - waiting for container to start: 1, container status: running
15:37:45 - opendevin:INFO: ssh_box.py:191 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 57333 opendevin@localhost` with the password '3445c6eb-31e7-493f-ac9a-6f2507218c2b' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 57333 opendevin@localhost` with the password '3445c6eb-31e7-493f-ac9a-6f2507218c2b on the host machine (where you started the container).
15:37:46 - opendevin:INFO: browser_env.py:38 - Starting browser env...
15:37:49 - opendevin:INFO: browser_env.py:51 - Browser env started.


==============
STEP 0

15:37:59 - PLAN

## Context
Advent of Code is an annual series of programming challenges that take place in December. Each day, a new problem is released, and participants must write code to solve it.

## Task
--- Day 1: The Tyranny of the Rocket Equation ---
Santa has become stranded at the edge of the Solar System while delivering presents to other planets! To accurately calculate his position in space, safely align his warp drive, and return to Earth in time to save Christmas, he needs you to bring him measurements from fifty stars.

Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

The Elves quickly load you into a spacecraft and prepare to launch.

At the first Go / No Go poll, every Elf is Go until the Fuel Counter-Upper. They haven't determined the amount of fuel required yet.

Fuel required to launch a given module is based on its mass. Specifically, to find the fuel required for a module, take its mass, divide by three, round down, and subtract 2.

For example:

For a mass of 12, divide by 3 and round down to get 4, then subtract 2 to get 2.
For a mass of 14, dividing by 3 and rounding down still yields 4, so the fuel required is also 2.
For a mass of 1969, the fuel required is 654.
For a mass of 100756, the fuel required is 33583.
The Fuel Counter-Upper needs to know the total fuel requirement. To find it, individually calculate the fuel needed for the mass of each module (your puzzle input), then add together all the fuel values.

What is the sum of the fuel requirements for all of the modules on your spacecraft?

## Constraints
- You should implement the solution in Python.
- I will provide you with the input data as a file with the name 'input.txt'.
- The program should print the solution of the task to standard output (stdout) and you should provide me with the code file and the solution output.

## Instructions
1. You should break down the task into smaller sub-tasks and solve each sub-task using TDD(Test-Driven Development) approach.
2. You should write unit tests based on the task examples.
3. You should save and run the tests and the task solution to make sure they work as expected.

## Completion Criteria
- The program should print the correct answer to the task.
- You have run the task solution program and provide the answer to me.

15:37:59 - opendevin:INFO: prompt.py:190
INFO
HINT:

15:38:22 - ACTION
AddTaskAction(parent=None, goal='Calculate total fuel requirement for modules on spacecraft', subtasks=[], thought='', action='add_task')
15:38:22 - opendevin:ERROR: agent_controller.py:131 - Error in loop
Traceback (most recent call last):
  File "/Users/isavita/git/OpenDevin/opendevin/controller/agent_controller.py", line 127, in _run
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/isavita/git/OpenDevin/opendevin/controller/agent_controller.py", line 309, in step
    observation = await self.action_manager.run_action(action, self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isavita/git/OpenDevin/opendevin/controller/action_manager.py", line 51, in run_action
    observation = await action.run(agent_controller)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isavita/git/OpenDevin/opendevin/events/action/tasks.py", line 23, in run
    controller.state.plan.add_subtask(self.parent, self.goal, self.subtasks)
  File "/Users/isavita/git/OpenDevin/opendevin/controller/state/plan.py", line 197, in add_subtask
    parent = self.get_task_by_id(parent_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isavita/git/OpenDevin/opendevin/controller/state/plan.py", line 176, in get_task_by_id
    parts = [int(p) for p in id.split('.')]
                             ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
15:38:22 - opendevin:INFO: agent_controller.py:197 - Task state set to TaskState.STOPPED
INFO:     127.0.0.1:57368 - "GET /api/plan HTTP/1.1" 204 No Content
```
<details>

**Comment by SmartManoj** [comment]
Add llm logs that are stored in `logs/llm` folder

**Comment by SmartManoj** [comment]
There is an `llm` folder inside `logs` folder. Need that log

**Comment by SmartManoj** [comment]
Set `DEBUG=1`  in config
