### ISSUE TITLE
[Bug]: Linux/Ollama - [Errno 111] Connection refused

### ISSUE THREAD

**Issue by wmsmigiel** [OpenDevin/OpenDevin#1685]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Hi!

I'm trying to run OpenDevin on a Linux system and I'm having trouble connecting to Ollama.

The error:

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec02985760>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### Current Version

```bash
ghcr.io/opendevin/opendevin:1651-merge
```

### Installation and Configuration

```bash
OS: EndeavourOS Linux x86_64 
Kernel: 6.8.9-arch1-1 
```
Ollama works fine

```
> ollama run llama3:8b-instruct-q6_K
>>> test
It looks like you accidentally sent a blank message or the word "test". If you meant to ask me something
or have a conversation, feel free to start again and I'll do my best to help!
```

My user can execute docker without `sudo`

```
> docker run hello-world
Hello from Docker!
This message shows that your installation appears to be working correctly.
```

I encountered issues with the docker group not being created, so I'm running a merge from here - #1658. Workspace is set:
```
> export WORKSPACE_BASE=$(pwd)/Documents/ODworkspace 
```
and my docker command:

```
> docker run \
          --add-host host.docker.internal:host-gateway \
          -e SANDBOX_USER_ID=$(id -u) \
          -e LLM_API_KEY="my_key" \
          -e LLM_BASE_URL="http://host.docker.internal:11434" \
          -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
          -v $WORKSPACE_BASE:/opt/workspace_base \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -p 3000:3000 \
          ghcr.io/opendevin/opendevin:1651-merge
```

### Model and Agent

ollama/llama3:8b-instruct-q6_K
MonologueAgent

### Reproduction Steps

1. Run the OpenDevin server with the command above
2. Set ollama model in the ui 
3. Input a command

### Logs, Errors, Screenshots, and Additional Context

From the UI:

![image](https://github.com/OpenDevin/OpenDevin/assets/22399915/bdc7d18e-f864-4bf7-82cb-74853e240f70)

and after any command is run

![image](https://github.com/OpenDevin/OpenDevin/assets/22399915/2be92adb-308b-4e4b-bb89-b64dc4f35d68)

Ollama port is correct:

![image](https://github.com/OpenDevin/OpenDevin/assets/22399915/5d6ded32-c81b-4bb2-a3aa-a63c4b485af6)

Logs:
```
Starting OpenDevin...
Setting up enduser with id 1000
Docker socket group id: 954
Creating group with id 954
Running as enduser
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_group_retry_policy" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [40]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     172.17.0.1:32916 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     ('172.17.0.1', 32930) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI3NDg3ZDNlOS02MWNhLTRiYmMtOWEzYi05ZDE4Y2IxNzUzOGUifQ.xBsN94_mZDb7iR69HTzTz3TlOkPvteLWESnYr8UCfV8" [accepted]
INFO:     connection open
Starting loop_recv for sid: 7487d3e9-61ca-4bbc-9a3b-9d18cb17538e
INFO:     172.17.0.1:32940 - "GET /api/litellm-models HTTP/1.1" 200 OK
08:22:11 - opendevin:INFO: agent.py:112 - Creating agent MonologueAgent using LLM ollama/llama3:8b-instruct-q6_K
08:22:11 - opendevin:INFO: llm.py:111 - Initializing LLM with model: ollama/llama3:8b-instruct-q6_K
08:22:11 - opendevin:WARNING: llm.py:127 - Could not get model info for ollama/llama3:8b-instruct-q6_K
08:22:11 - opendevin:INFO: ssh_box.py:52 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
08:22:11 - opendevin:INFO: ssh_box.py:408 - Container stopped
08:22:11 - opendevin:WARNING: ssh_box.py:420 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
08:22:11 - opendevin:INFO: ssh_box.py:429 - Mounting workspace directory: /home/user/Documents/ODworkspace
08:22:12 - opendevin:INFO: ssh_box.py:450 - Container started
08:22:13 - opendevin:INFO: ssh_box.py:466 - waiting for container to start: 1, container status: running
08:22:13 - opendevin:INFO: ssh_box.py:199 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 58883 opendevin@host.docker.internal` with the password 'c8c36f5c-cbe8-4cbc-b62f-857ef3297740' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 58883 opendevin@localhost` with the password 'c8c36f5c-cbe8-4cbc-b62f-857ef3297740 on the host machine (where you started the container).
08:22:15 - opendevin:INFO: browser_env.py:38 - Starting browser env...
08:22:15 - opendevin:INFO: agent_controller.py:190 - Setting agent state from AgentState.LOADING to AgentState.INIT
INFO:     172.17.0.1:32950 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:32940 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     172.17.0.1:32916 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     172.17.0.1:32964 - "DELETE /api/messages HTTP/1.1" 200 OK
08:22:19 - opendevin:INFO: agent.py:112 - Creating agent MonologueAgent using LLM ollama/llama3:8b-instruct-q6_K
08:22:19 - opendevin:INFO: llm.py:111 - Initializing LLM with model: ollama/llama3:8b-instruct-q6_K
08:22:19 - opendevin:WARNING: llm.py:127 - Could not get model info for ollama/llama3:8b-instruct-q6_K
08:22:23 - opendevin:INFO: browser_env.py:51 - Browser env started.
08:22:23 - opendevin:INFO: browser_env.py:58 - SHUTDOWN recv, shutting down browser env...
08:22:23 - opendevin:INFO: agent_controller.py:190 - Setting agent state from AgentState.INIT to AgentState.STOPPED
08:22:23 - opendevin:INFO: ssh_box.py:52 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
08:22:23 - opendevin:INFO: ssh_box.py:408 - Container stopped
08:22:23 - opendevin:WARNING: ssh_box.py:420 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
08:22:23 - opendevin:INFO: ssh_box.py:429 - Mounting workspace directory: /home/user/Documents/ODworkspace
08:22:24 - opendevin:INFO: ssh_box.py:450 - Container started
08:22:25 - opendevin:INFO: ssh_box.py:466 - waiting for container to start: 1, container status: running
08:22:26 - opendevin:INFO: ssh_box.py:199 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 59823 opendevin@host.docker.internal` with the password '61235c25-9749-4989-b792-57fc17ca7514' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 59823 opendevin@localhost` with the password '61235c25-9749-4989-b792-57fc17ca7514 on the host machine (where you started the container).
08:22:27 - opendevin:INFO: browser_env.py:38 - Starting browser env...
08:22:27 - opendevin:INFO: agent_controller.py:190 - Setting agent state from AgentState.LOADING to AgentState.INIT
08:22:27 - opendevin:INFO: agent_controller.py:190 - Setting agent state from AgentState.INIT to AgentState.INIT
08:22:27 - opendevin:INFO: agent_controller.py:190 - Setting agent state from AgentState.INIT to AgentState.RUNNING


==============
STEP 0

08:22:27 - PLAN
print cwd
08:22:27 - opendevin:ERROR: agent_controller.py:147 - Error in loop
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 238, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x72ec02985760>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec02985760>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2004, in completion
    generator = ollama.get_ollama_response(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/ollama.py", line 195, in get_ollama_response
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec02985760>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 142, in _run
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 258, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/monologue_agent/agent.py", line 235, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 184, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3222, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3116, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2226, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 9233, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 9030, in exception_type
    raise ServiceUnavailableError(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/exceptions.py", line 157, in __init__
    super().__init__(
  File "/app/.venv/lib/python3.12/site-packages/openai/_exceptions.py", line 82, in __init__
    super().__init__(message, response.request, body=body)
                              ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'request'
08:22:27 - opendevin:INFO: agent_controller.py:190 - Setting agent state from AgentState.RUNNING to AgentState.ERROR
08:22:35 - opendevin:INFO: browser_env.py:51 - Browser env started.
```

**Comment by suoko** [comment]
did you follow this https://github.com/OpenDevin/OpenDevin/blob/main/docs/modules/usage/llms/localLLMs.md#fixing-it ?

**Comment by SmartManoj** [comment]
Need to set OLLAMA_ORIGINS?
https://github.com/ollama/ollama/blob/c02db93243353855b983db2a1562a02b57e66db1/docs/faq.md?plain=1#L135

**Comment by cikichen** [comment]
+1

**Comment by wmsmigiel** [comment]
> did you follow this https://github.com/OpenDevin/OpenDevin/blob/main/docs/modules/usage/llms/localLLMs.md#fixing-it ?

not before, now yes, and it gets past the issue! Thanks, I missed the solution!

although I'm jumping into new things:

```
11:12:13 - PLAN
create a python script that displays basic system information
11:12:17 - opendevin:ERROR: agent_controller.py:147 - Error in loop
Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 142, in _run
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 258, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 231, in step
    cur_cost = completion_cost(completion_response=response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4453, in completion_cost
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4439, in completion_cost
    ) = cost_per_token(
        ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4254, in cost_per_token
    raise litellm.exceptions.NotFoundError(  # type: ignore
litellm.exceptions.NotFoundError: Model not in model_prices_and_context_window.json. You passed model=ollama/llama3:8b-instruct-q6_K. Register pricing for model - https://docs.litellm.ai/docs/proxy/custom_pricing

11:12:17 - opendevin:INFO: agent_controller.py:190 - Setting agent state from AgentState.RUNNING to AgentState.ERROR

```

**Comment by wmsmigiel** [comment]
the pricing issue is here #1667
