### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by conlank** [OpenDevin/OpenDevin#1800]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I have a custom prompt set up and when trying to use openDevin I receive an error associated with the variable PS1. See log file.

### Current Version

```bash
opendevin:0.5
```

### Installation and Configuration

```bash
docker run \
    -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5

Using an openAI api key, opening web browser on laptop, docker is running on a separate host.
```

### Model and Agent

- Model: chatgpt-3.5-turbo
- CodeActAgent

### Reproduction Steps

1. set PS1 to this `
echo $PS1; 
[\e[0;32m\u\e[0m@\e[0;33m\H\e[0m: \e[0;36m\w\e[0m]\$
`
2. `mkdir worspace`
3. `export WORKSPACE_BASE=$(pwd)/workspace`
4. Start OpenDevin using the provided docker commands

### Logs, Errors, Screenshots, and Additional Context

```
Running as enduser
INFO:     Started server process [33]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     192.168.1.135:59407 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.1.135:59407 - "GET /index.html HTTP/1.1" 200 OK
INFO:     192.168.1.135:59407 - "GET /api/config/custom.css HTTP/1.1" 404 Not Found
INFO:     192.168.1.135:59408 - "GET /api/config/custom.js HTTP/1.1" 404 Not Found
INFO:     192.168.1.135:59407 - "GET /site.webmanifest HTTP/1.1" 200 OK
INFO:     192.168.1.135:59408 - "GET /assets/index-CONCUfl8.js HTTP/1.1" 200 OK
INFO:     192.168.1.135:59409 - "GET /assets/index-C1rSGIfH.css HTTP/1.1" 200 OK
01:47:00 - opendevin:ERROR: auth.py:32 - Invalid token
01:47:00 - opendevin:INFO: listen.py:88 - Invalid or missing credentials, generating new session ID: a70d1544-8055-47bc-a64f-a59a32036d2c
INFO:     192.168.1.135:59407 - "GET /api/auth HTTP/1.1" 200 OK
INFO:     ('192.168.1.135', 59410) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhNzBkMTU0NC04MDU1LTQ3YmMtYTY0Zi1hNTlhMzIwMzZkMmMifQ.e5xE-yrSjupzUJpaQel-zH55d1VbcTkluez5R7Q156o" [accepted]
Starting loop_recv for sid: a70d1544-8055-47bc-a64f-a59a32036d2c
INFO:     connection open
INFO:     192.168.1.135:59407 - "GET /locales/en/translation.json HTTP/1.1" 200 OK
INFO:     192.168.1.135:59408 - "GET /favicon-32x32.png HTTP/1.1" 200 OK
INFO:     192.168.1.135:59409 - "GET /favicon-16x16.png HTTP/1.1" 200 OK
INFO:     192.168.1.135:59411 - "GET /locales/en-US/translation.json HTTP/1.1" 404 Not Found
INFO:     192.168.1.135:59407 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     192.168.1.135:59407 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     192.168.1.135:59408 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     192.168.1.135:59412 - "GET /safari-pinned-tab.svg HTTP/1.1" 200 OK
INFO:     192.168.1.135:59407 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     192.168.1.135:59413 - "GET /safari-pinned-tab.svg HTTP/1.1" 200 OK
01:54:45 - opendevin:INFO: agent.py:112 - Creating agent RepoExplorerAgent using LLM gpt-3.5-turbo
01:54:45 - opendevin:INFO: llm.py:115 - Initializing LLM with model: gpt-3.5-turbo
01:54:45 - opendevin:INFO: ssh_box.py:51 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
01:54:45 - opendevin:INFO: ssh_box.py:407 - Container stopped
01:54:45 - opendevin:WARNING: ssh_box.py:419 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
01:54:45 - opendevin:INFO: ssh_box.py:428 - Mounting workspace directory: /home/conlan/workspace
01:55:06 - opendevin:INFO: ssh_box.py:451 - Container started
01:55:07 - opendevin:INFO: ssh_box.py:467 - waiting for container to start: 1, container status: running
01:55:07 - opendevin:INFO: ssh_box.py:198 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 46371 opendevin@host.docker.internal` with the password '8d1b0f02-75dc-445e-9aae-1f8a385e2760' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 46371 opendevin@localhost` with the password '8d1b0f02-75dc-445e-9aae-1f8a385e2760 on the host machine (where you started the container).
01:55:49 - opendevin:ERROR: agent.py:125 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 117, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 79, in __init__
    self.runtime = ServerRuntime(self.id)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 61, in __init__
    self.sandbox = create_sandbox(sid, config.sandbox_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 38, in create_sandbox
    return DockerSSHBox(sid=sid, timeout=config.sandbox_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 88, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 203, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
01:55:49 - opendevin:INFO: agent_controller.py:190 - Setting agent(RepoExplorerAgent) state from AgentState.LOADING to AgentState.INIT
01:57:50 - opendevin:ERROR: listen.py:144 - Error opening file : [Errno 21] Is a directory: '/opt/workspace_base'
INFO:     192.168.1.135:59572 - "GET /api/select-file?file= HTTP/1.1" 500 Internal Server Error
01:58:16 - opendevin:INFO: agent.py:112 - Creating agent CodeActAgent using LLM gpt-3.5-turbo
01:58:16 - opendevin:INFO: llm.py:115 - Initializing LLM with model: gpt-3.5-turbo
01:58:16 - opendevin:WARNING: stream.py:31 - Subscriber subscribed multiple times: agent_controller
01:58:16 - opendevin:INFO: ssh_box.py:51 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
01:58:16 - opendevin:INFO: ssh_box.py:407 - Container stopped
01:58:16 - opendevin:WARNING: ssh_box.py:419 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
01:58:16 - opendevin:INFO: ssh_box.py:428 - Mounting workspace directory: /home/conlan/workspace
01:58:16 - opendevin:INFO: ssh_box.py:451 - Container started
01:58:17 - opendevin:INFO: ssh_box.py:467 - waiting for container to start: 1, container status: running
01:58:17 - opendevin:INFO: ssh_box.py:198 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 57559 opendevin@host.docker.internal` with the password '4fbacef3-850f-41e0-857e-e2a6405d49c7' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 57559 opendevin@localhost` with the password '4fbacef3-850f-41e0-857e-e2a6405d49c7 on the host machine (where you started the container).
01:58:59 - opendevin:ERROR: agent.py:125 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 117, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 79, in __init__
    self.runtime = ServerRuntime(self.id)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 61, in __init__
    self.sandbox = create_sandbox(sid, config.sandbox_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 38, in create_sandbox
    return DockerSSHBox(sid=sid, timeout=config.sandbox_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 88, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 203, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
01:58:59 - opendevin:INFO: agent_controller.py:190 - Setting agent(RepoExplorerAgent) state from AgentState.INIT to AgentState.INIT


INFO:     192.168.1.135:59630 - "GET /api/refresh-files HTTP/1.1" 200 OK
02:03:58 - opendevin:INFO: agent.py:112 - Creating agent SWEAgent using LLM gpt-3.5-turbo
02:03:58 - opendevin:INFO: llm.py:115 - Initializing LLM with model: gpt-3.5-turbo
02:03:58 - opendevin:WARNING: stream.py:31 - Subscriber subscribed multiple times: agent_controller
02:03:58 - opendevin:INFO: ssh_box.py:51 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
02:03:58 - opendevin:INFO: ssh_box.py:407 - Container stopped
02:03:58 - opendevin:WARNING: ssh_box.py:419 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
02:03:58 - opendevin:INFO: ssh_box.py:428 - Mounting workspace directory: /home/conlan/workspace
02:03:58 - opendevin:INFO: ssh_box.py:451 - Container started
02:03:59 - opendevin:INFO: ssh_box.py:467 - waiting for container to start: 1, container status: running
02:03:59 - opendevin:INFO: ssh_box.py:198 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 59289 opendevin@host.docker.internal` with the password '14acf6cd-90fe-4bcf-829e-6de761e6b7a2' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 59289 opendevin@localhost` with the password '14acf6cd-90fe-4bcf-829e-6de761e6b7a2 on the host machine (where you started the container).
02:04:41 - opendevin:ERROR: agent.py:125 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 117, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 79, in __init__
    self.runtime = ServerRuntime(self.id)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 61, in __init__
    self.sandbox = create_sandbox(sid, config.sandbox_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 38, in create_sandbox
    return DockerSSHBox(sid=sid, timeout=config.sandbox_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 88, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 203, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
02:04:41 - opendevin:INFO: agent_controller.py:190 - Setting agent(RepoExplorerAgent) state from AgentState.INIT to AgentState.INIT
02:04:41 - opendevin:INFO: session.py:40 - WebSocket disconnected, sid: a70d1544-8055-47bc-a64f-a59a32036d2c
INFO:     connection closed
INFO:     192.168.1.135:59688 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.1.135:59688 - "GET /index.html HTTP/1.1" 200 OK
INFO:     ('192.168.1.135', 59689) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhNzBkMTU0NC04MDU1LTQ3YmMtYTY0Zi1hNTlhMzIwMzZkMmMifQ.e5xE-yrSjupzUJpaQel-zH55d1VbcTkluez5R7Q156o" [accepted]
Starting loop_recv for sid: a70d1544-8055-47bc-a64f-a59a32036d2c
INFO:     connection open
INFO:     192.168.1.135:59690 - "GET /apple-touch-icon.png HTTP/1.1" 200 OK
INFO:     192.168.1.135:59688 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     192.168.1.135:59688 - "GET /api/litellm-models HTTP/1.1" 200 OK
02:07:58 - opendevin:INFO: agent.py:112 - Creating agent SWEAgent using LLM gpt-3.5-turbo
02:07:58 - opendevin:INFO: llm.py:115 - Initializing LLM with model: gpt-3.5-turbo
02:07:58 - opendevin:WARNING: stream.py:31 - Subscriber subscribed multiple times: agent_controller
02:07:58 - opendevin:INFO: ssh_box.py:51 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
02:07:58 - opendevin:INFO: ssh_box.py:407 - Container stopped
02:07:58 - opendevin:WARNING: ssh_box.py:419 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
02:07:58 - opendevin:INFO: ssh_box.py:428 - Mounting workspace directory: /home/conlan/workspace
02:07:59 - opendevin:INFO: ssh_box.py:451 - Container started
02:08:00 - opendevin:INFO: ssh_box.py:467 - waiting for container to start: 1, container status: running
02:08:00 - opendevin:INFO: ssh_box.py:198 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 53997 opendevin@host.docker.internal` with the password 'c16b6bb4-814c-409c-bfa9-601458deea05' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 53997 opendevin@localhost` with the password 'c16b6bb4-814c-409c-bfa9-601458deea05 on the host machine (where you started the container).
02:08:41 - opendevin:ERROR: agent.py:125 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 117, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 79, in __init__
    self.runtime = ServerRuntime(self.id)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 61, in __init__
    self.sandbox = create_sandbox(sid, config.sandbox_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 38, in create_sandbox
    return DockerSSHBox(sid=sid, timeout=config.sandbox_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 88, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 203, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
02:08:41 - opendevin:INFO: agent_controller.py:190 - Setting agent(RepoExplorerAgent) state from AgentState.INIT to AgentState.INIT
INFO:     192.168.1.135:59688 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     192.168.1.135:59691 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     192.168.1.135:59693 - "DELETE /api/messages HTTP/1.1" 200 OK
02:08:46 - opendevin:INFO: msg_stack.py:95 - Deleting messages...
02:09:41 - opendevin:INFO: agent.py:112 - Creating agent CodeActAgent using LLM gpt-3.5-turbo
02:09:41 - opendevin:INFO: llm.py:115 - Initializing LLM with model: gpt-3.5-turbo
02:09:41 - opendevin:WARNING: stream.py:31 - Subscriber subscribed multiple times: agent_controller
02:09:41 - opendevin:INFO: ssh_box.py:51 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
02:09:41 - opendevin:INFO: ssh_box.py:407 - Container stopped
02:09:41 - opendevin:WARNING: ssh_box.py:419 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
02:09:41 - opendevin:INFO: ssh_box.py:428 - Mounting workspace directory: /home/conlan/workspace
02:09:41 - opendevin:INFO: ssh_box.py:451 - Container started
02:09:42 - opendevin:INFO: ssh_box.py:467 - waiting for container to start: 1, container status: running
02:09:43 - opendevin:INFO: ssh_box.py:198 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 50527 opendevin@host.docker.internal` with the password 'fdcb4ca7-cfe1-4acb-82ff-12dbc2cded76' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 50527 opendevin@localhost` with the password 'fdcb4ca7-cfe1-4acb-82ff-12dbc2cded76 on the host machine (where you started the container).
02:10:24 - opendevin:ERROR: agent.py:125 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 117, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 79, in __init__
    self.runtime = ServerRuntime(self.id)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 61, in __init__
    self.sandbox = create_sandbox(sid, config.sandbox_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 38, in create_sandbox
    return DockerSSHBox(sid=sid, timeout=config.sandbox_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 88, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 203, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
02:10:24 - opendevin:INFO: agent_controller.py:190 - Setting agent(RepoExplorerAgent) state from AgentState.INIT to AgentState.INIT
02:15:05 - opendevin:INFO: session.py:40 - WebSocket disconnected, sid: a70d1544-8055-47bc-a64f-a59a32036d2c
INFO:     connection closed
```

**Comment by SmartManoj** [comment]
Step 1 for?

**Comment by rbren** [comment]
@conlank please see the troubleshooting guide from the bug template
