### ISSUE TITLE
[Bug]: AttributeError: 'dict' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by unclemusclez** [OpenDevin/OpenDevin#1809]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Refresh browser:
```
12:03:56 - opendevin:INFO: agent_controller.py:190 - Setting agent(CodeActAgent) state from AgentState.LOADING to AgentState.INIT
INFO:     127.0.0.1:48692 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:48694 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:48712 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:48698 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:49178 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:49192 - "GET /api/agents HTTP/1.1" 200 OK
```
Prompted with: https://i.imgur.com/H7kaWFe.png
```
Unfinished Session Detected

You seem to have an unfinished task. Would you like to pick up where you left off or start fresh?
```

Select "Start New Session":
```
INFO:     127.0.0.1:43238 - "DELETE /api/messages HTTP/1.1" 200 OK
12:06:24 - opendevin:INFO: msg_stack.py:95 - Deleting messages...
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-32' coro=<MessageStack._del_messages() done, defined at /mnt/p/opendevin/opendevin/server/session/msg_stack.py:94> exception=AttributeError("'dict' object has no attribute 'to_dict'")>
Traceback (most recent call last):
  File "/mnt/p/opendevin/opendevin/server/session/msg_stack.py", line 102, in _del_messages
    new_data[sid] = [msg.to_dict() for msg in msgs]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/p/opendevin/opendevin/server/session/msg_stack.py", line 102, in <listcomp>
    new_data[sid] = [msg.to_dict() for msg in msgs]
                     ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_dict'
```
https://i.imgur.com/Zy8jWRV.png

### Current Version

```bash
0.5.3
```

### Installation and Configuration

```bash
`make run`
```

### Model and Agent

ALL

### Reproduction Steps

listed above

**Comment by SmartManoj** [comment]
Check in incognito mode

**Comment by unclemusclez** [comment]
That seemed to have worked.
I am running Firefox 125.0.3 (64-bit)

**Comment by unclemusclez** [comment]
I received the same error again when refreshing the same private browser window and restarting OpenDevin with `make run`
