### ISSUE TITLE
[Bug]: Exception when deleting messages

### ISSUE THREAD

**Issue by frankxu2004** [OpenDevin/OpenDevin#1851]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Randomly if the session restarts or disconnects, delete_messages will be called and  the following appears in the logs:

```
INFO:     127.0.0.1:36072 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:36086 - "DELETE /api/messages HTTP/1.1" 200 OK
13:19:45 - opendevin:INFO: msg_stack.py:95 - Deleting messages...
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-18' coro=<MessageStack._del_messages() done, defined at /projects/ogma3/fangzhex/OpenDevin/opendevin/server/session/msg_stack.py:94> exception=TypeError('Object of type Message is not JSON serializable')>
Traceback (most recent call last):
  File "/projects/ogma3/fangzhex/OpenDevin/opendevin/server/session/msg_stack.py", line 107, in _del_messages
    json.dump(new_data, file)
  File "/home/fangzhex/miniconda3/lib/python3.11/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/fangzhex/miniconda3/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/fangzhex/miniconda3/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/home/fangzhex/miniconda3/lib/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/home/fangzhex/miniconda3/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/fangzhex/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Message is not JSON serializable
```

### Current Version

```bash
main branch
```

### Installation and Configuration

```bash
make run
```

**Comment by neubig** [comment]
Fixed by #1871
