### ISSUE TITLE
[Bug]: SWE-Bench Eval does not work

### ISSUE THREAD

**Issue by ramsey-coding** [OpenDevin/OpenDevin#2150]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I get the following error when I run the `./evaluation/swe_bench/scripts/run_infer.sh [model_config] [agent] [eval_limit]` script

```
Traceback (most recent call last):
  File "/Users/ramsey/conda/anaconda3/envs/opendevin/lib/python3.11/concurrent/futures/process.py", line 308, in weakref_cb
AttributeError: 'NoneType' object has no attribute 'util'
```

### Current OpenDevin version

```bash
latest
```

### Installation and Configuration

```bash
./evaluation/swe_bench/scripts/run_infer.sh eval_bedrock CodeActAgent 5
```

### Model and Agent

CodeAct agent

### Operating System

Mac

### Reproduction Steps

Run the `./evaluation/swe_bench/scripts/run_infer.sh` script

**Comment by SmartManoj** [comment]
Could you provide the full traceback?

**Comment by li-boxuan** [comment]
Could you please check out https://github.com/OpenDevin/OpenDevin/blob/main/evaluation/swe_bench/README.md#test-if-your-environment-works?

I am pretty sure your config is wrong.

**Comment by SmartManoj** [comment]
> AssertionError: Failed to backup ~/.bashrc: mv: cannot stat '/home/opendevin/.bashrc': No such file or directory

**Comment by ramsey-coding** [comment]
@li-boxuan @SmartManoj I get this error:

```
❯ poetry run python evaluation/swe_bench/swe_env_box.py

19:40:23 - opendevin:INFO: ssh_box.py:208 - SSHBox is running as opendevin user with USER_ID=501 in the sandbox
19:40:23 - opendevin:INFO: ssh_box.py:642 - Container stopped
19:40:23 - opendevin:WARNING: ssh_box.py:654 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
19:40:23 - opendevin:INFO: ssh_box.py:627 - Mounting workspace directory: None
19:40:23 - opendevin:INFO: ssh_box.py:663 - Mounting volumes: {'/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
19:40:23 - opendevin:INFO: ssh_box.py:627 - Mounting workspace directory: None
19:40:23 - opendevin:INFO: ssh_box.py:674 - Container started
19:40:24 - opendevin:INFO: ssh_box.py:690 - waiting for container to start: 1, container status: running
19:40:25 - opendevin:INFO: ssh_box.py:377 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 50766 opendevin@localhost` with the password '4853f2ee-caaa-4ed5-8de3-9abb8a963eec' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 50766 opendevin@localhost` with the password '4853f2ee-caaa-4ed5-8de3-9abb8a963eec on the host machine (where you started the container).
ERROR:root:  File "/Users/ramsey/repos/OpenDevin/evaluation/swe_bench/swe_env_box.py", line 141, in <module>
    sandbox = SWEBenchSSHBox.get_box_for_instance(instance=EXAMPLE_INSTANCE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ramsey/repos/OpenDevin/evaluation/swe_bench/swe_env_box.py", line 80, in get_box_for_instance
    sandbox = cls(
              ^^^^
  File "/Users/ramsey/repos/OpenDevin/evaluation/swe_bench/swe_env_box.py", line 36, in __init__
    assert exit_code == 0, f'Failed to backup ~/.bashrc: {output}'
           ^^^^^^^^^^^^^^

ERROR:root:<class 'AssertionError'>: Failed to backup ~/.bashrc: mv: cannot stat '/home/opendevin/.bashrc': No such file or directory
```

**Comment by li-boxuan** [comment]
> Could you please check out https://github.com/OpenDevin/OpenDevin/blob/main/evaluation/swe_bench/README.md#test-if-your-environment-works?
> 
> I am pretty sure your config is wrong.

You need to set run_as_devin = false in config.toml

**Comment by ramsey-coding** [comment]
My config is:

```
[core]
max_iterations = 100
cache_dir = "/tmp/cache"
sandbox_container_image = "ghcr.io/opendevin/sandbox:latest"
sandbox_type = "ssh"
ssh_hostname = "localhost"
sandbox_timeout = 120

# SWEBench eval specific
use_host_network = false
run_as_devin = false
enable_auto_lint = true

[eval_mistral]
model = "bedrock/mistral.mistral-7b-instruct-v0:2"
temperature = 0.0

selected_ids = ['sphinx-doc__sphinx-8721', 'sympy__sympy-14774', 'scikit-learn__scikit-learn-10508']

AWS_ACCESS_KEY_ID = "......."
AWS_SECRET_ACCESS_KEY = "......."
AWS_REGION_NAME = "us-west-2"
```

**Comment by SmartManoj** [comment]
Is this config loaded? any error about the config in the log?

**Comment by ramsey-coding** [comment]
this is the complete log:

```
❯ poetry run python evaluation/swe_bench/swe_env_box.py

19:46:22 - opendevin:INFO: ssh_box.py:208 - SSHBox is running as opendevin user with USER_ID=501 in the sandbox
19:46:22 - opendevin:INFO: ssh_box.py:642 - Container stopped
19:46:22 - opendevin:WARNING: ssh_box.py:654 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
19:46:22 - opendevin:INFO: ssh_box.py:627 - Mounting workspace directory: None
19:46:22 - opendevin:INFO: ssh_box.py:663 - Mounting volumes: {'/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
19:46:22 - opendevin:INFO: ssh_box.py:627 - Mounting workspace directory: None
19:46:22 - opendevin:INFO: ssh_box.py:674 - Container started
19:46:23 - opendevin:INFO: ssh_box.py:690 - waiting for container to start: 1, container status: running
19:46:24 - opendevin:INFO: ssh_box.py:377 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 50894 opendevin@localhost` with the password '....' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 50894 opendevin@localhost` with the password '.... on the host machine (where you started the container).
ERROR:root:  File "/Users/ramsey/repos/OpenDevin/evaluation/swe_bench/swe_env_box.py", line 141, in <module>
    sandbox = SWEBenchSSHBox.get_box_for_instance(instance=EXAMPLE_INSTANCE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ramsey/repos/OpenDevin/evaluation/swe_bench/swe_env_box.py", line 80, in get_box_for_instance
    sandbox = cls(
              ^^^^
  File "/Users/ramsey/repos/OpenDevin/evaluation/swe_bench/swe_env_box.py", line 36, in __init__
    assert exit_code == 0, f'Failed to backup ~/.bashrc: {output}'
           ^^^^^^^^^^^^^^

ERROR:root:<class 'AssertionError'>: Failed to backup ~/.bashrc: mv: cannot stat '/home/opendevin/.bashrc': No such file or directory
```

**Comment by SmartManoj** [comment]
Do you have only one config file?

**Comment by ramsey-coding** [comment]
yes - I have already pasted the config file.

**Comment by SmartManoj** [comment]
`export RUN_AS_DEVIN=false` and check

**Comment by li-boxuan** [comment]
> selected_ids = ['sphinx-doc__sphinx-8721', 'sympy__sympy-14774', 'scikit-learn__scikit-learn-10508']

Btw that one doesn't go to `config.toml` in the root folder. It goes to swe-bench folder.

**Comment by ramsey-coding** [comment]
after setting `export RUN_AS_DEVIN=false` I now get:


```
Ran 22 tests in 0.129s

OK
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
20:02:54 - opendevin:INFO: swe_env_box.py:178 - git reset --hard: HEAD is now at d26b242443 Fixed #30271 -- Added the Sign database function.
>>>
```


So looks like it is setup correctly?



I now get:

```
ERROR:root:<class 'opendevin.runtime.browser.browser_env.BrowserException'>: Failed to start browser environment.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:33<00:00, 33.10s/it]
Exception ignored in: <function _ExecutorManagerThread.__init__.<locals>.weakref_cb at 0x179e34c20>
Traceback (most recent call last):
  File "/Users/ramsey/conda/anaconda3/envs/opendevin/lib/python3.11/concurrent/futures/process.py", line 308, in weakref_cb
AttributeError: 'NoneType' object has no attribute 'util'
```

**Comment by SmartManoj** [comment]
u don't have playwright?

**Comment by ramsey-coding** [comment]
Did the setup, still get the following error:


```
Traceback (most recent call last):
  File "/Users/ramsey/conda/anaconda3/envs/opendevin/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/Users/ramsey/repos/OpenDevin/evaluation/swe_bench/run_infer.py", line 414, in update_progress
    output = future.result()
             ^^^^^^^^^^^^^^^
  File "/Users/ramsey/conda/anaconda3/envs/opendevin/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ramsey/conda/anaconda3/envs/opendevin/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/ramsey/repos/OpenDevin/evaluation/swe_bench/run_infer.py", line 450, in <module>
    future.result()
  File "/Users/ramsey/conda/anaconda3/envs/opendevin/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ramsey/conda/anaconda3/envs/opendevin/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
opendevin.runtime.browser.browser_env.BrowserException: Failed to start browser environment.
20:18:18 - opendevin:INFO: browser_env.py:53 - Browser env started.
```

**Comment by SmartManoj** [comment]
https://github.com/OpenDevin/OpenDevin/pull/1993#issuecomment-2128485114

**Comment by ramsey-coding** [comment]
@SmartManoj slightly different question, during SWE bench evaluation I dont want to the agent to browser the internet though.

**Comment by SmartManoj** [comment]
#2105

**Comment by ramsey-coding** [comment]
> > selected_ids = ['sphinx-doc__sphinx-8721', 'sympy__sympy-14774', 'scikit-learn__scikit-learn-10508']
> 
> Btw that one doesn't go to `config.toml` in the root folder. It goes to swe-bench folder.

where to set it then? Which config file?

**Comment by li-boxuan** [comment]
> > > selected_ids = ['sphinx-doc__sphinx-8721', 'sympy__sympy-14774', 'scikit-learn__scikit-learn-10508']
> > 
> > 
> > Btw that one doesn't go to `config.toml` in the root folder. It goes to swe-bench folder.
> 
> where to set it then? Which config file?

https://github.com/OpenDevin/OpenDevin/blob/main/evaluation/swe_bench/README.md

**Comment by ramsey-coding** [comment]
So there are two `config.toml`, one in the root folder and one in the `./evaluation/swe_bench/` folder.

- I need to create then second `config.toml` in `./evaluation/swe_bench/` folder with only the following content:

```
selected_ids = ['sphinx-doc__sphinx-8721', 'sympy__sympy-14774', 'scikit-learn__scikit-learn-10508']
```

**Comment by SmartManoj** [comment]
@li-boxuan  `sub_config.toml` would be better?

**Comment by li-boxuan** [comment]
> @li-boxuan `sub_config.toml` name would be better?

Eventually we will refactor the whole `evaluation` folder.

**Comment by mamoodi** [comment]
@li-boxuan can this issue be closed? Seems like it was a config issue?
