### ISSUE TITLE
[Bug]: "docker run" sample command in README raises exception (with container "main") when running as root.

### ISSUE THREAD

**Issue by tobitege** [OpenDevin/OpenDevin#2200]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

1) The "docker" command in the main README, section Getting started, is not working out of the box, at least when I tried `ghcr.io/opendevin/opendevin:main` is used instead of `ghcr.io/opendevin/opendevin:0.5` at the end.

It will run into this exception:
```sh
Exception: Persistent sandbox is currently designed for opendevin user only. Please set run_as_devin=True in your config.toml
```
It only works when I use `-e PERSIST_SANDBOX="false"` instead of `-e PERSIST_SANDBOX="true"`!

2) Running in WSL on Windows 11 with Docker for Windows running.
With above persist flag set to false, it does start up fine in WSL and I can open OD in browser and I get the agent's "Hello" message without error.
However, within Docker, there are 2 docker containers created and running, example:
![grafik](https://github.com/OpenDevin/OpenDevin/assets/10787084/9b386b20-9536-4364-991d-c30efe29e434)

If now the browser session as well as OD in terminal are shut down, the first docker container remains ("romantic_mayer" in this case). 
Is this supposed to happen this way with every session?

### Current OpenDevin version

```bash
Main as of today.
```

### Installation and Configuration

```bash
The 2 commands from the Getting started section as 2 separate, single lines:

export WORKSPACE_BASE=$(pwd)/workspace;

docker run -it     --pull=always     -e SANDBOX_USER_ID=$(id -u)     -e PERSIST_SANDBOX="false"     -e SSH_PASSWORD="mypassword"     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal:host-gateway     ghcr.io/opendevin/opendevin:main
```

### Operating System

WSL on Windows 11 Pro

**Comment by tobitege** [comment]
Hey @SmartManoj,
gladly I still have the console open. Here's the log of it:
```sh
Starting OpenDevin...
Running OpenDevin as root
INFO:     Started server process [10]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     172.17.0.1:60090 - "GET / HTTP/1.1" 200 OK
INFO:     172.17.0.1:60090 - "GET /assets/index-XgmWGMQR.js HTTP/1.1" 200 OK
INFO:     172.17.0.1:60104 - "GET /assets/index-XLRq1aJ1.css HTTP/1.1" 200 OK
INFO:     172.17.0.1:60090 - "GET /locales/en/translation.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:60090 - "GET /apple-touch-icon.png HTTP/1.1" 200 OK
INFO:     172.17.0.1:60104 - "GET /favicon-32x32.png HTTP/1.1" 200 OK
INFO:     172.17.0.1:60090 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     172.17.0.1:60090 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     ('172.17.0.1', 35824) - "WebSocket /ws" [accepted]
INFO:     connection open
08:26:54 - opendevin:INFO: agent.py:64 - Using server runtime
08:26:54 - opendevin:INFO: ssh_box.py:206 - SSHBox is running as root user with USER_ID=0 in the sandbox
08:26:54 - opendevin:ERROR: session.py:69 - Error creating controller: Persistent sandbox is currently designed for opendevin user only. Please set run_as_devin=True in your config.toml
Traceback (most recent call last):
  File "/app/opendevin/server/session/session.py", line 67, in _initialize_agent
    await self.agent_session.start(data)
  File "/app/opendevin/server/session/agent.py", line 46, in start
    await self._create_runtime()
  File "/app/opendevin/server/session/agent.py", line 65, in _create_runtime
    self.runtime = ServerRuntime(self.event_stream, self.sid)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/server/runtime.py", line 35, in __init__
    super().__init__(event_stream, sid, sandbox)
  File "/app/opendevin/runtime/runtime.py", line 72, in __init__
    self.sandbox = create_sandbox(sid, config.sandbox_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 46, in create_sandbox
    return DockerSSHBox(sid=sid)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 221, in __init__
    raise Exception(
Exception: Persistent sandbox is currently designed for opendevin user only. Please set run_as_devin=True in your config.toml
```

**Comment by SmartManoj** [comment]
> ```shell
> Running OpenDevin as root
> ```

How did you run?

**Comment by tobitege** [comment]
as root in WSL with this:
```sh
 docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e PERSIST_SANDBOX="true" \
    -e SSH_PASSWORD="mypassword" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:main
```

**Comment by SmartManoj** [comment]
> as root in WSL with this:

Why?

**Comment by tobitege** [comment]
It is the default behavior and user of my WSL, I don't use WSL normally. :)

**Comment by tobitege** [comment]
If you meant why I used "main": I wanted to try the current version.

**Comment by SmartManoj** [comment]
> It is the default behavior

Nope. Please [change it](https://www.tenforums.com/tutorials/128152-set-default-user-windows-subsystem-linux-distro-windows-10-a.html#option2) if you want persistent sandbox.

**Comment by tobitege** [comment]
I can do. But that's the point of this issue: if this is required, this is not mentioned in the docs unless I must have overlooked it. And the Getting started section and the Windows troubleshooting section don't mention it.

**Comment by SmartManoj** [comment]
> if this is required,

[Why is it bad to log in as root?](https://askubuntu.com/q/16178)

**Comment by tobitege** [comment]
Ok, I switched my default WSL user to "tobias" and created a workspace folder and ran the 2 commands again:
```sh
tobias@CD137K:~$ mkdir workspace
tobias@CD137K:~$ export WORKSPACE_BASE=$(pwd)/workspace;
tobias@CD137K:~$ docker run -it     --pull=always     -e SANDBOX_USER_ID=$(id -u)     -e PERSIST_SANDBOX="true"     -e S
SH_PASSWORD="mypassword"     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal:host-gateway     ghcr.io/opendevin/opendevin:main
main: Pulling from opendevin/opendevin
Digest: sha256:aa80914c3428637d1c998d67eb8e63a582c4b876c108051f4e5b2836358dc1a0
Status: Image is up to date for ghcr.io/opendevin/opendevin:main
Starting OpenDevin...
Setting up enduser with id 1000
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_index_client/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
There was a problem when trying to write in your cache folder (/home/enduser/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
INFO:     Started server process [35]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
```
Now I'm wondering why it says "python3.12" in above message, isn't OD all 3.11?

**Comment by SmartManoj** [comment]
> isn't OD all 3.11?

No.

**Comment by SmartManoj** [comment]
Known issue in WSL with docker https://github.com/OpenDevin/OpenDevin/issues/1366
