### ISSUE TITLE
Starting backend fastapi is not found

### ISSUE THREAD

**Issue by guyko81** [OpenDevin/OpenDevin#222]
sudo uvicorn opendevin.server.listen:app --port 3000
Traceback (most recent call last):
  File "/usr/bin/uvicorn", line 33, in <module>
    sys.exit(load_entry_point('uvicorn==0.15.0', 'console_scripts', 'uvicorn')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uvicorn/main.py", line 425, in main
    run(app, **kwargs)
  File "/usr/lib/python3/dist-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/lib/python3/dist-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/usr/lib/python3/dist-packages/uvicorn/config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/lib/python3/dist-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/lib/python3/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/OpenDevin/./opendevin/server/listen.py", line 1, in <module>
    from opendevin.server.session import Session
  File "/home/ubuntu/OpenDevin/./opendevin/server/session.py", line 5, in <module>
    from fastapi import WebSocketDisconnect
ModuleNotFoundError: No module named 'fastapi'

**Comment by rbren** [comment]
Did you run
```
```

**Comment by rbren** [comment]
Could be that you're running as `sudo`

**Comment by guyko81** [comment]
done both - probably something stupid, but can't figure out. I expected there will be some venv, making sure the packages are available. When just running python3, I can import fastapi. I added alias python to python3 too.

**Comment by rbren** [comment]
Googling around it seems like a very common problem with fastapi ☹️

**Comment by yufansong** [comment]
Maybe you can check `which python` or `which python3` in cmd to see the location of your interpreter. And then check whether fastapi locate in the corresponding bin directory.

**Comment by rbren** [comment]
This seems like not an OpenDevin problem, but more an issue with the host environment. I'm going to close this but @guyko81 let me know if you make any progress, or have some more info we could use to help you debug
