### ISSUE TITLE
using azure end point .. causes problems .. 

### ISSUE THREAD

**Issue by ack72tdp** [OpenDevin/OpenDevin#224]
**Describe the bug**
Can't connect through Azure Endpoint ... litellm connects fine with same azure end point separately outside this code ..... If I use openai endpoint with this code it works fine too .. 

Here  is the litellm libraries code is modified to support http_client   .. I have to use httpx_client in the completion like this to make it work .. 

httpx_client = httpx.Client(verify=False)

# azure call
response = completion(
    model = "azure/test-gpt-4-turbo",
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    http_client = httpx_client,
)
print (response)

Here is the call stack ..

INFO:     Started server process [14332]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 59171) - "WebSocket /ws" [accepted]
INFO:     connection open

==============
STEP 0
Retrying llama_index.embeddings.openai.base.get_embeddings in 0.10087867512617688 seconds as it raised APIConnectionError: Connection error..

        AGENT ERROR:
        Connection error.
Traceback (most recent call last):
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpcore\_sync\connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 926, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\OpenDevin\opendevin\controller\__init__.py", line 85, in step
    action = self.agent.step(state)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\agenthub\langchains_agent\__init__.py", line 123, in step
    self._initialize()
  File "C:\OpenDevin\agenthub\langchains_agent\__init__.py", line 119, in _initialize
    self._add_event(d)
  File "C:\OpenDevin\agenthub\langchains_agent\__init__.py", line 82, in _add_event
    self.memory.add_event(event)
  File "C:\OpenDevin\agenthub\langchains_agent\utils\memory.py", line 28, in add_event
    self.index.insert(doc)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\indices\base.py", line 242, in insert
    self.insert_nodes(nodes, **insert_kwargs)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\indices\vector_store\base.py", line 329, in insert_nodes
    self._insert(nodes, **insert_kwargs)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\indices\vector_store\base.py", line 312, in _insert
    self._add_nodes_to_index(self._index_struct, nodes, **insert_kwargs)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\indices\vector_store\base.py", line 233, in _add_nodes_to_index
    nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\indices\vector_store\base.py", line 141, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
                      ^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\indices\utils.py", line 138, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 102, in wrapper
    self.span_drop(*args, id=id, err=e, **kwargs)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 77, in span_drop
    h.span_drop(*args, id=id, err=err, **kwargs)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\instrumentation\span_handlers\base.py", line 47, in span_drop
    self.prepare_to_drop_span(*args, id=id, err=err, **kwargs)
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\instrumentation\span_handlers\null.py", line 35, in prepare_to_drop_span
    raise err
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 100, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\core\base\embeddings\base.py", line 280, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\embeddings\openai\base.py", line 427, in _get_text_embeddings
    return get_embeddings(
           ^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\OpenDevin\opendevinci\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\llama_index\embeddings\openai\base.py", line 180, in get_embeddings
    data = client.embeddings.create(input=list_of_text, model=engine, **kwargs).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\resources\embeddings.py", line 113, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 897, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\OpenDevin\opendevinci\Lib\site-packages\openai\_base_client.py", line 960, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

        OBSERVATION:
        Connection error.

==============
STEP 1

Any thoughts? Thanks in advance...

**Steps to Reproduce**
1.
2.
3.

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by ack72tdp** [comment]
BTW, I also set

LLM_API_BASE, LLM_API_KEY, LLM_MODEL, AZURE_API_BASE, AZURE_API_VERSION .. both base is set same ..

**Comment by rbren** [comment]
@ack72tdp my guess is this is an issue with LiteLLM. Are you able to get a basic example working with their client? 

https://litellm.vercel.app/docs/

**Comment by ack72tdp** [comment]
Yes it works fine .. with this basic example  like below ..

from litellm import completion
import httpx
import os

## set ENV variables
os.environ["AZURE_API_KEY"] = ""
os.environ["AZURE_API_BASE"] = ""
os.environ["AZURE_API_VERSION"] = ""

httpx_client = httpx.Client(verify=False)

# azure call
response = completion(
    model = "azure/test-gpt-4-turbo",
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    http_client = httpx_client,
)

print (response)

**Comment by RohitX0X** [comment]
I am also getting same issue: I dont want to use OPEN AI but instead Azure open ai , did all the steps mentioned above

Retrying llama_index.embeddings.openai.base.get_embeddings in 0.977972932183363 seconds as it raised AuthenticationError: Error code: 401 - {'error': {'messag': 'Incorrect API key provided: 51*************************84dd. You can find our API key at https://platform.openai.com/account/api-keys.', 'type': 'invalidrequest_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by guii** [comment]
Hello,
I had the same problem. I had to change the embedding in agenthub/langchains_agent/utils/memory.py
from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding
...
class LongTermMemory:
    def __init__(self):
        db = chromadb.Client()
        embed_model = AzureOpenAIEmbedding(model="text-embedding-ada-002", deployment_name="text-embedding-ada-002", api_key="...", azure_endpoint='https://....',api_version='....',)
        self.collection = db.get_or_create_collection(name="memories")
        vector_store = ChromaVectorStore(chroma_collection=self.collection)
        self.index = VectorStoreIndex.from_vector_store(vector_store, embed_model=embed_model)
...
