### ISSUE TITLE
FileNotFoundError 

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#248]
OpenDevin % export LLM_MODEL="gpt-3.5-turbo-1106"
OpenDevin % export OPENAI_API_KEY=sk.....
OpenDevin % export LLM_API_KEY="sk...

OpenDevin % uvicorn opendevin.server.listen:app --port 3000
```
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jwang/Documents/workspace/OpenDevin/venv/lib/python3.11/site-packages/docker/api/client.py", line 213, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwang/Documents/workspace/OpenDevin/venv/lib/python3.11/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/Users/jwang/Documents/workspace/OpenDevin/venv/lib/python3.11/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwang/Documents/workspace/OpenDevin/venv/lib/python3.11/site-packages/docker/api/client.py", line 236, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwang/Documents/workspace/OpenDevin/venv/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwang/Documents/workspace/OpenDevin/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwang/Documents/workspace/OpenDevin/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwang/Documents/workspace/OpenDevin/venv/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:
```

**Comment by josephykwang** [comment]
http://127.0.0.1:3000/
see 

```
{
  "detail": "Not Found"
}
```

I'm running on Mac

**Comment by rbren** [comment]
@josephykwang it seems like a docker issue. Do you have docker running? What does `docker ps` show?

**Comment by josephykwang** [comment]
```docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED       STATUS          PORTS                                              NAMES

97d63b4deeb4   nginx:1.23.4-alpine                 "/docker-entrypoint.…"   11 days ago   Up 57 minutes   0.0.0.0:80->80/tcp, 0.0.0.0:3000->80/tcp           danswer-stack-nginx-1

3a1ea538424e   danswer/danswer-web-server:latest   "docker-entrypoint.s…"   11 days ago   Up 57 minutes                                                      danswer-stack-web_server-1

39b92e69a327   danswer/danswer-backend:latest      "/bin/sh -c 'alembic…"   11 days ago   Up 57 minutes   0.0.0.0:8080->8080/tcp                             danswer-stack-api_server-1

2e81ce497d6d   danswer/danswer-backend:latest      "/usr/bin/supervisord"   11 days ago   Up 57 minutes                                                      danswer-stack-background-1

ab543410c908   vespaengine/vespa:8.277.17          "/usr/local/bin/star…"   11 days ago   Up 57 minutes   0.0.0.0:8081->8081/tcp, 0.0.0.0:19071->19071/tcp   danswer-stack-index-1
262f938ff141   postgres:15.2-alpine                "docker-entrypoint.s…"   11 days ago   Up 57 minutes   0.0.0.0:5432->5432/tcp                             danswer-stack-relational_db-1```
BTW, there is no dockerrun cmd in the readme.    On Wednesday, March 27, 2024 at 08:10:31 AM PDT, Robert Brennan ***@***.***> wrote:  
 
 


@josephykwang it seems like a docker issue. Do you have docker running? What does docker ps show?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by rbren** [comment]
does `docker pull ghcr.io/opendevin/sandbox:v0.1` fix the issue?

**Comment by josephykwang** [comment]
still the same problem.

**Comment by rbren** [comment]
Looked around a bit. I found this tip:

> Under advanced settings check the case “Allow the default Docker socket to be used (requires password)”.

[This issue](https://github.com/docker/compose/issues/7896) suggests it's docker not running

And [this one](https://github.com/openai/universe/issues/52) suggests maybe you have docker set up so that it needs `sudo`, and has instructions on fixing.

**Comment by OSH212** [comment]
running into the same issue (on mac as well). you guys found a solution?

**Comment by iFurySt** [comment]
It seems same as #278

**Comment by haseeb-heaven** [comment]
> running into the same issue (on mac as well). you guys found a solution?

I finally solved it by updating my Docker host path like this.
```bash
export DOCKER_HOST=unix:///Users/haseeb-mir/.docker/run/docker.sock
```

**Comment by rbren** [comment]
we've at least got better error messages in place now. I suspect the docker connection issues are going to be a theme for us
