### ISSUE TITLE
[Bug]: 'There was an unexpected error while running the agent'

### ISSUE THREAD

**Issue by scottsantinho** [OpenDevin/OpenDevin#2801]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

![CleanShot 2024-07-04 at 22 54 11@2x](https://github.com/OpenDevin/OpenDevin/assets/153218115/7745e127-5abc-46dc-adca-6f1c60875afb)

Hello,

After setting up OpenDevin Docker and the Claude API Key, I run into this error when prompting OpenDevin.

Could you help me fix it ?

Thanks in advance :)

### Current OpenDevin version

```bash
0.7
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.7
```

### Model and Agent

- Model: Claude 3.5 Sonnet
- Agent : CodeActAgent

### Operating System

MacOS Sonoma

### Logs, Errors, Screenshots, and Additional Context

```
Last login: [DATE] on ttys000
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-[TIMESTAMP] \
    ghcr.io/opendevin/opendevin:0.7%                                            
(base) [USERNAME]@[HOSTNAME] ~ % WORKSPACE_BASE=$(pwd)/workspace
(base) [USERNAME]@[HOSTNAME] ~ % docker run -it \
>     --pull=always \
>     -e SANDBOX_USER_ID=$(id -u) \
>     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
>     -v $WORKSPACE_BASE:/opt/workspace_base \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     -p 3000:3000 \
>     --add-host host.docker.internal:host-gateway \
>     --name opendevin-app-[TIMESTAMP] \
>     ghcr.io/opendevin/opendevin:0.7
0.7: Pulling from opendevin/opendevin
Digest: sha256:[DIGEST]
Status: Image is up to date for ghcr.io/opendevin/opendevin:0.7
Starting OpenDevin...
Setting up enduser with id [USER_ID]
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_index_client/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
[TIMESTAMP] - opendevin:INFO: listen.py:100 - File upload config: max_size=0MB, restrict_types=False, allowed_extensions=['.*']
INFO:     Started server process [PID]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     [IP_ADDRESS]:53588 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     [IP_ADDRESS]:53588 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     ('[IP_ADDRESS]', [PORT]) - "WebSocket /ws?token=[TOKEN]" [accepted]
[TIMESTAMP] - opendevin:ERROR: auth.py:29 - Invalid token
INFO:     connection open
INFO:     connection closed
INFO:     ('[IP_ADDRESS]', [PORT]) - "WebSocket /ws" [accepted]
INFO:     connection open
[TIMESTAMP] - opendevin:INFO: agent.py:64 - Using server runtime
[TIMESTAMP] - opendevin:INFO: ssh_box.py:202 - SSHBox is running as opendevin user with USER_ID=[USER_ID] in the sandbox
[TIMESTAMP] - opendevin:INFO: ssh_box.py:247 - Detected initial session.
[TIMESTAMP] - opendevin:INFO: ssh_box.py:249 - Creating new Docker container
[TIMESTAMP] - opendevin:WARNING: ssh_box.py:715 - Using port forwarding till the enable host network mode of Docker is out of experimental mode.Check the 897th issue on https://github.com/OpenDevin/OpenDevin/issues/ for more information.
[TIMESTAMP] - opendevin:INFO: ssh_box.py:688 - Mounting workspace directory: [WORKSPACE_PATH]
[TIMESTAMP] - opendevin:INFO: ssh_box.py:723 - Mounting volumes: {'[WORKSPACE_PATH]': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
[TIMESTAMP] - opendevin:INFO: ssh_box.py:688 - Mounting workspace directory: [WORKSPACE_PATH]
[TIMESTAMP] - opendevin:INFO: ssh_box.py:734 - Container started
[TIMESTAMP] - opendevin:INFO: ssh_box.py:750 - waiting for container to start: 1, container status: running
[TIMESTAMP] - opendevin:INFO: ssh_box.py:409 - Connecting to SSH session...
[TIMESTAMP] - opendevin:INFO: ssh_box.py:411 - You can debug the SSH connection by running: `ssh -v -p [PORT] opendevin@host.docker.internal` using the password '[PASSWORD]'
[TIMESTAMP] - opendevin:INFO: ssh_box.py:415 - Connected to SSH session
[TIMESTAMP] - opendevin:INFO: agent.py:96 - Creating agent CoderAgent using LLM anthropic.claude-3-5-sonnet-20240620-v1:0
[TIMESTAMP] - opendevin:INFO: llm.py:122 - Initializing LLM with model: anthropic.claude-3-5-sonnet-20240620-v1:0

Provider List: https://docs.litellm.ai/docs/providers


Provider List: https://docs.litellm.ai/docs/providers

[TIMESTAMP] - opendevin:WARNING: llm.py:143 - Could not get model info for anthropic.claude-3-5-sonnet-20240620-v1:0
[TIMESTAMP] - opendevin:INFO: mixin.py:41 - Initializing plugins in the sandbox
[TIMESTAMP] - opendevin:ERROR: state.py:64 - Failed to restore state from session: sessions/[SESSION_ID]/agent_state.pkl
Error restoring state sessions/[SESSION_ID]/agent_state.pkl
[TIMESTAMP] - opendevin:INFO: agent_controller.py:197 - [Agent Controller [CONTROLLER_ID]] Setting agent(CoderAgent) state from AgentState.LOADING to AgentState.INIT
[TIMESTAMP] - opendevin:INFO: agent_controller.py:135 - [Agent Controller [CONTROLLER_ID]] Starting step loop...
INFO:     [IP_ADDRESS]:[PORT] - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK
[TIMESTAMP] - OBSERVATION
**MessageAction** (source=EventSource.USER)
CONTENT: This is a test
[TIMESTAMP] - opendevin:INFO: agent_controller.py:197 - [Agent Controller [CONTROLLER_ID]] Setting agent(CoderAgent) state from AgentState.INIT to AgentState.RUNNING
INFO:     [IP_ADDRESS]:[PORT] - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK


==============
CoderAgent LEVEL 0 STEP 0


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2242, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/bedrock_httpx.py", line 1807, in completion
    sigv4.add_auth(request)
  File "/app/.venv/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 138, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 316, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/micro/agent.py", line 67, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 209, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 956, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 851, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2606, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 7540, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 6312, in exception_type
    response=original_exception.response,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoCredentialsError' object has no attribute 'response'
[TIMESTAMP] - opendevin:ERROR: agent_controller.py:144 - Error while running the agent: 'NoCredentialsError' object has no attribute 'response'
[TIMESTAMP] - opendevin:ERROR: agent_controller.py:145 - Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2242, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/bedrock_httpx.py", line 1807, in completion
    sigv4.add_auth(request)
  File "/app/.venv/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 138, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 316, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/micro/agent.py", line 67, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 209, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 956, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 851, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2606, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 7540, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 6312, in exception_type
    response=original_exception.response,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoCredentialsError' object has no attribute 'response'

[TIMESTAMP] - OBSERVATION
ErrorObservation(content='There was an unexpected error while running the agent', observation='error')
[TIMESTAMP] - opendevin:INFO: agent_controller.py:197 - [Agent Controller [CONTROLLER_ID]] Setting agent(CoderAgent) state from AgentState.RUNNING to AgentState.ERROR
INFO:     [IP_ADDRESS]:[PORT] - "GET /api

**Comment by while-basic** [comment]
<img width="1664" alt="Screenshot 2024-07-04 at 3 26 07 PM" src="https://github.com/OpenDevin/OpenDevin/assets/130608813/28212808-0bc2-4aef-ba3c-4a774a61cc5f">
Same issue here

**Comment by enyst** [comment]
> [TIMESTAMP] - opendevin:INFO: llm.py:122 - Initializing LLM with model: anthropic.claude-3-5-sonnet-20240620-v1:0

Are you sure that model name is valid? I see model name = "claude-3-5-sonnet-20240620".

(for example here https://docs.anthropic.com/en/api/client-sdks)

**Comment by scottsantinho** [comment]
@enyst Thanks, that was indeed the issue !

**Comment by Michael-Tanzer** [comment]
What did you change the model name to? It matches the name on the anthropic documnentation

**Comment by martinrebane** [comment]
As of today the model dropdown in Configuration offers 2 versions, one has `antrophic` prefix - this does not work for me. Other is just a model name, currently `claude-3-5-sonnet-20240620` works well for me.

**Comment by tobitege** [comment]
The ones with vendor names in front of the models would be for use with OpenRouter.
