### ISSUE TITLE
[Bug]: ERROR: session.py:73 - Error creating controller: Failed to initialize plugin agent_skills with exit code 126 and output: -bash: /opendevin/plugins/agent_skills/setup.sh: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by ForrestTrepte** [OpenDevin/OpenDevin#2817]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I am a new user attempting to set up a development environment according to Development.md. While executing `make run`, the following error occurred:

```
11:46:16 - opendevin:INFO: mixin.py:43 - Initializing plugins in the sandbox
11:46:16 - opendevin:INFO: mixin.py:30 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
11:46:16 - opendevin:INFO: mixin.py:60 - Copied files from [/mnt/c/s/OpenDevin/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
11:46:16 - opendevin:INFO: mixin.py:68 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
11:46:16 - opendevin:ERROR: session.py:73 - Error creating controller: Failed to initialize plugin agent_skills with exit code 126 and output: -bash: /opendevin/plugins/agent_skills/setup.sh: /bin/bash^M: bad interpreter: No such file or directory
Traceback (most recent call last):
  File "/mnt/c/s/OpenDevin/opendevin/server/session/session.py", line 71, in _initialize_agent
    await self.agent_session.start(data)
  File "/mnt/c/s/OpenDevin/opendevin/server/session/agent.py", line 47, in start
    await self._create_controller(start_event)
  File "/mnt/c/s/OpenDevin/opendevin/server/session/agent.py", line 104, in _create_controller
    self.runtime.init_sandbox_plugins(agent.sandbox_plugins)
  File "/mnt/c/s/OpenDevin/opendevin/runtime/runtime.py", line 89, in init_sandbox_plugins
    self.sandbox.init_plugins(plugins)
  File "/mnt/c/s/OpenDevin/opendevin/runtime/plugins/mixin.py", line 83, in init_plugins
    raise RuntimeError(
RuntimeError: Failed to initialize plugin agent_skills with exit code 126 and output: -bash: /opendevin/plugins/agent_skills/setup.sh: /bin/bash^M: bad interpreter: No such file or directory
^CINFO:     Shutting down
make: *** [Makefile:228: run] Interrupt
```

Searching for info on `bad interpreter` errors suggests that this may be a file containing an invalid Windows carriage return line ending. However, I don't yet have the knowledge of where the plugin setup.sh comes from to verify if that is the case. I am using Windows as my development environment. Although I am running make inside Ubuntu via WSL, I cloned the repository using Git for Windows so perhaps Git is inserting Windows line endings into a file and introducing the problem?

### Current OpenDevin version

```bash
I am building from source from the main branch at commit hash 99284da4.
```

### Installation and Configuration

```bash
make build
make setup-config
make run

config.toml:

[core]
workspace_base="/mnt/c/s/OpenDevinTest/workspace"
persist_sandbox=false

[llm]
model="gpt-4o"
api_key="REDACTED"
embedding_model="openai"
```

### Operating System

Windows

**Comment by ForrestTrepte** [comment]
This problem was indeed caused by Git adding CRLF to files. So not a Devin bug, but a configuration issue. I no longer have the error after turning off the git autocrlf setting like this:

```
git config core.autocrlf false
git rm --cached -r .
git reset --hard
make build
make run
```
