### ISSUE TITLE
No such file or directory: certifi-2023.11.17

### ISSUE THREAD

**Issue by power9799** [OpenDevin/OpenDevin#303]
**Describe the bug**
While running this on Apple Silicon Mac, I got this error
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/private/tmp/python-certifi-20231117-4919-2f0o9m/certifi-2023.11.17'

**Steps to Reproduce**
```.docker ps # this should exit successfully
docker pull ghcr.io/opendevin/sandbox:v0.1
this was successful 
but this : ``` export OPENAI_API_KEY="..." Also I tried add my api key, but still the same error
export WORKSPACE_DIR="/path/to/your/project"
python -m pip install -r requirements.txt
uvicorn opendevin.server.listen:app --port 3000
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/private/tmp/python-certifi-20231117-4919-2f0o9m/certifi-2023.11.17'

Traceback (most recent call last):
  File "/opt/homebrew/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/main.py", line 418, in main
    run(
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'opendevin'
**Expected behavior**
it should install 
**Actual behavior**

**Additional context**
<!-- Please include logs, screenshots, etc. -->

**Comment by SnowingFox** [comment]
i can run it in m2 pro

**Comment by yashpokar** [comment]
Its working for me as well.

Try using virtualenv if you are not

**Comment by rbren** [comment]
Virtualenv is a good idea. You can also try
```
pip install --upgrade --force-reinstall certifi
```

**Comment by Zoyashah01** [comment]
Encounter "No such file or directory: certifi-2023.11.17" exclusively at Lulu Dubai. Troubleshoot and resolve this issue related to missing or inaccessible files, ensuring smooth operation of your software environment. Just as Lulu Dubai offers a diverse range of products and services, this opportunity provides essential guidance for resolving file-related errors effectively. Address the issue promptly to maintain the integrity and functionality of your system. Access exclusive content now at [Lulu Dubai!](https://wowdeals360.com/dubai/)

**Comment by power9799** [comment]
> Virtualenv is a good idea. You can also try
> 
> ```
> pip install --upgrade --force-reinstall certifi
> ```

I tried this still didn't work, still the same error when using docker pull ghcr.io/opendevin/sandbox:v0.1
this was successful 
but this : ``` export OPENAI_API_KEY="..." 
export WORKSPACE_DIR="/path/to/your/project"
python -m pip install -r requirements.txt
uvicorn opendevin.server.listen:app --port 3000
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/private/tmp/python-certifi-20231117-4919-2f0o9m/certifi-2023.11.17'

**Comment by rbren** [comment]
@power9799 seems like no one else is seeing this issue, so I'm going to assume it's a problem with your env rather than with OpenDevin.

Best advice is to try and rebuild your env from scratch as much as possible (e.g. uninstall and reinstall python, all packages, etc). There are a handful of guides on doing this out there, given how finicky python can be.

I'm going to close this issue for now, but let us know if you get anywhere, or if you find any more info we could use to debug
