### ISSUE TITLE
Support file inputs for task in main.py

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#322]
Given the following task
```
PYTHONPATH=`pwd`:`pwd`/workspace  python opendevin/main.py -d ./workspace/ -i 100 -t "
Given the following python math_util.py module where list x and y contain a list of positive float numbers with values between 0 and 1. Give suggestion to fix incorrectness and optimize the code and generate the corresponding testto ensure 95%+ code coverage.

import math
import sys
sys.path.append("/Users/jwang/Documents/workspace/OpenDevin/workspace")


def wassersteinDistance(x: list, y: list):
    x_len = len(x)
    y_len = len(y)
    
    if x_len != y_len or x_len < 1:
        return float('inf')
    
    lastDistance = 0.0
    totalDistance = 0.0
    for i in range(x_len):
      currentDistance = (x[i] + lastDistance) - y[i]
      totalDistance += abs(currentDistance)
      lastDistance = currentDistance

    return totalDistance


def kullbackLeiblerDivergence(x: list, y: list):
    intersection = False
    kl = 0.0
    x_len = len(x)
    y_len = len(y)
    
    if x_len != y_len or x_len < 1:
        return float('inf')
    
    for i in range(x_len):
        if x[i] > 0.0 and y[i] > 0:
            intersection = True
            kl += x[i] * math.log(x[i]/y[i])
    if intersection:
      return kl
    else:
      return float('inf')


def jensenShannonDivergence(x: list, y: list):
    x_len = len(x)
    m = [0] * x_len
    for i in range(x_len):
        m[i] = (x[i] + y[i]) / 2.0;

    return (kullbackLeiblerDivergence(x, m) + kullbackLeiblerDivergence(y, m)) / 2.0;


def jensenShannonDistance(x: list, y: list):
    return math.sqrt(jensenShannonDivergence(x, y))
"
```

get the following error
```
STEP 12

        ACTION:
        FileReadAction(path='math_util.py', base_path='')
FileReadAction(path='math_util.py', base_path='./workspace/')

        ACTION RUN ERROR:
        [Errno 2] No such file or directory: './workspace/math_util.py'
Traceback (most recent call last):
  File "/Users/jwang/Documents/workspace/OpenDevin/opendevin/controller/__init__.py", line 105, in step
    observation = action.run(self)
                  ^^^^^^^^^^^^^^^^
  File "/Users/jwang/Documents/workspace/OpenDevin/opendevin/action/fileop.py", line 24, in run
    with open(path, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './workspace/math_util.py'

        OBSERVATION:
        [Errno 2] No such file or directory: './workspace/math_util.py'

```

**Comment by rbren** [comment]
The issue is with the `-t` string--bash interpolates strings in double quotes.

We should probably support accepting a prompt from a file, or piping from stdin

**Comment by josephykwang** [comment]
the following seems to work

```
PYTHONPATH=`pwd`:`pwd`/workspace  python opendevin/main.py -d ./workspace/ -i 100 -t 'Given the following python math_util.py module where list x and y contain a list of positive float numbers with values can range from 0.0 to 1.0, inclusive. Give suggestion to fix incorrectness and optimize the code and generate the corresponding testto ensure 95%+ code coverage.


import math
import sys
sys.path.append("/Users/jwang/Documents/workspace/OpenDevin/workspace")


def wassersteinDistance(x: list, y: list):
    """Wasserstein distance between two float lists.
    Args:
        x: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
        y: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
    """
    x_len = len(x)
    y_len = len(y)
    
    if x_len != y_len or x_len < 1:
        return float('inf')
    
    lastDistance = 0.0
    totalDistance = 0.0
    for i in range(x_len):
      currentDistance = (x[i] + lastDistance) - y[i]
      totalDistance += abs(currentDistance)
      lastDistance = currentDistance

    return totalDistance


def kullbackLeiblerDivergence(x: list, y: list):
    """KullbackLeibler divergence between two float lists.
    Args:
        x: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
        y: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
    """
    intersection = False
    kl = 0.0
    x_len = len(x)
    y_len = len(y)
    
    if x_len != y_len or x_len < 1:
        return float('inf')
    
    for i in range(x_len):
        if x[i] > 0.0 and y[i] > 0:
            intersection = True
            kl += x[i] * math.log(x[i]/y[i])
    if intersection:
      return kl
    else:
      return float('inf')


def jensenShannonDivergence(x: list, y: list):
    """Jensen Shannon divergence between two float lists.
    Args:
        x: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
        y: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
    """
    x_len = len(x)
    m = [0] * x_len
    for i in range(x_len):
        m[i] = (x[i] + y[i]) / 2.0;

    return (kullbackLeiblerDivergence(x, m) + kullbackLeiblerDivergence(y, m)) / 2.0;


def jensenShannonDistance(x: list, y: list):
    """Jensen Shannon distance between two float lists.
    Args:
        x: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
        y: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
    """
    return math.sqrt(jensenShannonDivergence(x, y))
'
```
