### ISSUE TITLE
[Bug]: 'ServerRuntime' object has no attribute 'file_store'

### ISSUE THREAD

**Issue by sammcj** [OpenDevin/OpenDevin#3283]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

```
09:59:00 - opendevin:INFO: agent.py:103 - Creating agent CodeActAgent using LLM ollama/deepseek-coder-v2-lite-instruct:q6_k_l
09:59:00 - opendevin:INFO: browser_env.py:58 - Starting browser env...
09:59:04 - opendevin:INFO: browser_env.py:101 - Browser env started.
09:59:04 - opendevin:INFO: agent.py:132 - Restored agent state from session, sid: d0bcd537-6aa1-4e3e-a76d-4fea84167da7
09:59:04 - opendevin:INFO: agent_controller.py:140 - [Agent Controller d0bcd537-6aa1-4e3e-a76d-4fea84167da7] Starting step loop...
09:59:04 - opendevin:ERROR: listen.py:462 - Error listing files: 'ServerRuntime' object has no attribute 'file_store'
Traceback (most recent call last):
  File "/app/opendevin/server/listen.py", line 388, in list_files
    request.state.session.agent_session.runtime.file_store.get_full_path(path)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ServerRuntime' object has no attribute 'file_store'
INFO:     172.22.0.28:47358 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK
09:59:15 - USER_ACTION
**MessageAction** (source=EventSource.USER)
CONTENT: Create a basic html website with hello world and bootstrap
09:59:15 - opendevin:ERROR: listen.py:462 - Error listing files: 'ServerRuntime' object has no attribute 'file_store'
Traceback (most recent call last):
  File "/app/opendevin/server/listen.py", line 388, in list_files
    request.state.session.agent_session.runtime.file_store.get_full_path(path)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ServerRuntime' object has no attribute 'file_store'
INFO:     172.22.0.28:60140 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK
```

### Current OpenDevin version

```bash
main as of 2024-08-07 - sha256:c882300bcdac79d21c27837195fea0c159783ce0a9b4178f6c273a8902f7052e
```

### Installation and Configuration

```bash
- Using official Docker image


...
services:
  &name opendevin:
    <<: [*ai-common, *restart, *autoupdate, *gpu]
    container_name: *name
    hostname: *name
    profiles:
      - *name
    image: ghcr.io/opendevin/opendevin:main
    env_file:
      - ./env/.opendevin.env
    ports:
      - 3000
    volumes:
      - /mnt/llm/opendevin/workspace:/opt/workspace_base
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/llm/opendevin/transformers_cache:/mnt/llm/opendevin/transformers_cache
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik-servicenet
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      traefik.enable: true
      org.hotio.pullio.update: true
      traefik.http.routers.opendevin.rule: Host(`opendevin.internal.domain`)
      traefik.http.routers.opendevin.tls.certresolver: le
      traefik.http.routers.opendevin.entrypoints: websecure
      traefik.http.routers.opendevin.tls.domains[0].main: "*.internal.domain"
      traefik.http.routers.opendevin.service: opendevin-service
      traefik.http.services.opendevin-service.loadbalancer.server.port: 3000
      traefik.http.routers.opendevin.middlewares: authentik


.env:

```
SANDBOX_USER_ID=<redacted>
WORKSPACE_MOUNT_PATH=/mnt/llm/opendevin/workspace
WORKSPACE_BASE=/mnt/llm/opendevin/workspace
WORKSPACE_MOUNT_PATH_IN_SANDBOX = /workspace
SANDBOX_CONTAINER_IMAGE="nikolaik/python-nodejs:python3.12-nodejs22" (tried with stock as well)
LLM_API_KEY=<redacted>
LLM_BASE_URL=http://ollama:11434
LLM_OLLAMA_BASE_URL=http://ollama:11434
LLM_TEMPERATURE=0.3
LLM_MAX_INPUT_TOKENS=16384
LLM_EMBEDDING_MODEL=nomic-embed-text:latest
TRANSFORMERS_CACHE=/mnt/llm/opendevin/transformers_cache
LLM_MODEL="ollama/deepseek-coder-v2-lite-instruct:q6_k_l"
PERSIST_SANDBOX=true
SSH_PASSWORD="<redacted>"
TZ=Australia/Melbourne
```
```

### Model and Agent

- deepseek-coder-v2-lite-instruct

### Operating System

- Fedora 40

**Comment by sammcj** [comment]
A whole new error now!

```
Starting OpenDevin...
Setting up enduser with id 1337
Docker socket group id: 976
Creating group with id 976
Running as enduser
INFO:     Started server process [72]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     connection open
INFO:     connection closed
INFO:     ('172.22.0.23', 53212) - "WebSocket /ws" [accepted]
INFO:     connection open
22:15:54 - opendevin:INFO: agent.py:78 - Using runtime: eventstream
22:15:54 - opendevin:ERROR: session.py:116 - Error creating controller: [Errno 2] No such file or directory: '/app/pyproject.toml'
Traceback (most recent call last):
  File "/app/opendevin/server/session/session.py", line 106, in _initialize_agent
    await self.agent_session.start(
  File "/app/opendevin/server/session/agent.py", line 53, in start
    await self._create_runtime(runtime_name, config, agent)
  File "/app/opendevin/server/session/agent.py", line 86, in _create_runtime
    await self.runtime.ainit()
  File "/app/opendevin/runtime/client/runtime.py", line 82, in ainit
    self.container_image = build_runtime_image(
                           ^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/utils/runtime_build.py", line 247, in build_runtime_image
    runtime_image_repo, runtime_image_tag = get_runtime_image_repo_and_tag(base_image)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/utils/runtime_build.py", line 213, in get_runtime_image_repo_and_tag
    od_version = _get_package_version()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/utils/runtime_build.py", line 24, in _get_package_version
    with open(pyproject_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/app/pyproject.toml'
```

**Comment by xingyaoww** [comment]
Are you launching using the Docker Image? Hmm could be a recent bug caused by #3271. Let me take a look
