### ISSUE TITLE
[Bug]: NoCredentialsError while trying to use ClaudeSonnet

### ISSUE THREAD

**Issue by GM-dot-one** [OpenDevin/OpenDevin#3310]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

While trying to get started with OpenDevin using Claude, I get an error AttributeError: 'NoCredentialsError' object has no attribute 'response'

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin:0.8
```

### Installation and Configuration

```bash
I provided the API key using the UI and also in the config.toml file
WORKSPACE_BASE=/Users/gaurav/Code/OpenDevin/workspace/
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8
latest: Pulling from opendevin/opendevin
Digest: sha256:ecb9f793d304e2127a99da8ce6c4418f2459fb0f0eafb25b5a4146d73e134c40
Status: Downloaded newer image for ghcr.io/opendevin/opendevin:latest
Starting OpenDevin...
Setting up enduser with id 501
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_cloud/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
10:46:20 - opendevin:INFO: config.py:437 - Config file not found: [Errno 2] No such file or directory: 'config.toml'
INFO:     Started server process [36]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     ('192.168.65.1', 24044) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI3ODQ1Y2I0Ny0wOTUwLTQ1NDUtOTFhMS00YThhNjBiNDZjODgifQ.SauAnO686AGHylWvmllVb9NeL_XNCjuboYfw-ngq0Rc&latest_event_id=9" [accepted]
10:46:22 - opendevin:ERROR: auth.py:27 - Invalid token
INFO:     connection open
INFO:     connection closed
INFO:     ('192.168.65.1', 48512) - "WebSocket /ws" [accepted]
INFO:     connection open

Provider List: https://docs.litellm.ai/docs/providers


Provider List: https://docs.litellm.ai/docs/providers

10:46:25 - opendevin:WARNING: llm.py:70 - Could not get model info for anthropic.claude-3-sonnet-20240229-v1:0
10:46:25 - opendevin:INFO: agent.py:79 - Using runtime: server
10:46:25 - opendevin:INFO: ssh_box.py:135 - SSHBox is running as opendevin user with USER_ID=501 in the sandbox
10:46:25 - opendevin:INFO: ssh_box.py:178 - Detected initial session.
10:46:25 - opendevin:INFO: ssh_box.py:180 - Creating new Docker container
10:46:25 - opendevin:WARNING: ssh_box.py:578 - Using port forwarding till the enable host network mode of Docker is out of experimental mode.Check the 897th issue on https://github.com/OpenDevin/OpenDevin/issues/ for more information.
10:46:25 - opendevin:INFO: ssh_box.py:586 - Mounting volumes: {'/Users/gaurav/Code/OpenDevin/workspace/': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
10:46:26 - opendevin:INFO: ssh_box.py:597 - Container started
10:46:27 - opendevin:INFO: ssh_box.py:613 - waiting for container to start: 1, container status: running
10:46:28 - opendevin:INFO: ssh_box.py:342 - Connecting to SSH session...
10:46:28 - opendevin:INFO: ssh_box.py:345 - You can debug the SSH connection by running: `ssh -v -p 55753 opendevin@localhost` using the password '2372e363-28d4-496f-afce-1941d976d9ea'
10:46:29 - opendevin:INFO: ssh_box.py:349 - Connected to SSH session
10:46:32 - opendevin:INFO: agent.py:100 - Creating agent CodeActAgent using LLM anthropic.claude-3-sonnet-20240229-v1:0
10:46:32 - opendevin:INFO: mixin.py:42 - Initializing plugins in the sandbox
10:46:32 - opendevin:INFO: mixin.py:30 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
10:46:32 - opendevin:INFO: mixin.py:59 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
10:46:32 - opendevin:INFO: mixin.py:67 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
10:46:34 - opendevin:INFO: mixin.py:85 - Plugin agent_skills initialized successfully
10:46:34 - opendevin:INFO: mixin.py:30 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
10:46:34 - opendevin:INFO: mixin.py:59 - Copied files from [/app/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
10:46:34 - opendevin:INFO: mixin.py:67 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
10:46:36 - opendevin:INFO: mixin.py:85 - Plugin jupyter initialized successfully
10:46:36 - opendevin:INFO: mixin.py:30 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
10:46:36 - opendevin:INFO: browser_env.py:78 - Starting browser env...
10:46:36 - opendevin:ERROR: state.py:127 - Failed to restore state from session: sessions/72b3707a-1a79-4570-b36b-b2c47d3ac3b2/agent_state.pkl
Error restoring state sessions/72b3707a-1a79-4570-b36b-b2c47d3ac3b2/agent_state.pkl
10:46:36 - opendevin:INFO: agent_controller.py:140 - [Agent Controller 72b3707a-1a79-4570-b36b-b2c47d3ac3b2] Starting step loop...
INFO:     192.168.65.1:27179 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK
10:46:41 - opendevin:INFO: browser_env.py:121 - Browser env started.
10:46:51 - USER_ACTION
**MessageAction** (source=EventSource.USER)
CONTENT: Create a simple Hello World application in python
INFO:     192.168.65.1:61281 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK


==============
CodeActAgent LEVEL 0 LOCAL STEP 0 GLOBAL STEP 0


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2317, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/bedrock_httpx.py", line 1940, in completion
    sigv4.add_auth(request)
  File "/app/.venv/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 143, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 392, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 194, in step
    response = self.llm.completion(
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 154, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1028, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 908, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2750, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 8072, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 6845, in exception_type
    response=original_exception.response,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoCredentialsError' object has no attribute 'response'
10:46:53 - opendevin:ERROR: agent_controller.py:149 - Error while running the agent: 'NoCredentialsError' object has no attribute 'response'
10:46:53 - opendevin:ERROR: agent_controller.py:150 - Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2317, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/bedrock_httpx.py", line 1940, in completion
    sigv4.add_auth(request)
  File "/app/.venv/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 143, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 392, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 194, in step
    response = self.llm.completion(
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 154, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1028, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 908, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2750, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 8072, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 6845, in exception_type
    response=original_exception.response,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoCredentialsError' object has no attribute 'response'

10:46:53 - OBSERVATION
ErrorObservation(content='There was an unexpected error while running the agent', observation='error')
INFO:     192.168.65.1:61281 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK
```

### Model and Agent

Model:anthropic.claude-3-sonnet-20240229-v1:0
Agent:CodeActAgent

### Operating System

MacOS

### Reproduction Steps

>WORKSPACE_BASE=/Users/gaurav/Code/OpenDevin/workspace/
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8

**Comment by neubig** [comment]
Hey @GM-dot-one , this looks like:
1. Maybe your credentials for Amazon Bedrock are not working properly (invalid API key, etc.)
2. There is an issue with the upstream [litellm library](https://github.com/BerriAI/litellm) that is not catching this properly.

Could you please try following the directions here with your current credentials and see if they work?
https://litellm.vercel.app/docs/providers/bedrock

If they do, then I think OpenDevin should also work, but please tell me if you're still having any issues!

**Comment by mamoodi** [comment]
@GM-dot-one this might be an issue with your model name. See this issue: https://github.com/OpenDevin/OpenDevin/issues/2801

**Comment by GM-dot-one** [comment]
Thanks @mamoodi and @neubig for the suggestions. The problem turned out to be not having any file in the ./workspace folder. It was cascading an error to the credentials code and causing the error. I put a dummy file in the ./workspace folder and everything started working like a charm.

**Comment by neubig** [comment]
Great, thanks!
