### ISSUE TITLE
LLM Provider NOT provided.

### ISSUE THREAD

**Issue by Likhithsai2580** [OpenDevin/OpenDevin#334]
**Describe the bug**

**Steps to Reproduce**
1.set envs as described in https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#picking-a-model
2.run the command uvicorn opendevin.server.listen:app --port 3000

**Expected behavior**
it should respond properly

**Actual behavior**
Traceback (most recent call last):
  File "C:\Users\gunap\Documents\OpenDevin\opendevin\controller\__init__.py", line 85, in step
    action = self.agent.step(state)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gunap\Documents\OpenDevin\agenthub\langchains_agent\__init__.py", line 172, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gunap\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 2807, in wrapper
    raise e
  File "C:\Users\gunap\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 2705, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gunap\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\main.py", line 2094, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\gunap\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 8296, in exception_type
    raise e
  File "C:\Users\gunap\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 8264, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model="ollama/llama2:13b"
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

**Additional context**
![image](https://github.com/OpenDevin/OpenDevin/assets/62712260/66cd077c-fdbd-4012-82af-e50f81ba7f0f)

**Comment by Likhithsai2580** [comment]
fixed

**Comment by sercanerhan** [comment]
@Likhithsai2580 how did you fixed it and were you trying a `local` llm?

**Comment by Likhithsai2580** [comment]
export LLM_MODEL=ollama/llama2
export LLM_API_KEY=
export LLM_BASE_URL=http://localhost:11434

**Comment by Likhithsai2580** [comment]
all the best

**Comment by Likhithsai2580** [comment]
i am seeing these alternatives for devin
opendevin
devika
https://github.com/semanser/codel

**Comment by sercanerhan** [comment]
thank you @Likhithsai2580 for your guidance. 
I've also one more line for the embedings such as:
```toml
LLM_EMBEDDING_MODEL="local"
```
but looks like the user agent works but the langchain group chat does not work with the other coder agent. Will try to understand the behavior later on, thank you.

**Comment by Likhithsai2580** [comment]
You're welcome!

**Comment by alam220** [comment]
openrouter api how to setup . 

The LLM provider is currently unavailable. Please try again later.
