### ISSUE TITLE
source code string cannot contain null bytes

### ISSUE THREAD

**Issue by Lase9** [OpenDevin/OpenDevin#336]
im in windows 11 any fix ?
all the requirements are installed 

```
C:\Users\lase9\Desktop\OpenDevin-main>uvicorn opendevin.server.listen:app --port 3000
C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\main.py", line 409, in main
    run(
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\lase9\Desktop\OpenDevin-main\opendevin\server\listen.py", line 3, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "C:\Users\lase9\Desktop\OpenDevin-main\agenthub\__init__.py", line 5, in <module>
    from . import langchains_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lase9\Desktop\OpenDevin-main\agenthub\langchains_agent\__init__.py", line 2, in <module>
    from .langchains_agent import LangchainsAgent
  File "C:\Users\lase9\Desktop\OpenDevin-main\agenthub\langchains_agent\langchains_agent.py", line 8, in <module>
    from agenthub.langchains_agent.utils.memory import LongTermMemory
  File "C:\Users\lase9\Desktop\OpenDevin-main\agenthub\langchains_agent\utils\memory.py", line 4, in <module>
    from llama_index.core import Document
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_index\core\__init__.py", line 10, in <module>
    from llama_index.core.base.response.schema import Response
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_index\core\base\response\schema.py", line 8, in <module>
    from llama_index.core.schema import NodeWithScore
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_index\core\schema.py", line 15, in <module>
    from llama_index.core.utils import SAMPLE_TEXT, truncate_text
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_index\core\utils.py", line 89, in <module>
    globals_helper = GlobalsHelper()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_index\core\utils.py", line 45, in __init__
    import nltk
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\__init__.py", line 135, in <module>
    from nltk.featstruct import *
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\featstruct.py", line 97, in <module>
    from nltk.sem.logic import (
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\sem\__init__.py", line 44, in <module>
    from nltk.sem.boxer import Boxer
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\sem\boxer.py", line 40, in <module>
    from nltk.sem.drt import (
  File "C:\Users\lase9\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\sem\drt.py", line 43, in <module>
    from tkinter import Canvas, Tk
SyntaxError: source code string cannot contain null bytes

```

**Comment by Lase9** [comment]
i fix it by adding this to Python\Python312\Lib\site-packages\nltk\sem\drt.py

```
import sys
sys.modules['tkinter'] = None
```
