### ISSUE TITLE
unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#347]
```
export WORKSPACE_DIR="~/ml-code/OpenDevin/workspace"
export OPENAI_API_KEY=...
export LLM_API_KEY=...
python -m pip install -r requirements.txt
pip3 install -U pytest
pip3 install coverage 
uvicorn opendevin.server.listen:app --port 3000```

get 
```
Traceback (most recent call last):
  File "/opt/miniconda/envs/py3916/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/opt/miniconda/envs/py3916/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/miniconda/envs/py3916/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/opt/miniconda/envs/py3916/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/ml-code/OpenDevin/opendevin/server/listen.py", line 1, in <module>
    from opendevin.server.session import Session
  File "/home/user/ml-code/OpenDevin/opendevin/server/session.py", line 13, in <module>
    from opendevin.controller import AgentController
  File "/home/user/ml-code/OpenDevin/opendevin/controller/__init__.py", line 1, in <module>
    from .agent_controller import AgentController
  File "/home/user/ml-code/OpenDevin/opendevin/controller/agent_controller.py", line 19, in <module>
    from .command_manager import CommandManager
  File "/home/user/ml-code/OpenDevin/opendevin/controller/command_manager.py", line 4, in <module>
    from opendevin.sandbox.sandbox import DockerInteractive
  File "/home/user/ml-code/OpenDevin/opendevin/sandbox/sandbox.py", line 80, in <module>
    class DockerInteractive:
  File "/home/user/ml-code/OpenDevin/opendevin/sandbox/sandbox.py", line 87, in DockerInteractive
    workspace_dir: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by josephykwang** [comment]
think the problem the current sandbox does not mount other

**Comment by josephykwang** [comment]
saw [Python](https://www.python.org/downloads/) >= 3.10
