### ISSUE TITLE
tomllb not found

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#362]
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ pipenv shell
Launching subshell in virtual environment...
pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$  . /home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/bin/activate
(OpenDevin) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ python3 -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
(OpenDevin) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ uvicorn opendevin.server.listen:app --port 3000
Traceback (most recent call last):
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/listen.py", line 1, in <module>
    from opendevin.server.session import Session
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/session.py", line 7, in <module>
    from opendevin import config
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/config.py", line 2, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

**Comment by rbren** [comment]
Fix is here: https://github.com/OpenDevin/OpenDevin/pull/363

**Comment by PierrunoYT** [comment]
@rbren Something still dont want to work To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ pipenv shell
Launching subshell in virtual environment...
pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$  . /home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/bin/activate
(OpenDevin) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ uvicorn opendevin.server.listen:app --port 3000
Traceback (most recent call last):
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/listen.py", line 1, in <module>
    from opendevin.server.session import Session
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/session.py", line 7, in <module>
    from opendevin import config
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/config.py", line 13, in <module>
    config = toml.loads(config_str)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/toml/decoder.py", line 340, in loads
    raise TomlDecodeError("Unbalanced quotes", original, i)
toml.decoder.TomlDecodeError: Unbalanced quotes (line 4 column 51 char 198)
