### ISSUE TITLE
There is still a Toml issue

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#364]
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ pipenv shell
Launching subshell in virtual environment...
pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$  . /home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/bin/activate
(OpenDevin) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ uvicorn opendevin.server.listen:app --port 3000
Traceback (most recent call last):
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/listen.py", line 1, in <module>
    from opendevin.server.session import Session
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/session.py", line 7, in <module>
    from opendevin import config
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/config.py", line 13, in <module>
    config = toml.loads(config_str)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/toml/decoder.py", line 340, in loads
    raise TomlDecodeError("Unbalanced quotes", original, i)
toml.decoder.TomlDecodeError: Unbalanced quotes (line 4 column 51 char 198)

**Comment by josephykwang** [comment]
```
(OpenDevin) jwang@jwang-llm:~/OpenDevin$ ./math_util.sh 
Traceback (most recent call last):
  File "/home/user/OpenDevin/opendevin/main.py", line 6, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
  File "/home/user/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import langchains_agent # noqa: E402
  File "/home/user/OpenDevin/agenthub/langchains_agent/__init__.py", line 1, in <module>
    from opendevin.agent import Agent
  File "/home/user/OpenDevin/opendevin/agent.py", line 7, in <module>
    from opendevin.llm.llm import LLM
  File "/home/user/OpenDevin/opendevin/llm/llm.py", line 7, in <module>
    from opendevin import config
  File "/home/user/OpenDevin/opendevin/config.py", line 2, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'
```

**Comment by rbren** [comment]
@josephykwang can you pull latest? I just merged a change that removes the reference to `tomllib`

**Comment by rbren** [comment]
@PierrunoYT can you share your config.toml

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/dbc1d8c4-d1f7-4a2c-838e-1dce741f59c7)

**Comment by rbren** [comment]
You have too many quotes in WORKSPACE_DIR

**Comment by PierrunoYT** [comment]
> You have too many quotes in WORKSPACE_DIR
> 
> see the error message:
> 
> > raise TomlDecodeError("Unbalanced quotes", original, i)
> > toml.decoder.TomlDecodeError: Unbalanced quotes (line 4 column 51 char 198)

Bruh thx I thought I fixed it

**Comment by PierrunoYT** [comment]
@rbren I just fixed it but I get the same error

(OpenDevin) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ uvicorn opendevin.server.listen:app --port 3000
Traceback (most recent call last):
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/toml/decoder.py", line 866, in load_value
    raise ValueError("Reserved escape sequence used")
ValueError: Reserved escape sequence used

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/listen.py", line 1, in <module>
    from opendevin.server.session import Session
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/session.py", line 7, in <module>
    from opendevin import config
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/config.py", line 13, in <module>
    config = toml.loads(config_str)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Reserved escape sequence used (line 4 column 1 char 148)

**Comment by rbren** [comment]
Sounds like there's an issue in your toml file. Do you have a `\` in there? Or some other weird character?

**Comment by rbren** [comment]
ah yeah it's the backslashes for windows. Windows is the worst.

You probably need to write the file like `"C:\\User\\pierr\\"` etc--double the backslashes

**Comment by PierrunoYT** [comment]
> Sounds like there's an issue in your toml file. Do you have a `\` in there? Or some other weird character?

Yeah I copy pasted the path from Windows but it seems it's not working. I'm trying with forward slashes now.

**Comment by josephykwang** [comment]
can we tag new release going forward?
    On Friday, March 29, 2024 at 02:10:38 PM PDT, PierrunoYT ***@***.***> wrote:  
 
 



Sounds like there's an issue in your toml file. Do you have a \ in there? Or some other weird character?


Yeah I copy pasted the path from Windows but it seems it's not working. I'm trying with forward slashes now.

**Comment by rbren** [comment]
@PierrunoYT forward slashes won't work. You need to escape the backward slashes, like `\\`

**Comment by josephykwang** [comment]
pipenv install -v

$ /home/user/.local/share/virtualenvs/OpenDevin-F7ennbR1/bin/python 

/home/user/.local/lib/python3.9/site-packages/pipenv/patched/pip/__pip-runner__.py install -i https://pypi.org/simple 

--no-input --upgrade --no-deps -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt

Using source directory: '/home/user/.local/share/virtualenvs/OpenDevin-F7ennbR1/src'

Looking in indexes: https://pypi.org/simple, https://archive.uber.com/pypi/simple, https://pypi.python.org/simple




Collecting aiohttp==3.9.3 (from -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt (line 1))




  Using cached aiohttp-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)




Collecting aiosignal==1.3.1 (from -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt (line 2))




  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)




Collecting annotated-types==0.6.0 (from -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt (line 3))




  Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)




Collecting anyio==4.3.0 (from -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt (line 4))




  Using cached anyio-4.3.0-py3-none-any.whl (85 kB)


    On Friday, March 29, 2024 at 02:16:55 PM PDT, Joseph Wang ***@***.***> wrote:  
 
  can we tag new release going forward?
    On Friday, March 29, 2024 at 02:10:38 PM PDT, PierrunoYT ***@***.***> wrote:  
 
 



Sounds like there's an issue in your toml file. Do you have a \ in there? Or some other weird character?


Yeah I copy pasted the path from Windows but it seems it's not working. I'm trying with forward slashes now.

**Comment by josephykwang** [comment]
the install hung
```
$ /home/user/venv_devin/bin/python 

/home/user/venv_devin/lib/python3.10/site-packages/pipenv/patched/pip/__pip-runner__.py install -i 

https://pypi.org/simple --no-input --upgrade --no-deps -r 

/tmp/pipenv-pxpy8nhu-requirements/pipenv-zvpku6zd-hashed-reqs.txt

Using source directory: '/home/user/venv_devin/src'

Looking in indexes: https://pypi.org/simple, https://archive.uber.com/pypi/simple, https://pypi.python.org/simple




Collecting build==1.2.1 (from -r /tmp/pipenv-pxpy8nhu-requirements/pipenv-zvpku6zd-hashed-reqs.txt (line 1))




  Using cached build-1.2.1-py3-none-any.whl (21 kB)




Collecting httpcore==1.0.5 (from -r /tmp/pipenv-pxpy8nhu-requirements/pipenv-zvpku6zd-hashed-reqs.txt (line 2))




  Using cached httpcore-1.0.5-py3-none-any.whl (77 kB)




Collecting huggingface-hub==0.22.2 (from huggingface-hub==0.22.2->-r 

/tmp/pipenv-pxpy8nhu-requirements/pipenv-zvpku6zd-hashed-reqs.txt (line 3))




  Using cached huggingface_hub-0.22.2-py3-none-any.whl (388 kB)




Collecting importlib-metadata==7.0.0 (from -r /tmp/pipenv-pxpy8nhu-requirements/pipenv-zvpku6zd-hashed-reqs.txt (line 

4))




  Using cached importlib_metadata-7.0.0-py3-none-any.whl (23 kB)



```
    On Friday, March 29, 2024 at 03:25:56 PM PDT, Joseph Wang ***@***.***> wrote:  
 
  pipenv install -v

$ /home/user/.local/share/virtualenvs/OpenDevin-F7ennbR1/bin/python 

/home/user/.local/lib/python3.9/site-packages/pipenv/patched/pip/__pip-runner__.py install -i https://pypi.org/simple 

--no-input --upgrade --no-deps -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt

Using source directory: '/home/user/.local/share/virtualenvs/OpenDevin-F7ennbR1/src'

Looking in indexes: https://pypi.org/simple, https://archive.uber.com/pypi/simple, https://pypi.python.org/simple




Collecting aiohttp==3.9.3 (from -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt (line 1))




  Using cached aiohttp-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)




Collecting aiosignal==1.3.1 (from -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt (line 2))




  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)




Collecting annotated-types==0.6.0 (from -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt (line 3))




  Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)




Collecting anyio==4.3.0 (from -r /tmp/pipenv-tgp9z66n-requirements/pipenv-immimyrd-hashed-reqs.txt (line 4))




  Using cached anyio-4.3.0-py3-none-any.whl (85 kB)


    On Friday, March 29, 2024 at 02:16:55 PM PDT, Joseph Wang ***@***.***> wrote:  
 
  can we tag new release going forward?
    On Friday, March 29, 2024 at 02:10:38 PM PDT, PierrunoYT ***@***.***> wrote:  
 
 



Sounds like there's an issue in your toml file. Do you have a \ in there? Or some other weird character?


Yeah I copy pasted the path from Windows but it seems it's not working. I'm trying with forward slashes now.
