### ISSUE TITLE
Error in loop from_bytes() missing required argument 'byteorder' (pos 2)

### ISSUE THREAD

**Issue by ntrpnr** [OpenDevin/OpenDevin#373]
After 50 steps I got this error

```
Error in loop from_bytes() missing required argument 'byteorder' (pos 2)
Traceback (most recent call last):
  File "/home/erik/OpenDevin/opendevin/controller/agent_controller.py", line 62, in start_loop
    finished = await self.step(i)
  File "/home/erik/OpenDevin/opendevin/controller/agent_controller.py", line 78, in step
    log_obs = self.command_manager.get_background_obs()
  File "/home/erik/OpenDevin/opendevin/controller/command_manager.py", line 47, in get_background_obs
    output = cmd.read_logs()
  File "/home/erik/OpenDevin/opendevin/sandbox/sandbox.py", line 73, in read_logs
    chunk, last_remains = self.parse_docker_exec_output(last_remains + data)
  File "/home/erik/OpenDevin/opendevin/sandbox/sandbox.py", line 55, in parse_docker_exec_output
    msg_length = int.from_bytes(prefix[4:8])  # , byteorder='big'
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)
Exited before finishing
Client websocket disconnected (1001, None)
INFO:     connection closed
```

**Comment by rbren** [comment]
This is fixed in the main branch. Can you pull latest?

**Comment by ntrpnr** [comment]
@rbren Just now (5 min) got the latest docker image. I still have the same issue.

```
Error in loop from_bytes() missing required argument 'byteorder' (pos 2)
Traceback (most recent call last):
  File "/home/erik/OpenDevin/opendevin/controller/agent_controller.py", line 62, in start_loop
    finished = await self.step(i)
  File "/home/erik/OpenDevin/opendevin/controller/agent_controller.py", line 78, in step
    log_obs = self.command_manager.get_background_obs()
  File "/home/erik/OpenDevin/opendevin/controller/command_manager.py", line 47, in get_background_obs
    output = cmd.read_logs()
  File "/home/erik/OpenDevin/opendevin/sandbox/sandbox.py", line 73, in read_logs
    chunk, last_remains = self.parse_docker_exec_output(last_remains + data)
  File "/home/erik/OpenDevin/opendevin/sandbox/sandbox.py", line 55, in parse_docker_exec_output
    msg_length = int.from_bytes(prefix[4:8])  # , byteorder='big'
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)
```

**Comment by ntrpnr** [comment]
Alright, I will investigate furhter
