### ISSUE TITLE
Your system has an unsupported version of sqlite3

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#375]
running commit 413f5b1c0b75c2f6292e46458c7359b71227acec

```(venv_devin) jwang@jwang-llm:~/OpenDevin$ ./math_util.sh 
Traceback (most recent call last):
  File "/home/user/OpenDevin/opendevin/main.py", line 6, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
  File "/home/user/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import langchains_agent # noqa: E402
  File "/home/user/OpenDevin/agenthub/langchains_agent/__init__.py", line 9, in <module>
    from agenthub.langchains_agent.utils.memory import LongTermMemory
  File "/home/user/OpenDevin/agenthub/langchains_agent/utils/memory.py", line 3, in <module>
    import chromadb
  File "/home/user/venv_devin/lib/python3.10/site-packages/chromadb/__init__.py", line 79, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.
(venv_devin) jwang@jwang-llm:~/OpenDevin$ sqlite3 --version
3.38.2 2022-03-26 13:51:10 d33c709cc0af66bc5b6dc6216eba9f1f0b40960b9ae83694c986fbf4c1d6f08f
```

**Comment by Lanthanum1** [comment]
You can modify the pipfile with python=3.11, see #380
