### ISSUE TITLE
Disable terminal input until its implemented

### ISSUE THREAD

**Issue by penberg** [OpenDevin/OpenDevin#381]
**Describe the bug**

I started up OpenDevin, then attempted to write a command to the terminal, but server crashed because it hit a code path that is not implemented. I was thinking of changing the not implemented error to `await self.send_error()`, but then started to wonder why we even allow users to type commands from the UI in cases where we're not prepared to handle them.

**Steps to Reproduce**
1. Start OpenDevin
2. Attempt to write to the terminal prompt
3.

**Actual behavior**

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/routing.py", line 375, in handle
    await self.app(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/routing.py", line 98, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/starlette/routing.py", line 96, in app
    await func(session)
  File "/Users/penberg/.local/share/virtualenvs/OpenDevin-q_F4dVcV/lib/python3.10/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/Users/penberg/src/penberg/OpenDevin/opendevin/server/listen.py", line 23, in websocket_endpoint
    await session.start_listening()
  File "/Users/penberg/src/penberg/OpenDevin/opendevin/server/session.py", line 72, in start_listening
    raise NotImplementedError
NotImplementedError
```

**Comment by jojeyh** [comment]
The terminal does not currently accept input, there's a draft PR at #371 if you want to check it out.  The session does not maintain state (current working directory) and there's some formatting errors.  I'm working on establishing a stateful session with Docker now, will probably be done soon.

**Comment by enyst** [comment]
This looks solved, user input in the terminal has been disabled a while ago.
