### ISSUE TITLE
Something went wrong: HTTPConnectionPool(host='localhost', port=8000): 

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#384]
Hello, I am getting an error like this.

1. Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86581a9e70>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by rbren** [comment]
@timucindusunur can you share your configuration/env? We need more info here.

**Comment by timucindusunur** [comment]
LLM_API_KEY="sk-"
LLM_MODEL="gpt-3.5-turbo-1106"
LLM_BASE_URL="https://localhost:3000"
LLM_EMBEDDING_MODEL="llama2" # can be "llama2", "openai", "azureopenai", or "local"

**Comment by timucindusunur** [comment]
PLAN:

        🔵 0 Write a bash script that prints 'hello world'


        AGENT ERROR:
        HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/embeddings (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/embeddings (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timuc/OpenDevin/opendevin/controller/agent_controller.py", line 88, in step
    action = self.agent.step(self.state)
  File "/home/timuc/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 122, in step
    self._initialize(state.plan.main_goal)
  File "/home/timuc/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 118, in _initialize
    self._add_event(d)
  File "/home/timuc/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 72, in _add_event
    self.memory.add_event(event)
  File "/home/timuc/OpenDevin/agenthub/langchains_agent/utils/memory.py", line 69, in add_event
    self.index.insert(doc)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/indices/base.py", line 242, in insert
    self.insert_nodes(nodes, **insert_kwargs)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/indices/vector_store/base.py", line 329, in insert_nodes
    self._insert(nodes, **insert_kwargs)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/indices/vector_store/base.py", line 312, in _insert
    self._add_nodes_to_index(self._index_struct, nodes, **insert_kwargs)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/indices/vector_store/base.py", line 233, in _add_nodes_to_index
    nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/indices/vector_store/base.py", line 141, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/indices/utils.py", line 138, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 146, in wrapper
    self.span_drop(id_=id_, bound_args=bound_args, instance=instance, err=e)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 98, in span_drop
    h.span_drop(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/instrumentation/span_handlers/base.py", line 77, in span_drop
    span = self.prepare_to_drop_span(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/instrumentation/span_handlers/null.py", line 71, in prepare_to_drop_span
    raise err
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 144, in wrapper
    result = func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/core/base/embeddings/base.py", line 280, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/embeddings/ollama/base.py", line 64, in _get_text_embeddings
    embeddings = self.get_general_text_embedding(text)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/llama_index/embeddings/ollama/base.py", line 89, in get_general_text_embedding
    response = requests.post(
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/embeddings (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))

        OBSERVATION:
        HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/embeddings (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))
Exited before finishing

**Comment by afan-ai** [comment]
Have you confirmed to see if your local model (on port 3000) is being served as HTTP (or HTTPS)? Perhaps changing the URL to HTTP might work.

**Comment by hadi-nayebi** [comment]
I was getting the same error, with the following .env file:

OPENAI_API_KEY="sk-"
WORKSPACE_DIR="./workspace"
LLM_MODEL="gpt-3.5-turbo"
LLM_EMBEDDING_MODEL="openai"

After, restarting both servers:
1. uvicorn opendevin.server.listen:app --port 3000
2. npm start -- --port 3001

the error stopped.

**Comment by rbren** [comment]
oh good eye @afan-ai ! It's almost definitely not https://localhost--change to http://

**Comment by timucindusunur** [comment]
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


        AGENT ERROR:
        Error condensing thoughts: OpenAIException - Traceback (most recent call last):
          File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 376, in completion
            raise e
          File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 312, in completion
            openai_client = openai(
          File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 98, in __init__
            raise openaiError(
        openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 376, in completion
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 312, in completion
    openai_client = OpenAI(
  File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 990, in completion
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 963, in completion
    response = openai_chat_completions.completion(
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 384, in completion
    raise OpenAIError(status_code=500, message=traceback.format_exc())
litellm.llms.openai.OpenAIError: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 376, in completion
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 312, in completion
    openai_client = OpenAI(
  File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timuc/OpenDevin/agenthub/langchains_agent/utils/monologue.py", line 30, in condense
    resp = llm.completion(messages=messages)
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2807, in wrapper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2705, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 2094, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 8296, in exception_type
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 7082, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: OpenAIException - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 376, in completion
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 312, in completion
    openai_client = openai(
  File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 98, in __init__
    raise openaiError(
openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timuc/OpenDevin/opendevin/controller/agent_controller.py", line 89, in step
    action = self.agent.step(self.state)
  File "/home/timuc/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 124, in step
    self._add_event(prev_action.to_dict())
  File "/home/timuc/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 74, in _add_event
    self.monologue.condense(self.llm)
  File "/home/timuc/OpenDevin/agenthub/langchains_agent/utils/monologue.py", line 35, in condense
    raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: OpenAIException - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 376, in completion
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 312, in completion
    openai_client = openai(
  File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 98, in __init__
    raise openaiError(
openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable


        OBSERVATION:
        Error condensing thoughts: OpenAIException - Traceback (most recent call last):
          File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 376, in completion
            raise e
          File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 312, in completion
            openai_client = openai(
          File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 98, in __init__
            raise openaiError(
        openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

Exited before finishing                        Thanks guys but there is one more problem.

**Comment by timucindusunur** [comment]
INFO:     Started server process [2115]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 43006) - "WebSocket /ws" [accepted]
INFO:     connection open
INFO:     127.0.0.1:43014 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:43026 - "GET /litellm-models HTTP/1.1" 200 OK


==============
STEP 0

        PLAN:

        🔵 0 bana python kodu yaz

Retrying llama_index.embeddings.openai.base.get_embeddings in 0.909895576464711 seconds as it raised APIConnectionError: Connection error..    Thanks guys but there is one more problem.



# This is a template. Run `cp config.toml.template config.toml` to use it.

LLM_API_KEY="sk-"
LLM_MODEL="LLM_MODEL="gpt-3.5-turbo-1106"
LLM_BASE_URL="http://localhost:3000"
LLM_EMBEDDING_MODEL="openai" # can be "llama2", "openai", "azureopenai", or "local"



WORKSPACE_DIR="./workspace"

**Comment by timucindusunur** [comment]
Retrying llama_index.embeddings.openai.base.get_embeddings in 0.7864436057007745 seconds as it raised APIConnectionError: Connection error..   


Finally I get an error like this.

LLM_API_KEY="sk-"
LLM_MODEL="gpt-3.5-turbo"
LLM_BASE_URL="http://localhost:3000"
LLM_EMBEDDING_MODEL="openai"  # can be "llama2", "openai", "azureopenai", or "local"
WORKSPACE_DIR="./workspace"

**Comment by rbren** [comment]
Oh it looks like you're trying to use openai on localhost? You probably wan to unset LLM_BASE_URL, unless you're running some kind of proxy to openai

**Comment by timucindusunur** [comment]
Oops. Something went wrong: Error condensing thoughts: OpenAIException - Traceback (most recent call last): File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/litellm/llms/openai.py", line 376, in completion raise e File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/litellm/llms/openai.py", line 312, in completion openai_client = openai( File "/root/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.10/site-packages/openai/_client.py", line 98, in __init__ raise openaiError( openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable 


Actually I use these settings, I don't understand what it has to do with Openai.


# This is a template. Run `cp config.toml.template config.toml` to use it.
ANTHROPIC_API_KEY="sk"
model="anthropic/claude-3-sonnet-20240229"
LLM_BASE_URL="http://localhost:3000"
WORKSPACE_DIR="./workspace"

**Comment by rbren** [comment]
> model="anthropic/claude-3-sonnet-20240229"


This should be `LLM_MODEL="anthropic/claude-3-sonnet-20240229"`

**Comment by rbren** [comment]
Going to close this one. Feel free to open a new issue if you're still having trouble!

**Comment by enyst** [comment]
@pratyushdev-codes I also see in your log a vector dimension error, like when you try to use the same store for 3k dimensions and then for 700 dimensions. You may want to check that.

If you still experience issues, please open a new issue.
