### ISSUE TITLE
Fix issue with torch dependency

### ISSUE THREAD

**Issue by ItsDevMonk** [OpenDevin/OpenDevin#437]
I tried to run this in my machine (without Graphics card). I got the below error.
```
(OpenDevin) krish@KrishServer:/mnt/c/Users/Krish/Desktop/GD/OpenDevin$ uvicorn opendevin.server.listen:app --port 3000
Traceback (most recent call last):
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Krish/Desktop/GD/OpenDevin/opendevin/server/listen.py", line 4, in <module>
    import agenthub  # noqa F401 (we import this to get the agents registered)
  File "/mnt/c/Users/Krish/Desktop/GD/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import langchains_agent # noqa: E402
  File "/mnt/c/Users/Krish/Desktop/GD/OpenDevin/agenthub/langchains_agent/__init__.py", line 2, in <module>
    from .langchains_agent import LangchainsAgent
  File "/mnt/c/Users/Krish/Desktop/GD/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 8, in <module>
    from agenthub.langchains_agent.utils.memory import LongTermMemory
  File "/mnt/c/Users/Krish/Desktop/GD/OpenDevin/agenthub/langchains_agent/utils/memory.py", line 2, in <module>
    from llama_index.core import Document
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/indices/base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/ingestion/pipeline.py", line 31, in <module>
    from llama_index.core.ingestion.api_utils import get_client
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/ingestion/api_utils.py", line 23, in <module>
    from llama_index.core.ingestion.transformations import (
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/ingestion/transformations.py", line 267, in <module>
    ConfigurableTransformations = build_configurable_transformation_enum()
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/core/ingestion/transformations.py", line 247, in build_configurable_transformation_enum
    from llama_index.embeddings.huggingface import (
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/embeddings/huggingface/__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/llama_index/embeddings/huggingface/base.py", line 27, in <module>
    from sentence_transformers import SentenceTransformer
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/torch/__init__.py", line 197, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages/torch/__init__.py", line 162, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['', '/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/bin', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/krish/.local/share/virtualenvs/OpenDevin-LodNhC5G/lib/python3.10/site-packages', '/mnt/c/Users/Krish/Desktop/GD/OpenDevin']
```

It would be better if there is any option to use CPU only.

**Comment by rbren** [comment]
This is a strange error. We're not reliant on GPUs at all, but it seems like we're importing torch for some reason?

**Comment by rbren** [comment]
See some workaround here: https://stackoverflow.com/questions/76327419/valueerror-libcublas-so-0-9-not-found-in-the-system-path
