### ISSUE TITLE
Crash agent while doing its work

### ISSUE THREAD

**Issue by jabbor** [OpenDevin/OpenDevin#471]
**Describe the bug**
When creating a python program, this happens:

       AGENT ERROR:
        Error condensing thoughts: Invalid \escape: line 2 column 7 (char 9)
Traceback (most recent call last):
  File "D:\OpenDevin\agenthub\langchains_agent\utils\monologue.py", line 32, in condense
    self.thoughts = prompts.parse_summary_response(summary_resp)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenDevin\agenthub\langchains_agent\utils\prompts.py", line 143, in parse_summary_response
    parsed = json.loads(response)
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenDevin\agenthub\langchains_agent\utils\json.py", line 11, in loads
    return json.loads(s, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 7 (char 9)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OpenDevin\opendevin\controller\agent_controller.py", line 89, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenDevin\agenthub\langchains_agent\langchains_agent.py", line 124, in step
    self._add_event(prev_action.to_dict())
  File "D:\OpenDevin\agenthub\langchains_agent\langchains_agent.py", line 74, in _add_event
    self.monologue.condense(self.llm)
  File "D:\OpenDevin\agenthub\langchains_agent\utils\monologue.py", line 35, in condense
    raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: Invalid \escape: line 2 column 7 (char 9)

        OBSERVATION:
        Error condensing thoughts: Invalid \escape: line 2 column 7 (char 9)
Error sending data to client
INFO:     connection closed
Error sending data to client
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)

**Steps to Reproduce**
1.
2.
3.

**Expected behavior**

**Actual behavior**

**Additional context**
<img width="722" alt="opendevin_screen" src="https://github.com/OpenDevin/OpenDevin/assets/50017850/5fd0f2a4-705e-40d8-85ec-e32ec66216bb">

**Comment by markusza** [comment]
Adding to the issue, might be related.

```
        AGENT ERROR:
        Unterminated string starting at: line 5 column 17 (char 93)
Traceback (most recent call last):
  File "/home/markus/OpenDevin/opendevin/controller/agent_controller.py", line 89, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markus/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 137, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markus/OpenDevin/agenthub/langchains_agent/utils/prompts.py", line 136, in parse_action_response
    action_dict = json.loads(response)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/markus/OpenDevin/agenthub/langchains_agent/utils/json.py", line 11, in loads
    return json.loads(s, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 5 column 17 (char 93)

        OBSERVATION:
        Unterminated string starting at: line 5 column 17 (char 93)
Error sending data to client
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
INFO:     connection closed
```

Crashes mid work.
Running Gemini-pro

**Comment by rbren** [comment]
This might help: https://github.com/OpenDevin/OpenDevin/pull/444

**Comment by jabbor** [comment]
I ran a git pull, and now it's working! Thx!
