### ISSUE TITLE
Error with its thought condensing

### ISSUE THREAD

**Issue by Gsingh225** [OpenDevin/OpenDevin#478]
**Describe the bug**
```
Oops. Something went wrong: Error condensing thoughts: local variable 'error_str' referenced before assignment
```
**Steps to Reproduce**
1. set model to Gemini
2. run normally

**Error from one of the attempts, it spams them**

```==============
STEP 65

        PLAN:

        🔵 0 create a calculator website thats stylish and has css in py flask.


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/Users/censoredt/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 5524, in get_llm_provider
    model = model.split("/", 1)[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/censored/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/main.py", line 642, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
  File "/Users/cen/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 5643, in get_llm_provider
    content=error_str,
UnboundLocalError: local variable 'error_str' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cen/devin/OpenDevin/agenthub/langchains_agent/utils/monologue.py", line 31, in condense
    resp = llm.completion(messages=messages)
  File "/Users/cdn/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 2819, in wrapper
    raise e
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 2717, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/main.py", line 2094, in completion
    raise exception_type(
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 8311, in exception_type
    raise e
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 8286, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: local variable 'error_str' referenced before assignment

        AGENT ERROR:
        Error condensing thoughts: local variable 'error_str' referenced before assignment
Traceback (most recent call last):
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 5524, in get_llm_provider
    model = model.split("/", 1)[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/main.py", line 642, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 5643, in get_llm_provider
    content=error_str,
UnboundLocalError: local variable 'error_str' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ddd/devin/OpenDevin/agenthub/langchains_agent/utils/monologue.py", line 31, in condense
    resp = llm.completion(messages=messages)
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 2819, in wrapper
    raise e
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 2717, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/main.py", line 2094, in completion
    raise exception_type(
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 8311, in exception_type
    raise e
  File "/Users/ddd/.local/share/virtualenvs/OpenDevin-bE5tbBnG/lib/python3.10/site-packages/litellm/utils.py", line 8286, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: local variable 'error_str' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ddd/devin/OpenDevin/opendevin/controller/agent_controller.py", line 89, in step
    action = self.agent.step(self.state)
  File "/Users/ddd/devin/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 124, in step
    self._add_event(prev_action.to_dict())
  File "/Users/dddd/devin/OpenDevin/agenthub/langchains_agent/langchains_agent.py", line 74, in _add_event
    self.monologue.condense(self.llm)
  File "/Users/ddd/devin/OpenDevin/agenthub/langchains_agent/utils/monologue.py", line 36, in condense
    raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: local variable 'error_str' referenced before assignment

        OBSERVATION:
        Error condensing thoughts: local variable 'error_str' referenced before assignment


==============
STEP 66```

**Comment by jojeyh** [comment]
@Gsingh225 what is the specific string you used for LLM_MODEL ? It looks like you didn't set it correctly

**Comment by Gsingh225** [comment]
> @Gsingh225 what is the specific string you used for LLM_MODEL ? It looks like you didn't set it correctly

HI! I used gemini, just the name. What was it supposed to be? Thanks.

**Comment by Gsingh225** [comment]
The LLM_MODEL string was set to "gemini", the correct one was "gemini/gemini-pro"

**Comment by jojeyh** [comment]
@Gsingh225 yup! for future reference the model string should match what is used is LiteLLM
