### ISSUE TITLE
OPENAI Key issue when starting front and backend

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#518]
Workspace directory /mnt/c/Users/pierr/OpenDevinProjects does not exist. Creating it...
Task exception was never retrieved
future: <Task finished name='create controller' coro=<Session.create_controller() done, defined at /mnt/c/Users/pierr/OpenDevin/opendevin/server/session.py:106> exception=OpenAIError('The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable')>
Traceback (most recent call last):
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/session.py", line 134, in create_controller
    llm = LLM(model=model, api_key=api_key, base_url=api_base)
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/llm/llm.py", line 36, in __init__
    self._router = Router(
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/litellm/router.py", line 196, in __init__
    self.set_model_list(model_list)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/litellm/router.py", line 2099, in set_model_list
    self.set_client(model=model)
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/litellm/router.py", line 1952, in set_client
    _client = openai.AsyncOpenAI(  # type: ignore
  File "/home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/lib/python3.10/site-packages/openai/_client.py", line 296, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by jojeyh** [comment]
@PierrunoYT  did you set your api key in the `config.toml` per the instructions?

**Comment by PierrunoYT** [comment]
> @PierrunoYT did you set your api key in the `config.toml` per the instructions?

Actually yes

**Comment by jojeyh** [comment]
Can you post `config.toml`? (Don't forget to remove actual api key!)

**Comment by PierrunoYT** [comment]
> Can you post `config.toml`? (Don't forget to remove actual api key!)

![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/7aa96def-4697-4089-8574-c68704fa3502)

**Comment by jojeyh** [comment]
I believe only `LLM_API_KEY` works now.  The `OPENAI_API_KEY` was used previously.

**Comment by PierrunoYT** [comment]
> I believe only `LLM_API_KEY` works now. The `OPENAI_API_KEY` was used previously.

True thx
