### ISSUE TITLE
modelNotFound Error 

### ISSUE THREAD

**Issue by alphaabhi** [OpenDevin/OpenDevin#528]
** I am getting model not found 404 error even though open ai key has been configured correctly with a gpt4 plan as well**

**Steps to Reproduce**
1. 
2.
3.

**Expected behavior**

**  response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\litellm\utils.py", line 2819, in wrapper
    raise e
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\litellm\utils.py", line 2717, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\litellm\main.py", line 2094, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\litellm\utils.py", line 8311, in exception_type
    raise e
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\litellm\utils.py", line 7064, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model `gpt-4-0125-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
Client websocket disconnected (1012, None)
INFO:     Waiting for application shutdown.

        OBSERVATION:
        OpenAIException - Error code: 404 - {'error': {'message': 'The model `gpt-4-0125-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
Error sending data to client
INFO:     connection closed
INFO:     Application shutdown complete.
INFO:     Finished server process [17288]

==============
STEP 15

        PLAN:

        🔵 0 stop

Aborted!
Exception ignored in atexit callback: <bound method DockerInteractive.cleanup of <opendevin.sandbox.sandbox.DockerInteractive object at 0x000001220D633920>>
Traceback (most recent call last):
  File "C:\opendevin\OpenDevin\opendevin\sandbox\sandbox.py", line 279, in cleanup
    self.container.remove(force=True)
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\models\containers.py", line 364, in remove
    return self.client.api.remove_container(self.id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\utils\decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\api\container.py", line 1036, in remove_container
    self._raise_for_status(res)
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\api\client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\errors.py", line 39, in create_api_error_from_http_exception  
    raise cls(e, response=response, explanation=explanation) from e    
docker.errors.NotFound: 404 Client Error for http+docker://localnpipe/v1.44/containers/9c04d5a3f7f52e9b92d94f13d8f4c62e1f1cad4dabc0eecb95e8dd609fd4e24d?v=False&link=False&force=True: Not Found ("No such container: 9c04d5a3f7f52e9b92d94f13d8f4c62e1f1cad4dabc0eecb95e8dd609fd4e24d")    
Exception ignored in atexit callback: <bound method DockerInteractive.cleanup of <opendevin.sandbox.sandbox.DockerInteractive object at 0x000001220D673200>>
Traceback (most recent call last):
  File "C:\opendevin\OpenDevin\opendevin\sandbox\sandbox.py", line 279, in cleanup
    self.container.remove(force=True)
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\models\containers.py", line 364, in remove
    return self.client.api.remove_container(self.id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\utils\decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\api\container.py", line 1036, in remove_container
    self._raise_for_status(res)
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\api\client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\high9\.virtualenvs\opendevin-jFsLOa_j\Lib\site-packages\docker\errors.py", line 39, in create_api_error_from_http_exception  
    raise cls(e, response=response, explanation=explanation) from e    
docker.errors.NotFound: 404 Client Error for http+docker://localnpipe/v1.44/containers/97219b7639963696eb661ae98382758d4e7592186732c66d6530b73ae14c9ed9?v=False&link=False&force=True: Not Found ("No such container: 97219b7639963696eb661ae98382758d4e7592186732c66d6530b73ae14c9ed9")    
Exception ignored in atexit callback: <bound method DockerInteractive.cleanup of <opendevin.sandbox.sandbox.DockerInteractive object at 0x000001220D7BF6B0>>
Traceback (most recent call last):
  File "C:\opendevin\OpenDevin\opendevin\sandbox\sandbox.py", line 279, in cleanup
    self.container.remove(force=T**

**Additional context**

![image](https://github.com/OpenDevin/OpenDevin/assets/39146300/1b942a28-3ba3-4e2a-8840-c7ddcad626d7)

**Comment by rbren** [comment]
What happens if you select a different OpenAI model?

I had thought gpt-4 was widely available now, but maybe not?

**Comment by enyst** [comment]
GPT-4 is not available via API for accounts that have simply a subscription. OpenAI calls that "free tier" and it gives access to 3.5.

Only starting with the next tier they give access to this one. That next tier means adding a credit card on the account and I think also charging it once.

**Comment by AbhisekOmkar** [comment]
You need to use subscription open api key for this

**Comment by yufansong** [comment]
Close it for now. If new problem happened, feel free to open it.

**Comment by rahulgowda223** [comment]
I am also facing the same issue
