### ISSUE TITLE
BackEnd server run error

### ISSUE THREAD

**Issue by wesamdev** [OpenDevin/OpenDevin#573]
#### Describe the bug
there is problem while run backend server
#### Setup and configuration
**Current version**:

```bash
commit 16fe8303e7233e45d25e3fe9ed5d504f34d97ebd (HEAD -> main, origin/main, origin/HEAD)
Author: Xingyao Wang <xingyao6@illinois.edu>
Date:   Tue Apr 2 19:21:30 2024 +0800

    support disable color printing via environment variable in config.toml (#545)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY=""
LLM_MODEL="gpt-3.5-turbo-0125"
WORKSPACE_DIR="./workspace"

```

**Commands I ran to install and run OpenDevin**:
```
git clone opendevin
cd OpenDevin
python3 -m venv env
source env/bin/activate
pip install pipenv
pipenv install -v
make setup-config
```

**Logs, error messages, and screenshots**:
 i get this error when `make run`
https://prnt.sc/swt32v0ZJRMj
and if i run only backend server this error popup on console and backend server crashes `make start-backend`
```sh
(env) wesamdev@wesamhost:~/OpenDevin $ make start-backend
Starting backend...
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Traceback (most recent call last):
  File "/home/wesamdev/OpenDevin/env/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wesamdev/OpenDevin/opendevin/server/listen.py", line 4, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/agenthub/monologue_agent/__init__.py", line 2, in <module>
    from .agent import MonologueAgent
  File "/home/wesamdev/OpenDevin/agenthub/monologue_agent/agent.py", line 28, in <module>
    from agenthub.monologue_agent.utils.memory import LongTermMemory
  File "/home/wesamdev/OpenDevin/agenthub/monologue_agent/utils/memory.py", line 37, in <module>
    embed_model = HuggingFaceEmbedding(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/llama_index/embeddings/huggingface/base.py", line 86, in __init__
    self._model = SentenceTransformer(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 191, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 1246, in _load_sbert_model
    module = module_class.load(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wesamdev/OpenDevin/env/lib/python3.11/site-packages/sentence_transformers/models/Pooling.py", line 227, in load
    with open(os.path.join(input_path, "config.json")) as fIn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/llama_index/models--BAAI--bge-small-en-v1.5/snapshots/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling/config.json'
make: *** [Makefile:24: start-backend] Error 1
```
 
#### Additional Context
Please help!
~~~~

**Comment by wesamdev** [comment]
i found  fix : `wget https://huggingface.co/BAAI/bge-small-en-v1.5/raw/main/1_Pooling/config.json -P /tmp/llama_index/models--BAAI--bge-small-en-v1.5/snapshots/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling/
`
thats should fix the problem. #561

**Comment by enyst** [comment]
Thank you for sharing the solution! <3
This has started happening for some reason recently.

**Comment by wesamdev** [comment]
> Thank you for sharing the solution! <3 This has started happening for some reason recently.

every reboot we do this 5c38ec7c405ec4b44b94cc5a9bb96e735b38267a changes

**Comment by huybery** [comment]
I suspect that some sort of network problem is preventing the files from being pulled from Huggingface.

**Comment by rbren** [comment]
I think we could get rid of it temporarily, but at some point we are going to need embeddings to drive a vector database...
