### ISSUE TITLE
api timeout error in planning stage

### ISSUE THREAD

**Issue by JustinLin610** [OpenDevin/OpenDevin#581]
After running `make start-backend` and `make start-front-end`, I tested with a simple prompt "hi" but the server got stuck and after waiting a long time it seems to be an API timeout error:

It first stucks at

```console
==============
STEP 0

PLAN:
hi
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
```

Then it reports API timeout error:

```console
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/junyang.ljy/Desktop/code/OpenDevin/opendevin/controller/agent_controller.py", line 110, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junyang.ljy/Desktop/code/OpenDevin/agenthub/monologue_agent/agent.py", line 162, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/router.py", line 328, in completion
    raise e
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/router.py", line 325, in completion
    response = self.function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/router.py", line 1419, in function_with_fallbacks
    raise original_exception
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/router.py", line 1344, in function_with_fallbacks
    response = self.function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/router.py", line 1496, in function_with_retries
    raise e
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/router.py", line 1462, in function_with_retries
    response = original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/router.py", line 386, in _completion
    raise e
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/router.py", line 369, in _completion
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/utils.py", line 2852, in wrapper
    raise e
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/utils.py", line 2750, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/main.py", line 2093, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/utils.py", line 8344, in exception_type
    raise e
  File "/Users/junyang.ljy/.local/share/virtualenvs/OpenDevin-_HYa44fQ/lib/python3.11/site-packages/litellm/utils.py", line 7054, in exception_type
    raise Timeout(
litellm.exceptions.Timeout: Request timed out.

OBSERVATION:
Request timed out.
```

Yet everything actually works fine with my openai api service and also using litellm alone.

**Comment by rbren** [comment]
@JustinLin610 can you open a new issue, and fill out the bug template. That will give us the info we need to debug.
