### ISSUE TITLE
Issue starting backend

### ISSUE THREAD

**Issue by jokosantosi** [OpenDevin/OpenDevin#582]
#### Describe the bug

after i installing every thing and running `make start-backend` its show this error. Im using ChatGPT, gpt4-0125-preview model
this the error

**Logs, error messages, and screenshots**:
```bash
Starting backend...
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/opendevin/opendevin/server/listen.py", line 4, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "/home/user/opendevin/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/opendevin/agenthub/monologue_agent/__init__.py", line 2, in <module>
    from .agent import MonologueAgent
  File "/home/user/opendevin/agenthub/monologue_agent/agent.py", line 28, in <module>
    from agenthub.monologue_agent.utils.memory import LongTermMemory
  File "/home/user/opendevin/agenthub/monologue_agent/utils/memory.py", line 37, in <module>
    embed_model = HuggingFaceEmbedding(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/llama_index/embeddings/huggingface/base.py", line 86, in __init__
    self._model = SentenceTransformer(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 191, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 1246, in _load_sbert_model
    module = module_class.load(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/opendevin-IWmZXoSL/lib/python3.11/site-packages/sentence_transformers/models/Pooling.py", line 227, in load
    with open(os.path.join(input_path, "config.json")) as fIn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/llama_index/models--BAAI--bge-small-en-v1.5/snapshots/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling/config.json'
make: *** [Makefile:24: start-backend] Error 1
```

and this if i running `make run`, vite is running but backend isn't
<img src="https://github.com/OpenDevin/OpenDevin/assets/92248772/49319002-8792-4f6e-9607-6102a7a8a15a">
<img src="https://github.com/OpenDevin/OpenDevin/assets/92248772/54af3054-5338-4c4d-8553-730081a774c1" >

**Comment by JustinLin610** [comment]
Solution in #573 #583

**Comment by jokosantosi** [comment]
> Solution in #573 #583

its fixed thanks the backend is running so well, but why if i running `make run` its showing this error now

```bash
Running the app...

> opendevin-frontend@0.1.0 start
> vite --port 3001

'\\wsl.localhost\Ubuntu\home\user\opendevin\frontend'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'vite' is not recognized as an internal or external command,
operable program or batch file.
make: *** [Makefile:36: run] Error 1
```

**Comment by jokosantosi** [comment]
> I advise u'd better use `make start-backend` and `make start-frontend` separately

oh thanks it works for me, but i dont know why after run this `wget https://huggingface.co/BAAI/bge-small-en-v1.5/raw/main/1_Pooling/config.json -P /tmp/llama_index/models--BAAI--bge-small-en-v1.5/snapshots/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling/ ` my node and npm cant run, but i can installing node again using `nvm install node` and this is works well

thankyou
