### ISSUE TITLE
Unable to find config.json file

### ISSUE THREAD

**Issue by rajchauhan143** [OpenDevin/OpenDevin#583]
Starting backend...
Traceback (most recent call last):
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/od2/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/od2/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/od2/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/rachavan/Desktop/OpenDevin/opendevin/server/listen.py", line 4, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "/Users/rachavan/Desktop/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/Desktop/OpenDevin/agenthub/monologue_agent/__init__.py", line 2, in <module>
    from .agent import MonologueAgent
  File "/Users/rachavan/Desktop/OpenDevin/agenthub/monologue_agent/agent.py", line 28, in <module>
    from agenthub.monologue_agent.utils.memory import LongTermMemory
  File "/Users/rachavan/Desktop/OpenDevin/agenthub/monologue_agent/utils/memory.py", line 37, in <module>
    embed_model = HuggingFaceEmbedding(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/llama_index/embeddings/huggingface/base.py", line 86, in __init__
    self._model = SentenceTransformer(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 191, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 1246, in _load_sbert_model
    module = module_class.load(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachavan/.local/share/virtualenvs/OpenDevin-e_m2vP2T/lib/python3.11/site-packages/sentence_transformers/models/Pooling.py", line 227, in load
    with open(os.path.join(input_path, "config.json")) as fIn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rachavan/Library/Caches/llama_index/models--BAAI--bge-small-en-v1.5/snapshots/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling/config.json'
make: *** [start-backend] Error 1
(od2) rachavan@IN-RACHAVAN-M2 opendevin %

**Comment by JustinLin610** [comment]
#573 this problem happens a lot with llama_index. I advise you to load embedding in llama_index and see if it works. or you can just use the solution in the mentioned issue to use wget to get the config.json

**Comment by rbren** [comment]
Closing in favor of https://github.com/OpenDevin/OpenDevin/issues/438
