### ISSUE TITLE
FileWriteAction doesn't handle exception

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#594]
```
STEP 23
	
	AGENT ERROR:
	FileWriteAction.__init__() got an unexpected keyword argument 'content'
Traceback (most recent call last):
  File "/home/user/OpenDevin/opendevin/controller/__init__.py", line 85, in step
    action = self.agent.step(state)
  File "/home/user/OpenDevin/agenthub/langchains_agent/__init__.py", line 174, in step
    action = prompts.parse_action_response(action_resp)
  File "/home/user/OpenDevin/agenthub/langchains_agent/utils/prompts.py", line 172, in parse_action_response
    action = ACTION_TYPE_TO_CLASS[action_dict["action"]](**action_dict["args"])
TypeError: FileWriteAction.__init__() got an unexpected keyword argument 'content'
	
	OBSERVATION:
	FileWriteAction.__init__() got an unexpected keyword argument 'content'


```

by running 

```
PYTHONPATH=`pwd`:`pwd`/workspace  python opendevin/main.py -d ./workspace/ -i 100 -t 'Review the following wassersteinDistance function change in term of correctness, efficiency, handle of corner cases, readability, and python style.

previous code:
===
import math

def wassersteinDistance(x: list, y: list):
    """Wasserstein distance between two equal length float lists. Each list contains probability distribution for a fixed number of bin; that is x[0] is the probability of the first bin and x[1] is the probability of the second bin. 
    Args:
        x: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
        y: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
    """
    x_len = len(x)
    y_len = len(y)
    
    if x_len != y_len or x_len < 1:
        return float(math.inf)
    
    lastDistance = 0.0
    totalDistance = 0.0
    for i in range(x_len):
      currentDistance = (x[i] + lastDistance) - y[i]
      totalDistance += abs(currentDistance)
      lastDistance = currentDistance

    return totalDistance
===

new code:
===
import math

def wassersteinDistance(x: list, y: list):
    """Wasserstein distance between two equal length float lists. Each list contains probability distribution for a fixed number of bin; that is x[0] is the probability of the first bin and x[1] is the probability of the second bin. 
    Args:
        x: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
        y: a float list where each value can range from 0.0 to 1.0, inclusive, and all numbers add up to exactly 1.0
    """
    if not x or not y or len(x) != len(y):
        return float(math.inf)
    
    x_sorted, y_sorted = sorted(x), sorted(y)
    
    totalDistance = sum(abs(xi - yi) for xi, yi in zip(x_sorted, y_sorted))

    return totalDistance
===

Here are corect results of wassersteinDistance: 
wassersteinDistance([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],[0.15, 0.05, 0.1, 0.1, 0.1, 0.1, 0.1, 0.28, 0.01, 0.01]) = 0.32000000000000006
wassersteinDistance([0.1, 0.9],[0.15, 0.15, 0.7]) = float(math.inf)
wassersteinDistance([0.1, 0.5, 0.4], [0.4, 0.1, 0.5]) = 0.4
'
```

**Comment by enyst** [comment]
I think this was fixed in the past few days, please update your git repo to get the fixes.

**Comment by josephykwang** [comment]
with the latest with python 3.11,

get 

```
Traceback (most recent call last):
  File "/home/user/venv_devin/lib/python3.11/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv_devin/lib/python3.11/site-packages/toml/decoder.py", line 781, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/OpenDevin/opendevin/main.py", line 6, in <module>
    import agenthub  # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "/home/user/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/OpenDevin/agenthub/monologue_agent/__init__.py", line 1, in <module>
    from opendevin.agent import Agent
  File "/home/user/OpenDevin/opendevin/agent.py", line 7, in <module>
    from opendevin.llm.llm import LLM
  File "/home/user/OpenDevin/opendevin/llm/llm.py", line 7, in <module>
    from opendevin import config
  File "/home/user/OpenDevin/opendevin/config.py", line 13, in <module>
    config = toml.loads(config_str)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv_devin/lib/python3.11/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Duplicate keys! (line 2 column 1 char 32)
```

**Comment by rbren** [comment]
@josephykwang can you reopen this and fill out the bug template? That way we know what version you're working with and what your settings are.
