### ISSUE TITLE
No agent class registered under 'LangschainAgent'

### ISSUE THREAD

**Issue by jojeyh** [OpenDevin/OpenDevin#600]
#### Describe the bug
Agent class is not registered on startup.

#### Setup and configuration
**Current version**:
```bash
commit 22a9a28e46f86488d8756db3c074ee35403ba740 (HEAD -> main, upstream/main, origin/main, origin/HEAD, files-endpoints)
Author: Robert Brennan <accounts@rbren.io>
Date:   Tue Apr 2 10:02:09 2024 -0400

    Update intro message (#569)

```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```
`config.toml` empty, defaults to OpenAI model, correct `LLM_API_KEY` in env

**My model and agent** (you can see these settings in the UI):
* Model: default
* Agent: Langchain

**Commands I ran to install and run OpenDevin**:
Setup as per instructions

**Steps to Reproduce**:
1.  Run backend/frontend as per instructions

**Logs, error messages, and screenshots**:
```
Traceback (most recent call last):
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/routing.py", line 375, in handle
    await self.app(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/routing.py", line 98, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/starlette/routing.py", line 96, in app
    await func(session)
  File "/home/anon/.local/share/virtualenvs/OpenDevin-rPYAfP2Q/lib/python3.10/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/home/anon/OpenDevin/opendevin/server/listen.py", line 24, in websocket_endpoint
    await session.start_listening()
  File "/home/anon/OpenDevin/opendevin/server/session.py", line 88, in start_listening
    await self.create_controller(data)
  File "/home/anon/OpenDevin/opendevin/server/session.py", line 137, in create_controller
    AgentCls = Agent.get_cls(agent_cls)
  File "/home/anon/OpenDevin/opendevin/agent.py", line 90, in get_cls
    raise ValueError(f"No agent class registered under '{name}'.")
ValueError: No agent class registered under 'LangchainsAgent'.
```

**Comment by enyst** [comment]
LangchainsAgent has been renamed to MonologueAgent yesterday in https://github.com/OpenDevin/OpenDevin/commit/3e6508b7f16d8120c5085bb185c39d2b73bf4ab1 

If I search through the repo, I find no remaining occurrence. So it looks like there's still something outdated in your setup? I think agents are referenced in FE now, so maybe a rebuild of FE.

**Comment by jojeyh** [comment]
@enyst  Didn't see the new setup instructions with Makefile. Got another error on build but will open another PR. Thx :)
