### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by Toasterme** [OpenDevin/OpenDevin#630]
When i do the make run i have those error 
```
Starting backend...
Starting frontend...

> opendevin-frontend@0.1.0 start
> vite "--port" "3001"

file:///home/xxxx/OpenDevin/frontend/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
make[1]: *** [Makefile:30: start-frontend] Error 1
make[1]: Leaving directory '/home/xxxx/OpenDevin'
make: *** [Makefile:39: run] Error 2
```

#### Setup and configuration
**Current version**:

```commit d397a200bfa6f5706ab2ff615eed99bddfb46c4f (HEAD -> main, origin/main, origin/HEAD)
Author: Jim Su <jimsu@protonmail.com>
Date:   Tue Apr 2 21:25:16 2024 -0400

    Add playwright to pipenv (#625)

    * Add playwright to Pipfile
```

**My config.toml and environment vars** (be sure to redact API keys):
```LLM_API_KEY="none"
LLM_MODEL="gpt-4-0125-preview"
WORKSPACE_DIR="./workspace"
LLM_BASE_URL="http://192.168.0.53:1234/v1/"
```

**My model and agent** (you can see these settings in the UI):
* Model: NousResearch/Hermes-2-Pro-Mistral-7B-GGUF/Hermes-2-Pro-Mistral-7B.Q8_0.gguf
* Agent: LM Studio

**Commands I ran to install and run OpenDevin**:
```  149  make
  150  make build
  151  make setup-config
  152  ls
  153  vi config.toml
  154  make run
```

**Comment by Toasterme** [comment]
Problem with NPM, solved with : 
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh |bash
```

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```
```
nvm install 16
nvm use 16
```
Then the make run works (but that is another story...)

**Comment by Toasterme** [comment]
npm problem, maybe this should be in the readme to install NPM ?
