### ISSUE TITLE
make run - (No agent class registered under '{name}

### ISSUE THREAD

**Issue by azmodeuz** [OpenDevin/OpenDevin#636]
**Logs, error messages, and screenshots**:

>root@DESKTOP-7H4KC7C:/home/matt/OpenDevin# make run
Running the app...
make[1]: Entering directory '/home/matt/OpenDevin'
Starting backend...
make[1]: Entering directory '/home/matt/OpenDevin'
Starting frontend...
opendevin-frontend@0.1.0 start
vite --port 3001
VITE v5.2.7  ready in 248 ms
➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
INFO:     Started server process [9252]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     127.0.0.1:51742 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51750 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:51758 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51772 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 51788) - "WebSocket /ws" [accepted]
INFO:     connection open
>>ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/root/.local/share/virtualenvs/OpenDevin-Z0Y6cbJO/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/home/matt/OpenDevin/opendevin/server/listen.py", line 24, in websocket_endpoint
    await session.start_listening()
  File "/home/matt/OpenDevin/opendevin/server/session.py", line 88, in start_listening
    await self.create_controller(data)
  File "/home/matt/OpenDevin/opendevin/server/session.py", line 135, in create_controller
    AgentCls = Agent.get_cls(agent_cls)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/OpenDevin/opendevin/agent.py", line 90, in get_cls
    raise ValueError(f"No agent class registered under '{name}'.")
ValueError: No agent class registered under 'LangchainsAgent'.
INFO:     connection closed
#### SYSTEM INFO

Python 3.11.8
Docker version 25.0.3, build 4debf41
NodeJs - v21.7.1
WSL - Ubuntu 22.04.3 LTS

**Comment by enyst** [comment]
"LangchainsAgent" has been renamed to MonologueAgent two days ago, and nothing in the project should reference it anymore. So that error looks like your project isn't updated.

Can you try to update everything you're running, git pull, and perhaps make sure to rebuild frontend too, npm install, and then start backend and frontend separately.

**Comment by azmodeuz** [comment]
> "LangchainsAgent" has been renamed to MonologueAgent two days ago, and nothing in the project should reference it anymore. So that error looks like your project isn't updated.
> 
> Can you try to update everything you're running, git pull, and perhaps make sure to rebuild frontend too, npm install, and then start backend and frontend separately.

Thank you, I ended up deleting the old opendevin and cloning a new one, npm install on front end, back to opendevin, rand the backend and front end separately and its working fine no errors now... thanks a bunch.
