### ISSUE TITLE
Can someone please explain to me how to install opendevin using windows WSL (ubuntu) because i've been 3 hours trying and the only thing i got as a result was a headache

### ISSUE THREAD

**Issue by Jaitwo** [OpenDevin/OpenDevin#651]
Please someone can explain how to install it like with detail because i don't know how to install it and each tutorial gives a different way that at the end ends with an error

**Comment by Jaitwo** [comment]
> This

???

**Comment by iFurySt** [comment]
can you write what the problems you met? or just post the errors you faced.

**Comment by Jaitwo** [comment]
> can you write what the problems you met? or just post the errors you faced.

i don't really know how to install it, could you help me?

**Comment by Zeus9820** [comment]
![Uploading image.png…]()
I am getting this error

**Comment by neubig** [comment]
@jaslogic1 , thank you for the report, I have created a new issue #655 that we can track separately.

And thank you everyone for the comments on Windows install. If you have the same issue as @jaslogic1 , could you please upvote it or comment there in #655? If you have a different issue, could you please create an issue with detail of the error message?

I am going to close this issue because we'll need more detail in order to resolve it.

And everyone, I understand that the instructions for OpenDevin keep changing, this is a rapidly developing OSS project that just started about two weeks ago, so hopefully things will be stabilizing soon! We welcome PRs to help out with that.

**Comment by Jaitwo** [comment]
Can someone give me clear instructions on how to install this please? im new in this things and i want to try this out but idk how to use the command "make" to install it

**Comment by Zeus9820** [comment]
make run
Running the app...
make[1]: Entering directory '/home/zeus/workspace/devin/OpenDevin'
Starting backend...
make[1]: Entering directory '/home/zeus/workspace/devin/OpenDevin'
Starting frontend...
make[1]: python: No such file or directory
make[1]: *** [Makefile:26: start-backend] Error 127
make[1]: Leaving directory '/home/zeus/workspace/devin/OpenDevin'

> opendevin-frontend@0.1.0 start
> vite

/mnt/c/Users/User/AppData/Roaming/npm/node_modules/vite/node_modules/rollup/dist/native.js:89
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/mnt/c/Users/User/AppData/Roaming/npm/node_modules/vite/node_modules/rollup/dist/native.js:89:9)
    at Object.<anonymous> (/mnt/c/Users/User/AppData/Roaming/npm/node_modules/vite/node_modules/rollup/dist/native.js:98:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /mnt/c/Users/User/AppData/Roaming/npm/node_modules/vite/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
      at Module._load (node:internal/modules/cjs/loader:981:27)
      at Module.require (node:internal/modules/cjs/loader:1231:19)
      at require (node:internal/modules/helpers:177:18)
      at requireWithFriendlyError (/mnt/c/Users/User/AppData/Roaming/npm/node_modules/vite/node_modules/rollup/dist/native.js:71:10)
      at Object.<anonymous> (/mnt/c/Users/User/AppData/Roaming/npm/node_modules/vite/node_modules/rollup/dist/native.js:98:76)
      at Module._compile (node:internal/modules/cjs/loader:1364:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
      at Module.load (node:internal/modules/cjs/loader:1203:32)
      at Module._load (node:internal/modules/cjs/loader:1019:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/mnt/c/Users/User/AppData/Roaming/npm/node_modules/vite/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v18.20.0
make[1]: *** [Makefile:31: start-frontend] Error 1
make[1]: Leaving directory '/home/zeus/workspace/devin/OpenDevin' 



Please help me fix this 

I am using WSL

**Comment by neubig** [comment]
@Zeus9820 It seems that Python is not installed in your version of WSL, so you will need to install it. This isn't an OpenDevin specific problem so we probably won't be able to provide support for that.

**Comment by Zeus9820** [comment]
I have fixed it can you see whats happening here 

zeus@ZEUS:~/workspace/devin/OpenDevin$ make run
Running the app...
make[1]: Entering directory '/home/zeus/workspace/devin/OpenDevin'
Starting backend...
make[1]: Entering directory '/home/zeus/workspace/devin/OpenDevin'
Starting frontend...
yarn run v1.22.19
$ vite
Traceback (most recent call last):
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zeus/workspace/devin/OpenDevin/opendevin/server/listen.py", line 1, in <module>
    from opendevin.server.session import Session
  File "/home/zeus/workspace/devin/OpenDevin/opendevin/server/session.py", line 5, in <module>
    from fastapi import WebSocketDisconnect
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/fastapi/openapi/models.py", line 4, in <module>
    from fastapi._compat import (
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/fastapi/_compat.py", line 24, in <module>
    from starlette.datastructures import UploadFile
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/starlette/datastructures.py", line 7, in <module>
    from starlette.concurrency import run_in_threadpool
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/starlette/concurrency.py", line 8, in <module>
    import anyio.to_thread
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/anyio/__init__.py", line 27, in <module>
    from ._core._sockets import connect_tcp as connect_tcp
  File "/home/zeus/.local/share/virtualenvs/OpenDevin-vcEyM1DF/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 35, in <module>
    from exceptiongroup import ExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'
make[1]: *** [Makefile:26: start-backend] Error 1
make[1]: Leaving directory '/home/zeus/workspace/devin/OpenDevin'

  VITE v5.2.7  ready in 283 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
6:55:08 AM [vite] ws proxy error:
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
6:55:08 AM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
6:55:08 AM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
6:55:08 AM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
6:55:08 AM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)

**Comment by Zeus9820** [comment]
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.

  VITE v5.2.7  ready in 274 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
7:50:21 AM [vite] ws proxy error:
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:21 AM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:21 AM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:21 AM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:21 AM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:23 AM [vite] ws proxy error:
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:23 AM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:23 AM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:23 AM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:23 AM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:24 AM [vite] ws proxy error:
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:24 AM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:24 AM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:24 AM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
7:50:24 AM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
INFO:     Started server process [26441]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
I have fixed all the issues i dont know what is happeing here

**Comment by azmodeuz** [comment]
we need more info if you want help.

python --version

python3 --version

docker-compose --version

node --version

cat /etc/os-release

I had a problem that makefile was looking for python and not python3. 

so provide this info, and i can help

**Comment by Zeus9820** [comment]
I have resolved all this issues of wsl it is working fine now @azmodeuz

**Comment by risingsunomi** [comment]
Was running into quite a bit of issues too on WSL. One thing that really help me to get it working is by creating a opendevin_env python3.11 venv and then cloning the report in the venv folder. After source activating, run the make file. 

Another thing with just using the python command in the MakeFile, it assumes that you are already in a venv and running make build in the venv. I think this can be solved by both adding a way to specify python 3.11 or greater or just python3.11 as default or adding commands in the MakeFile to create a venv with python3.11 or greater first before running any python commands

Something I would like to add to the setup instructions especially WSL. I am going to try it in a fully Linux env (PopOS) though and see if I get similar issues.
