### ISSUE TITLE
make start-backend error

### ISSUE THREAD

**Issue by MokshithAnnagiri** [OpenDevin/OpenDevin#668]
make start-backend
Starting backend...
Traceback (most recent call last):
  File "/home/amks/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/amks/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/amks/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/amks/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/amks/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/amks/.local/lib/python3.10/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/amks/.local/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/amks/.local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/amks/.local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/amks/.local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/amks/.local/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/amks/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/home/amks/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/amoks/OneDrive/Desktop/btech/OpenDevin/OpenDevin/opendevin/server/listen.py", line 4, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
  File "/mnt/c/Users/amoks/OneDrive/Desktop/btech/OpenDevin/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
  File "/mnt/c/Users/amoks/OneDrive/Desktop/btech/OpenDevin/OpenDevin/agenthub/monologue_agent/__init__.py", line 2, in <module>
    from .agent import MonologueAgent
  File "/mnt/c/Users/amoks/OneDrive/Desktop/btech/OpenDevin/OpenDevin/agenthub/monologue_agent/agent.py", line 28, in <module>
    from agenthub.monologue_agent.utils.memory import LongTermMemory
  File "/mnt/c/Users/amoks/OneDrive/Desktop/btech/OpenDevin/OpenDevin/agenthub/monologue_agent/utils/memory.py", line 5, in <module>
    from llama_index.vector_stores.chroma import ChromaVectorStore
ModuleNotFoundError: No module named 'llama_index.vector_stores'
make: *** [Makefile:26: start-backend] Error 1

**Comment by foragerr** [comment]
Did you run `make build` first, as listed in the readme instructions?
https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#-get-started

**Comment by rbren** [comment]
Closing this one due to lack of info. @MokshithAnnagiri if following the README doesn't work, can you open a new issue and fill out the template?
