### ISSUE TITLE
Error when starting HTTP server: Address already in use  

### ISSUE THREAD

**Issue by nickmoore444** [OpenDevin/OpenDevin#680]
When attempting to start the HTTP server using the `python -m http.server` command, an OSError with the message "Address already in use" is encountered.

#### Setup and configuration
**Current version**:

```bash
```

Mac OS 14.4.1 Sonoma

**My model and agent** (you can see these settings in the UI):
* Model: GPT 3.5 Turbo
* Agent: Planner

**Commands I ran to install and run OpenDevin**:
pipenv install

**Steps to Reproduce**:
1. Create a simple web server that says "Hello World!"
2.
3.

**Logs, error messages, and screenshots**:
$ python3 -m http.server
Background command started. To stop it, send a `kill` action with id 27

$ Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/http/server.py", line 1307, in <module>
J    test(
  File "/usr/lib/python3.10/http/server.py", line 1258, in test
w    with ServerClass(addr, HandlerClass) as httpd:
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
^    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 1301, in server_bind
g    return super().server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
t    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
U    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

$ Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
`    exec(code, run_globals)
  File "/usr/lib/python3.10/http/server.py", line 1307, in <module>
J    test(
  File "/usr/lib/python3.10/http/server.py", line 1258, in test
w    with ServerClass(addr, HandlerClass) as httpd:
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
^    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 1301, in server_bind
�    return super().server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
U    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

$ python -m http.server
Background command started. To stop it, send a `kill` action with id 29

**Comment by stratte89** [comment]
hey try to run this in the terminal

for port in {3000..3005}; do
  pid=$(lsof -ti :$port)
  if [ ! -z "$pid" ]; then
    echo "Killing process on port $port"
    kill -9 $pid
  fi
done

**Comment by rbren** [comment]
This doesn't seem like an OpenDevin bug. BTW @nickmoore444 you should be using uvicorn to start the server

**Comment by nickmoore444** [comment]
I am using uvicorn to start the backend if I run this @stratte89 it will kill the backend server that's running on 3000, the problem is the http server isn't starting because it's trying to use an existing port, I noticed a few other people on youtube that ran into this.  Maybe starting the server on 8080?
python -m http.server 8080

**Comment by rbren** [comment]
Sorry I think I misunderstood--it's the _agent_ running `python -m http.server 8080`?

**Comment by nickmoore444** [comment]
The agent is not running on 8080 it's trying to use a port that's already being used I suggested the fix is to have it run on another port.

**Comment by rbren** [comment]
I'm going to close this in favor of https://github.com/OpenDevin/OpenDevin/issues/954
