### ISSUE TITLE
Fails at sudo make run

### ISSUE THREAD

**Issue by cardoza1991** [OpenDevin/OpenDevin#747]
#### Setup and configuration
**Current version**:

```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:Claude 3 Opus
* Agent:??

**Commands I ran to install and run OpenDevin**:
make build
make setup-config
```(base) michael@megatron:~/OpenDevin$ sudo make run
Running the app...
/bin/sh: 1: [: unexpected operator
make[1]: Entering directory '/home/michael/OpenDevin'
Starting backend...
make[1]: Entering directory '/home/michael/OpenDevin'
Starting frontend...

> opendevin-frontend@0.1.0 start
> vite


  VITE v5.2.8  ready in 939 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/michael/OpenDevin/opendevin/server/listen.py", line 4, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "/home/michael/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/OpenDevin/agenthub/monologue_agent/__init__.py", line 2, in <module>
    from .agent import MonologueAgent
  File "/home/michael/OpenDevin/agenthub/monologue_agent/agent.py", line 28, in <module>
    from agenthub.monologue_agent.utils.memory import LongTermMemory
  File "/home/michael/OpenDevin/agenthub/monologue_agent/utils/memory.py", line 2, in <module>
    from llama_index.core import Document
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 31, in <module>
    from llama_index.core.ingestion.api_utils import get_client
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/api_utils.py", line 23, in <module>
    from llama_index.core.ingestion.transformations import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/transformations.py", line 267, in <module>
    ConfigurableTransformations = build_configurable_transformation_enum()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/transformations.py", line 247, in build_configurable_transformation_enum
    from llama_index.embeddings.huggingface import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/embeddings/huggingface/__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/embeddings/huggingface/base.py", line 27, in <module>
    from sentence_transformers import SentenceTransformer
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/torch/__init__.py", line 197, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/torch/__init__.py", line 162, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['', '/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/bin', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages', '/home/michael/OpenDevin']
make[1]: *** [Makefile:33: start-backend] Error 1
make[1]: Leaving directory '/home/michael/OpenDevin'
^Cmake[1]: *** [Makefile:38: start-frontend] Interrupt
make: *** [Makefile:48: run] Interrupt


```

**Steps to Reproduce**:
1.
2.
3.

**Logs, error messages, and screenshots**:

**Comment by foragerr** [comment]
What commit are you on? please pull latest.

**Comment by dorbanianas** [comment]
yeah I guess you are in an old commit because we fixed the unexpected operator error

**Comment by cardoza1991** [comment]
I am using the latest one from a few hours ago

**Comment by dorbanianas** [comment]
git to pull the latest one because there's so many changes 😅

**Comment by dorbanianas** [comment]
and rerun `make build`

**Comment by cardoza1991** [comment]
ok I will do that!

**Comment by cardoza1991** [comment]
Aigo! Same issue. (base) michael@megatron:~/OpenDevin$ sudo make run
Running the app...
/bin/sh: 1: [: unexpected operator
make[1]: Entering directory '/home/michael/OpenDevin'
Starting backend...
make[1]: Entering directory '/home/michael/OpenDevin'
Starting frontend...

> opendevin-frontend@0.1.0 start
> vite


  VITE v5.2.8  ready in 582 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/michael/OpenDevin/opendevin/server/listen.py", line 4, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "/home/michael/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/OpenDevin/agenthub/monologue_agent/__init__.py", line 2, in <module>
    from .agent import MonologueAgent
  File "/home/michael/OpenDevin/agenthub/monologue_agent/agent.py", line 28, in <module>
    from agenthub.monologue_agent.utils.memory import LongTermMemory
  File "/home/michael/OpenDevin/agenthub/monologue_agent/utils/memory.py", line 2, in <module>
    from llama_index.core import Document
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 31, in <module>
    from llama_index.core.ingestion.api_utils import get_client
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/api_utils.py", line 23, in <module>
    from llama_index.core.ingestion.transformations import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/transformations.py", line 267, in <module>
    ConfigurableTransformations = build_configurable_transformation_enum()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/core/ingestion/transformations.py", line 247, in build_configurable_transformation_enum
    from llama_index.embeddings.huggingface import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/embeddings/huggingface/__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/llama_index/embeddings/huggingface/base.py", line 27, in <module>
    from sentence_transformers import SentenceTransformer
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/torch/__init__.py", line 197, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages/torch/__init__.py", line 162, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['', '/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/bin', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/root/.local/share/virtualenvs/OpenDevin-L7Wv9fhF/lib/python3.11/site-packages', '/home/michael/OpenDevin']
make[1]: *** [Makefile:33: start-backend] Error 1
make[1]: Leaving directory '/home/michael/OpenDevin'
I tried troubleshooting myself. CUDA is in my bashrc

**Comment by cardoza1991** [comment]
I've had less issues with the requirements.txt version... michael@megatron:~/OpenDevin$ sudo make build
[sudo] password for michael: 
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
Installing Python dependencies...
Retrieving Poetry metadata

The latest version (1.8.2) is already installed.
make: poetry: No such file or directory
make: *** [Makefile:20: build] Error 127
michael@megatron:~/OpenDevin$

**Comment by cardoza1991** [comment]
installed poetry to ubuntu with curl -sSL https://install.python-poetry.org | python3 -
success.
added poetry to path with "bashrc" added export PATH="$HOME/.local/bin:$PATH" to bashrc with nano ~/.bashrc
next. Used source ~/.bashrc to make the changes. Verified poetry is on system path. michael@megatron:~/OpenDevin$ poetry --version
Poetry (version 1.8.2)
Still failed. 
michael@megatron:~/OpenDevin$ sudo make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
Installing Python dependencies...
Retrieving Poetry metadata

The latest version (1.8.2) is already installed.
make: poetry: No such file or directory
make: *** [Makefile:20: build] Error 127
I am updating the Makefile with @poetry install --without evaluation
added @/home/michael/.local/bin/poetry install --without evaluation install --without evaluation <- this fixed it

**Comment by cardoza1991** [comment]
And it broke again.

**Comment by cardoza1991** [comment]
The main culprit being "Poetry not found." here;s the backend logs. /bin/sh: 1: poetry: not found
Seriously nothing is working. I had high hopes. I'll go back to Pythagora

**Comment by dorbanianas** [comment]
Can you try to run it without sudo

**Comment by yufansong** [comment]
> The main culprit being "Poetry not found." here;s the backend logs. /bin/sh: 1: poetry: not found

See [here](https://github.com/OpenDevin/OpenDevin/issues/759#issuecomment-2039618274). If it is a poetry problem. it may largely you didn't set the environment variable path.

**Comment by cardoza1991** [comment]
> Can you try to run it without sudo

Yeah I did and the websocket failed.

**Comment by cardoza1991** [comment]
> > The main culprit being "Poetry not found." here;s the backend logs. /bin/sh: 1: poetry: not found
> 
> See [here](https://github.com/OpenDevin/OpenDevin/issues/759#issuecomment-2039618274). If it is a poetry problem. it may largely you didn't set the environment variable path.

I hard coded the path in the Makefile and bashrc see above.
