### ISSUE TITLE
Missing files of frontend

### ISSUE THREAD

**Issue by pi-null-mezon** [OpenDevin/OpenDevin#762]
I have pull master branch today and opendevin frontend stops to work. Seems some files are absent in `./frontend/src/i18n`

**Current version**:
```bash
commit dcaf51bc9e09ae02c5719aea7f9232d7c6dd2c9e (HEAD -> main, origin/main, origin/HEAD)
Author: iFurySt <ifuryst@gmail.com>
Date:   Fri Apr 5 11:21:17 2024 +0800

    fix: add the community-maintained model list (#654)
```

**Commands I ran to install and run OpenDevin**:
```
make build
```

**Steps to Reproduce**:
make run # and go to localhost:3001
 
**Logs, error messages, and screenshots**:

```bash
make run
Running the app...
Waiting for the backend to start...

> opendevin-frontend@0.1.0 start /home/alex/Programming//OpenDevin/frontend
> vite "--" "--port" "3001"


  VITE v5.2.8  ready in 381 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
2:02:49 PM [vite] Internal server error: Failed to resolve import "../i18n/declaration" from "src/components/ChatInterface.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/alex/Programming//OpenDevin/frontend/src/components/ChatInterface.tsx:8:24
  23 |  import userAvatar from "../assets/user-avatar.png";
  24 |  import { useTypingEffect } from "../hooks/useTypingEffect";
  25 |  import { I18nKey } from "../i18n/declaration";
     |                           ^
  26 |  import {
  27 |    addAssistantMessageToChat,
      at formatError (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50863:46)
      at TransformContext.error (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50857:19)
      at normalizeUrl (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66092:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66247:47
      at async Promise.all (index 10)
      at async TransformContext.transform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66168:13)
      at async Object.transform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51172:30)
      at async loadAndTransform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:53923:29)
2:02:49 PM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/ChatInterface.tsx". Does the file exist?
2:02:49 PM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/Workspace.tsx". Does the file exist?
2:02:49 PM [vite] Internal server error: Failed to resolve import "../i18n/declaration" from "src/components/SettingModal.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/alex/Programming//OpenDevin/frontend/src/components/SettingModal.tsx:35:24
  49 |  import store from "../store";
  50 |  import socket from "../socket/socket";
  51 |  import { I18nKey } from "../i18n/declaration";
     |                           ^
  52 |  import { AvailableLanguages } from "../i18n";
  53 |  const cachedModels = JSON.parse(
      at formatError (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50863:46)
      at TransformContext.error (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50857:19)
      at normalizeUrl (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66092:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66247:47
      at async Promise.all (index 12)
      at async TransformContext.transform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66168:13)
      at async Object.transform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51172:30)
      at async loadAndTransform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:53923:29)
2:02:49 PM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/SettingModal.tsx". Does the file exist?
2:02:49 PM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/Input.tsx". Does the file exist?
2:02:49 PM [vite] Internal server error: Failed to resolve import "../i18n/declaration" from "src/components/Workspace.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/alex/Programming//OpenDevin/frontend/src/components/Workspace.tsx:7:24
  22 |  import Earth from "../assets/earth";
  23 |  import Pencil from "../assets/pencil";
  24 |  import { I18nKey } from "../i18n/declaration";
     |                           ^
  25 |  import { AllTabs, TabOption } from "../types/TabOption";
  26 |  import Browser from "./Browser";
      at formatError (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50863:46)
      at TransformContext.error (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50857:19)
      at normalizeUrl (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66092:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66247:47
      at async Promise.all (index 9)
      at async TransformContext.transform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66168:13)
      at async Object.transform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51172:30)
      at async loadAndTransform (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:53923:29)
      at async viteTransformMiddleware (file:///home/alex/Programming//OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:63775:32)
```

**Comment by 808vita** [comment]
Thanks for creating this issue.
I faced a similar issue relating to this.

Please try out the following things:
- check if you have corepack or install it `npm install -g corepack`
- make sure to run  `pnpm run make-i18n` this is creates the necessary declaration.

And try running the frontend again.

**Comment by FazliddinKiller** [comment]
> I hit this too. A fresh `make build` fixes it--always good to run after pulling latest
> 
> (edit: looks like you ran `make build`...not sure why it didn't take)

Worked for me! Thanks a lot!

**Comment by pi-null-mezon** [comment]
I give it another try. Yes, `make build && make run` works now for me too. So, issue no longer needed. Thanks :heart:

**Comment by pi-null-mezon** [comment]
closing
