### ISSUE TITLE
You cannot enter a message.

### ISSUE THREAD

**Issue by namkim** [OpenDevin/OpenDevin#764]
#### Describe the bug

After make run, I cannot enter any message after connecting to `http://localhost:3001/`
Messages cannot be entered and sent.

#### Setup and configuration
**Current version**:

```bash
commit dcaf51bc9e09ae02c5719aea7f9232d7c6dd2c9e (HEAD -> main, origin/main, origin/HEAD)
Author: iFurySt <ifuryst@gmail.com>
Date:   Fri Apr 5 11:21:17 2024 +0800

    fix: add the community-maintained model list (#654)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-3.5-turbo"
LLM_API_KEY="sk-*********"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

**Logs, error messages, and screenshots**:

#### Additional Context
![Screenshot 2024-04-05 at 21 40 59](https://github.com/OpenDevin/OpenDevin/assets/5554576/14b2ba4e-2d80-4226-be5b-d18c813f8df9)

**Comment by foragerr** [comment]
Look for errors among the files in `./logs` folder please.

**Comment by namkim** [comment]
Thank you.
I was able to check the error log.

```
/Users/kaneo/.pyenv/versions/3.11.1/envs/devin/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [40125]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 50192) - "WebSocket /ws" [accepted]
INFO:     connection open
INFO:     127.0.0.1:50194 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:50195 - "GET /litellm-agents HTTP/1.1" 200 OK
Please check Docker is running using `docker ps`.
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
INFO:     ('127.0.0.1', 50197) - "WebSocket /ws" [accepted]
INFO:     connection open
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Error creating controller.
INFO:     127.0.0.1:50193 - "GET /default-model HTTP/1.1" 200 OK
INFO:     127.0.0.1:50198 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:50199 - "GET /litellm-agents HTTP/1.1" 200 OK
Please check Docker is running using `docker ps`.
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Error creating controller.
INFO:     127.0.0.1:50204 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:50205 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:50203 - "GET /default-model HTTP/1.1" 200 OK
INFO:     127.0.0.1:50209 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:50210 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:50211 - "GET /default-model HTTP/1.1" 200 OK
INFO:     127.0.0.1:50213 - "GET /default-model HTTP/1.1" 200 O
```

**Comment by foragerr** [comment]
```
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError
``` 

usually means the server code is unable to connect to docker on your machine. Search for that error in issues, there are some troubleshooting steps in other tickets.

**Comment by zhonggegege** [comment]
I have more errors here, it seems that no matter how I configure the config.toml I can't connect to the local ollama, it always prompts the following error, this is the last part of the log:
raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=null
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
INFO:     connection closed

config.toml:
LLM_MODEL="ollama/qwen:7b"
LLM_API_KEY="ollama"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://loaclhost:<port_number>"
WORKSPACE_DIR="./workspace"

**Comment by zhonggegege** [comment]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/home/agent/OpenDevin/opendevin/server/listen.py", line 26, in websocket_endpoint
    await session.start_listening()
  File "/home/agent/OpenDevin/opendevin/server/session.py", line 89, in start_listening
    await self.create_controller(data)
  File "/home/agent/OpenDevin/opendevin/server/session.py", line 135, in create_controller
    llm = LLM(model=model, api_key=api_key, base_url=api_base)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agent/OpenDevin/opendevin/llm/llm.py", line 36, in __init__
    self._router = Router(
                   ^^^^^^^
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/litellm/router.py", line 198, in __init__
    self.set_model_list(model_list)
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/litellm/router.py", line 2075, in set_model_list
    ) = litellm.get_llm_provider(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/litellm/utils.py", line 5759, in get_llm_provider
    raise e
  File "/home/agent/miniconda3/envs/opendev/lib/python3.11/site-packages/litellm/utils.py", line 5746, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=null
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by enyst** [comment]
This doesn't seem to be an issue with the project, I'll close this but please do open another issue if you still experience problems!
