### ISSUE TITLE
Installation and first run issues on M1 Mac: Poetry PATH and Permissions Errors

### ISSUE THREAD

**Issue by loveQt** [OpenDevin/OpenDevin#777]
#### Describe the bug

Great work guys, while **I have installed and ran opendevin successfully**, just want to share something during my first install on a clean M1 Mac.
1. poetry. seems like poetry is required but not listed as Requirements and will be automatically installed, but as poetry wasn't in PATH, the `make build` will exit with an error:
```
Installing Python dependencies...
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/Users/xcduan/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.8.2): Done

Poetry (1.8.2) is installed now. Great!

To get started you need Poetry's bin directory (/Users/xcduan/.local/bin) in your `PATH`
environment variable.

Add `export PATH="/Users/xcduan/.local/bin:$PATH"` to your shell configuration file.

Alternatively, you can call Poetry explicitly with `/Users/xcduan/.local/bin/poetry`.

You can test that everything is set up by executing:

`poetry --version`

make: poetry: No such file or directory
make: *** [build] Error 1
```
maybe should consider adding to PATH, or advise user to `pip3 install poetry` manually.

2. after I install poetry manually and globally, I encountered another PermissionError, which can be fixed using `sudo make build`
```
PermissionError: [Errno 13] Permission denied: '/Users/xcduan/.cache/pre-commit'
make: *** [build] Error 1
```

3. when first `make run`, got another permission denied, so have to use `sudo make run`
```
Running the app...
Waiting for the backend to start...
Connection to localhost port 3000 [tcp/hbci] succeeded!

> opendevin-frontend@0.1.0 start /Users/xcduan/OpenDevin/frontend
> vite "--" "--port" "3001"


  VITE v5.2.8  ready in 649 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Error: EACCES: permission denied, mkdir '/Users/xcduan/OpenDevin/frontend/node_modules/.vite/deps_temp_45b34176'
    at Object.mkdirSync (node:fs:1401:3)
    at runOptimizeDeps (file:///Users/xcduan/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:52612:10)
    at file:///Users/xcduan/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:52053:46
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
this permission denied only appears once, and it seems I can use `make run`now.

#### Setup and configuration
**Current version**:

```bash
commit 1328f55dcdab8a79b21fb783ee26d97c268cd1f5 (HEAD -> main, origin/main, origin/HEAD)
```

**Comment by neubig** [comment]
I also encountered this, I think it can be classified as a bug since it causes `make build` to break. I'll take a look at this, but have limited time for the next couple days, so if someone else has a fix then that's also welcome.
