### ISSUE TITLE
ERROR meta-llama/Llama-2-13b  and plz suggest  workable model

### ISSUE THREAD

**Issue by Ratul007** [OpenDevin/OpenDevin#782]
Face this error --Provider List: https://docs.litellm.ai/docs/providers

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/home/eagle/.vscode/OpenDevin/opendevin/server/listen.py", line 26, in websocket_endpoint
    await session.start_listening()
  File "/home/eagle/.vscode/OpenDevin/opendevin/server/session.py", line 89, in start_listening
    await self.create_controller(data)
  File "/home/eagle/.vscode/OpenDevin/opendevin/server/session.py", line 135, in create_controller
    llm = LLM(model=model, api_key=api_key, base_url=api_base)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eagle/.vscode/OpenDevin/opendevin/llm/llm.py", line 36, in __init__
    self._router = Router(
                   ^^^^^^^
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/router.py", line 198, in __init__
    self.set_model_list(model_list)
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/router.py", line 2075, in set_model_list
    ) = litellm.get_llm_provider(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 5759, in get_llm_provider
    raise e
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 5746, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=meta-llama/Llama-2-13b
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
INFO:     connection closed
INFO:     127.0.0.1:46454 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:46458 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:46470 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:46474 - "GET /litellm-agents HTTP/1.1" 200 OK

**Comment by lowlyocean** [comment]
See https://github.com/OpenDevin/OpenDevin/issues/793

**Comment by zhonggegege** [comment]
My troubles are worse here：
raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=null
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by rbren** [comment]
Hey all--sorry you're having trouble. Please open a new issue with the template filled out, so we have enough info to reproduce.
