### ISSUE TITLE
ERROR:openrouter/mistralai/mistral-7b-instruct:free 

### ISSUE THREAD

**Issue by Ratul007** [OpenDevin/OpenDevin#784]
PLAN:
hi

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

ERROR:
Traceback (most recent call last):
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 350, in completion
    openai_client = OpenAI(
                    ^^^^^^^
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/openai/_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/main.py", line 1529, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 422, in completion
    raise OpenAIError(status_code=500, message=traceback.format_exc())
litellm.llms.openai.OpenAIError: Traceback (most recent call last):
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 350, in completion
    openai_client = OpenAI(
                    ^^^^^^^
  File "/home/eagle/.cache/pypoetry/virtualenvs/opendevin-nolN6OfP-py3.11/lib/python3.11/site-packages/openai/_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by yufansong** [comment]
> openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

You should set this variable.

**Comment by Ratul007** [comment]
Okey thank you 😊
