### ISSUE TITLE
im haveing a  bad time running lm-studios 

### ISSUE THREAD

**Issue by Soundmovin46** [OpenDevin/OpenDevin#799]
OBSERVATION:
Error condensing thoughts: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}  
Exited before finishing
^CReceived signal 2, exiting...
INFO:     connection closed
ERROR:    Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 216, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 397, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 402, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 377, in uvloop.loop.Loop._ceval_process_signals
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/opendevin/server/session/manager.py", line 45, in handle_signal
    exit(0)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/routing.py", line 741, in lifespan
    await receive()
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 216, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 397, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 402, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 377, in uvloop.loop.Loop._ceval_process_signals
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/opendevin/server/session/manager.py", line 45, in handle_signal
    exit(0)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/opendevin/server/listen.py", line 40, in websocket_endpoint
    await session_manager.loop_recv(sid, agent_manager.dispatch)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/opendevin/server/session/manager.py", line 37, in loop_recv
    await self._sessions[sid].loop_recv(dispatch)
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/opendevin/server/session/session.py", line 26, in loop_recv
    data = await self.websocket.receive_json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/websockets.py", line 157, in receive_json
    message = await self.receive()
              ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/starlette/websockets.py", line 49, in receive
    message = await self._receive()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 379, in asgi_receive
    data = await self.recv()
           ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await asyncio.wait(
  File "/usr/lib/python3.11/asyncio/tasks.py", line 428, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 535, in _wait
    await waiter
asyncio.exceptions.CancelledError

(devin_env_311) soundmoving465@bryantmorrismin:/mnt/c/Users/zombi/Downloads/GPT/OpenDevin$ kill -9 14831
-bash: kill: (14831) - No such process
(devin_env_311) soundmoving465@bryantmorrismin:/mnt/c/Users/zombi/Downloads/GPT/OpenDevin$ kill -9 25628
-bash: kill: (25628) - No such process
(devin_env_311) soundmoving465@bryantmorrismin:/mnt/c/Users/zombi/Downloads/GPT/OpenDevin$ make setup-config
Setting up config.toml...
Enter your LLM Model name (see https://docs.litellm.ai/docs/providers for full list) [default: gpt-4-0125-preview]: TheBloke/CodeLlama-13B
Enter your LLM API key: lm-studio
Enter your LLM Base URL [mostly used for local LLMs, leave blank if not needed - example: http://localhost:5001/v1/]: http://localhost:1234/v1
/bin/sh: 2: [[: not found
Enter your LLM Embedding Model
Choices are openai, azureopenai, llama2 or leave blank to default to 'BAAI/bge-small-en-v1.5' via huggingface
> local
Enter your workspace directory [default: ./workspace]:
(devin_env_311) soundmoving465@bryantmorrismin:/mnt/c/Users/zombi/Downloads/GPT/OpenDevin$ make start-backend
Starting backend...
/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".
/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".
LLM_MODEL="TheBloke/CodeLlama-13B"
LLM_API_KEY="lm-studio"
LLM_EMBEDDING_MODEL="local"
WORKSPACE_DIR="./workspace"

model id has a confict when i run it and look for my model it no where to be found and im running the back end this is my config file 
 this is the the error that i get and its also saying when i load it up that trying to use it with lm studios

**Comment by enyst** [comment]
Have you succeeded in the past with this LLM_MODEL setting? I am not sure it works, but lm-studio is openai compatible from what I understand, so it might work with:
```LLM_MODEL="openai/CodeLlama-13B"```
assuming that the second part of the name is exactly right. The rest unchanged. Can you give it a try?

**Comment by Soundmovin46** [comment]
> Have you succeeded in the past with this LLM_MODEL setting? I am not sure it works, but lm-studio is openai compatible from what I understand, so it might work with: `LLM_MODEL="openai/CodeLlama-13B"` assuming that the second part of the name is exactly right. The rest unchanged. Can you give it a try?

this is my first go around  il give it a shot and see how it works if you have any reconditions to this problem it would be greatly welcome (devin_env_311) soundmoving465@bryantmorrismin:/mnt/c/Users/zombi/Downloads/GPT/OpenDevin$ make start-backend
Starting backend...
/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.

**Comment by enyst** [comment]
That is a warning, it's annoying but it doesn't affect functionality. It is already tracked and will be fixed.

**Comment by zhonggegege** [comment]
> openai/CodeLlama-13B

After make run, it seems that the front end will forcefully read the model in the settings, and this model cannot be downloaded in ollama, which seems to lead to an endless loop with no solution.

![1712393371941](https://github.com/OpenDevin/OpenDevin/assets/152971528/ef629d33-5ce0-42ba-a64d-62e6d0e938e9)

**Comment by rbren** [comment]
I just put a call out for better LM studio docs. Seems like a lot of folks are having trouble.

Going to close this in favor of https://github.com/OpenDevin/OpenDevin/issues/419
