### ISSUE TITLE
Failed to start on make run

### ISSUE THREAD

**Issue by thelege2nd** [OpenDevin/OpenDevin#815]
![image](https://github.com/OpenDevin/OpenDevin/assets/12984941/93ccd7d8-c6ae-4129-bdc2-fdef87aae927)

any ideas how to fix this?

**Comment by thelege2nd** [comment]
fixed the initial issue but now  im getting this error

thelege2nd@MonsterGorilla:/mnt/d/devin/OpenDevin$ make run
Running the app...
Waiting for the backend to start...
Backend started successfully.
Starting frontend with pnpm...

> opendevin-frontend@0.1.0 start /mnt/d/devin/OpenDevin/frontend
> vite "--" "--port" "3001"


  VITE v5.2.8  ready in 13154 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
11:45:29 AM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/Workspace.tsx". Does the file exist?
11:45:29 AM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/SettingModal.tsx". Does the file exist?
11:45:29 AM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/ChatInterface.tsx". Does the file exist?
11:45:30 AM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/Input.tsx". Does the file exist?
11:45:31 AM [vite] Internal server error: Failed to resolve import "../i18n/declaration" from "src/components/Workspace.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /mnt/d/devin/OpenDevin/frontend/src/components/Workspace.tsx:7:24
  22 |  import Earth from "../assets/earth";
  23 |  import Pencil from "../assets/pencil";
  24 |  import { I18nKey } from "../i18n/declaration";
     |                           ^
  25 |  import { AllTabs, TabOption } from "../types/TabOption";
  26 |  import Browser from "./Browser";
      at formatError (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50863:46)
      at TransformContext.error (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50857:19)
      at normalizeUrl (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66092:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66247:47
      at async Promise.all (index 9)
      at async TransformContext.transform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66168:13)
      at async Object.transform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51172:30)
      at async loadAndTransform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:53923:29)
      at async viteTransformMiddleware (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:63775:32)
11:45:31 AM [vite] Internal server error: Failed to resolve import "../i18n/declaration" from "src/components/SettingModal.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /mnt/d/devin/OpenDevin/frontend/src/components/SettingModal.tsx:27:24
  40 |    getInitialModel
  41 |  } from "../services/settingsService";
  42 |  import { I18nKey } from "../i18n/declaration";
     |                           ^
  43 |  import { AvailableLanguages } from "../i18n";
  44 |  const cachedModels = JSON.parse(
      at formatError (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50863:46)
      at TransformContext.error (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50857:19)
      at normalizeUrl (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66092:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66247:47
      at async Promise.all (index 8)
      at async TransformContext.transform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66168:13)
      at async Object.transform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51172:30)
      at async loadAndTransform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:53923:29)
      at async viteTransformMiddleware (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:63775:32)
11:45:31 AM [vite] Internal server error: Failed to resolve import "../i18n/declaration" from "src/components/ChatInterface.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /mnt/d/devin/OpenDevin/frontend/src/components/ChatInterface.tsx:8:24
  23 |  import userAvatar from "../assets/user-avatar.png";
  24 |  import { useTypingEffect } from "../hooks/useTypingEffect";
  25 |  import { I18nKey } from "../i18n/declaration";
     |                           ^
  26 |  import {
  27 |    addAssistantMessageToChat,
      at formatError (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50863:46)
      at TransformContext.error (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50857:19)
      at normalizeUrl (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66092:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66247:47
      at async Promise.all (index 10)
      at async TransformContext.transform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66168:13)
      at async Object.transform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51172:30)
      at async loadAndTransform (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:53923:29)
      at async viteTransformMiddleware (file:///mnt/d/devin/OpenDevin/frontend/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.29/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:63775:32)
11:45:31 AM [vite] Pre-transform error: Failed to resolve import "../i18n/declaration" from "src/components/Input.tsx". Does the file exist?

**Comment by 808vita** [comment]
please try out the things mentioned here 

https://github.com/OpenDevin/OpenDevin/issues/762

**Comment by thelege2nd** [comment]
yeah some reason make build and make run fixies it.
