### ISSUE TITLE
Unknow issue

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#817]
self.socket.listen(self.request_queue_size)
OSError: [Errno 98] Address already in use

$ python3 -m http.server --directory /workspace 8000
Background command started. To stop it, send a `kill` action with id 3

$ Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/http/server.py", line 1307, in <module>
J    test(
  File "/usr/lib/python3.10/http/server.py", line 1258, in test
w    with ServerClass(addr, HandlerClass) as httpd:
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
^    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 1301, in server_bind
�    return super().server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
U    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

$ Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/http/server.py", line 1307, in <module>
�    test(
  File "/usr/lib/python3.10/http/server.py", line 1258, in test
    with ServerClass(addr, HandlerClass) as httpd:
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
^    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 1301, in server_bind
g    return super().server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
t    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
U    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/52112679-a514-4bf7-98a8-2fb5047458b8)

**Comment by Soundmovin46** [comment]
hoeew did you get it to work\

**Comment by spuder** [comment]
This is not a problem with opendevin, this is a problem with you having a conflicting port on your computer. 

`OSError: [Errno 98] Address already in use`

Stop whatever process is taking port 3000 or 30001

**Comment by andrescevp** [comment]
`lsof -i:[PORT]` should help to kill that process in linux

**Comment by rbren** [comment]
@PierrunoYT please fill out the template when opening issues.
