### ISSUE TITLE
make build in WSL ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by bvandorf** [OpenDevin/OpenDevin#831]
Installing pre-commit hooks...
The currently activated Python version 3.10.12 is not supported by the project (^3.11).
Trying to find and use a compatible version.
Using python3 (3.12.2)
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-4iDJopQS-py3.12/bin/pre-commit", line 5, in <module>
    from pre_commit.main import main
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-4iDJopQS-py3.12/lib/python3.12/site-packages/pre_commit/main.py", line 14, in <module>
    from pre_commit.commands.clean import clean
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-4iDJopQS-py3.12/lib/python3.12/site-packages/pre_commit/commands/clean.py", line 6, in <module>
    from pre_commit.store import Store
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-4iDJopQS-py3.12/lib/python3.12/site-packages/pre_commit/store.py", line 6, in <module>
    import sqlite3
  File "/home/user/.pyenv/versions/3.12.2/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/user/.pyenv/versions/3.12.2/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
make: *** [Makefile:41: build] Error 1
user@DESKTOP-TGGO2K7:~/scripts/vscode/python/open_deven/OpenDevin$

**Comment by bvandorf** [comment]
I am also not sure what it is talking about for the python version and then finding the current one 

user@DESKTOP-TGGO2K7:~/scripts/vscode/python/open_deven/OpenDevin$ python --version
Python 3.12.2

Installing pre-commit hooks...
The currently activated Python version 3.10.12 is not supported by the project (^3.11).
Trying to find and use a compatible version.
Using python3 (3.12.2)

**Comment by bvandorf** [comment]
ok figured out the activated python version and that is now 3.12.2 without any switching

**Comment by bvandorf** [comment]
user@DESKTOP-TGGO2K7:~/scripts/vscode/python/open_deven/OpenDevin$ make build
Building project...
Checking Python installation...
Python 3 is already installed. Version: 3.12.2
Checking npm installation...
npm is already installed. Version: 10.5.1
Checking Docker installation...
Docker is already installed. Version: 24.0.6,
Installing Python dependencies...
Poetry is already installed.
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: opendevin (0.1.0)
Activating Poetry shell...
Setting up frontend environment...
Detect Node.js version...
Current Node.js version is 18.18.0, corepack is supported.
Installing frontend dependencies with npm...

> opendevin-frontend@0.1.0 prepare
> cd .. && husky install frontend/.husky

husky - Git hooks installed

up to date, audited 1017 packages in 8s

212 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
Running make-i18n with npm...

> opendevin-frontend@0.1.0 make-i18n
> node scripts/make-i18n-translations.cjs

Installing pre-commit hooks...
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-4iDJopQS-py3.12/bin/pre-commit", line 5, in <module>
    from pre_commit.main import main
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-4iDJopQS-py3.12/lib/python3.12/site-packages/pre_commit/main.py", line 14, in <module>
    from pre_commit.commands.clean import clean
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-4iDJopQS-py3.12/lib/python3.12/site-packages/pre_commit/commands/clean.py", line 6, in <module>
    from pre_commit.store import Store
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-4iDJopQS-py3.12/lib/python3.12/site-packages/pre_commit/store.py", line 6, in <module>
    import sqlite3
  File "/home/user/.pyenv/versions/3.12.2/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/user/.pyenv/versions/3.12.2/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
make: *** [Makefile:41: build] Error 1
user@DESKTOP-TGGO2K7:~/scripts/vscode/python/open_deven/OpenDevin$

**Comment by bvandorf** [comment]
I fixed it but I am not 100% sure why installing python 3.11.3 with pyenv seemed to let it work

**Comment by anthonyrawlins** [comment]
I built Python 3.12 from source and got this error. I then installed libsqlite3-dev using apt and then rebuilt Python3.12. I ran make build again with no errors.
