### ISSUE TITLE
No module named 'zipp'

### ISSUE THREAD

**Issue by xplorer990** [OpenDevin/OpenDevin#833]
Windows 11 WSL2 Ubuntu20.04

Previous issue with poetry got fixed as it seems but it runs into a different problem immediately.

```
ModuleNotFoundError: No module named 'zipp'
make: *** [Makefile:20: build] Error 1
```

```
$ make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Installing Python dependencies...
Retrieving Poetry metadata

The latest version (1.8.2) is already installed.
Traceback (most recent call last):
  File "/home/enli/.local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/console/application.py", line 19, in <module>
    from poetry.__version__ import __version__
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/__version__.py", line 5, in <module>
    from poetry.utils._compat import metadata
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/utils/_compat.py", line 20, in <module>
    import importlib_metadata as metadata
  File "/home/enli/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 8, in <module>
    import zipp
ModuleNotFoundError: No module named 'zipp'
make: *** [Makefile:20: build] Error 1
enli@LY5:~/OpenDevin$ pip install zipp
Defaulting to user installation because normal site-packages is not writeable
Collecting zipp
  Using cached zipp-3.18.1-py3-none-any.whl.metadata (3.5 kB)
Using cached zipp-3.18.1-py3-none-any.whl (8.2 kB)
Installing collected packages: zipp
Successfully installed zipp-3.18.1
enli@LY5:~/OpenDevin$ make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Installing Python dependencies...
Retrieving Poetry metadata

The latest version (1.8.2) is already installed.
Traceback (most recent call last):
  File "/home/enli/.local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/console/application.py", line 19, in <module>
    from poetry.__version__ import __version__
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/__version__.py", line 5, in <module>
    from poetry.utils._compat import metadata
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/utils/_compat.py", line 20, in <module>
    import importlib_metadata as metadata
  File "/home/enli/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 8, in <module>
    import zipp
ModuleNotFoundError: No module named 'zipp'
make: *** [Makefile:20: build] Error 1
```

**Comment by dorbanianas** [comment]
try to use `poetry run pip install zipp`

**Comment by rbren** [comment]
@dorbanianas any ideas why `make build` isn't catching zipp? Do we need to add it to our deps?

**Comment by dorbanianas** [comment]
I'm not sure about which package uses zipp but I'll take a look at it if we need to add it to our dependencies

**Comment by xplorer990** [comment]
@dorbanianas  same error

$ poetry run pip install zipp
Traceback (most recent call last):
  File "/home/enli/.local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/console/application.py", line 19, in <module>
    from poetry.__version__ import __version__
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/__version__.py", line 5, in <module>
    from poetry.utils._compat import metadata
  File "/home/enli/.local/lib/python3.8/site-packages/poetry/utils/_compat.py", line 20, in <module>
    import importlib_metadata as metadata
  File "/home/enli/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 8, in <module>
    import zipp
ModuleNotFoundError: No module named 'zipp'

**Comment by dorbanianas** [comment]
Which python version are you using type:

Python3 --version
and
Poetry run python3 --version

**Comment by dorbanianas** [comment]
You can try the new main and send here the output

**Comment by SmartManoj** [comment]
> python3.8

update to 3.11

**Comment by rbren** [comment]
Should be fixed with the new docker installation method

**Comment by rbren** [comment]
Should be fixed with the new docker installation method

**Comment by rbren** [comment]
Should be fixed with the new docker installation method
