### ISSUE TITLE
pexpect is not support on windows machine

### ISSUE THREAD

**Issue by techsharma2000** [OpenDevin/OpenDevin#889]
uvicorn opendevin.server.listen:app --port 3000
C:\Users\techs\miniconda3\envs\od\lib\site-packages\pydantic\_internal\_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
C:\Users\techs\miniconda3\envs\od\lib\site-packages\pydantic\_internal\_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
C:\Users\techs\miniconda3\envs\od\lib\site-packages\pydantic\_internal\_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
C:\Users\techs\miniconda3\envs\od\lib\site-packages\pydantic\_internal\_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
C:\Users\techs\miniconda3\envs\od\lib\site-packages\pydantic\_internal\_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
ERROR:root:  File "C:\Users\techs\miniconda3\envs\od\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\techs\miniconda3\envs\od\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\techs\miniconda3\envs\od\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\click\core.py", line 1157, in __call__      
    return self.main(*args, **kwargs)
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\click\core.py", line 1434, in invoke        
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\uvicorn\main.py", line 409, in main
    run(
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\techs\miniconda3\envs\od\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\techs\miniconda3\envs\od\lib\asyncio\base_events.py", line 649, in run_until_complete  
    return future.result()
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\uvicorn\server.py", line 69, in serve       
    await self._serve(sockets)
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\uvicorn\server.py", line 76, in _serve      
    config.load()
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\uvicorn\config.py", line 433, in load       
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\techs\miniconda3\envs\od\lib\importlib\__init__.py", line 126, in import_module        
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\devin\git\OpenDevin\opendevin\server\listen.py", line 12, in <module>
    import agenthub  # noqa F401 (we import this to get the agents registered)
  File "C:\devin\git\OpenDevin\agenthub\__init__.py", line 7, in <module>
    from . import planner_agent # noqa: E402
  File "C:\devin\git\OpenDevin\agenthub\planner_agent\__init__.py", line 2, in <module>
    from .agent import PlannerAgent
  File "C:\devin\git\OpenDevin\agenthub\planner_agent\agent.py", line 2, in <module>
    from .prompt import get_prompt, parse_response
  File "C:\devin\git\OpenDevin\agenthub\planner_agent\prompt.py", line 4, in <module>
    from opendevin.controller.agent_controller import print_with_color
  File "C:\devin\git\OpenDevin\opendevin\controller\__init__.py", line 1, in <module>
    from .agent_controller import AgentController
  File "C:\devin\git\OpenDevin\opendevin\controller\agent_controller.py", line 22, in <module>
    from .command_manager import CommandManager
  File "C:\devin\git\OpenDevin\opendevin\controller\command_manager.py", line 3, in <module>
    from opendevin.sandbox.sandbox import DockerInteractive
  File "C:\devin\git\OpenDevin\opendevin\sandbox\sandbox.py", line 7, in <module>
    from pexpect import pxssh
  File "C:\Users\techs\miniconda3\envs\od\lib\site-packages\pexpect\pxssh.py", line 23, in <module>     
    from pexpect import ExceptionPexpect, TIMEOUT, EOF, spawn

ERROR:root:<class 'ImportError'>: cannot import name 'spawn' from 'pexpect' (C:\Users\techs\miniconda3\envs\od\lib\site-packages\pexpect\__init__.py)

(od) C:\devin\git\OpenDevin>pip install pexpect
Requirement already satisfied: pexpect in c:\users\techs\miniconda3\envs\od\lib\site-packages (4.9.0)
Requirement already satisfied: ptyprocess>=0.5 in c:\users\techs\miniconda3\envs\od\lib\site-packages (from pexpect) (0.7.0)

(od) C:\devin\git\OpenDevin>

![image](https://github.com/OpenDevin/OpenDevin/assets/3040095/6a48a474-b673-413a-ae24-48162a33d397)

**Comment by dorbanianas** [comment]
For now, we don't support Windows, so you can run the project on WSL. If you face any issues let me know

**Comment by xingyaoww** [comment]
Thanks for reporting the issue! I think [wexpect](https://github.com/raczben/wexpect/tree/1b7dd177b7c5374f5ef7d19e74d4eb8d29227fe9) could be a potential solution for this, but there's probably no easy available for now. PRs are welcomed if you have any ideas to workaround this!

**Comment by rbren** [comment]
Should be fixed with the new docker installation method!

**Comment by hungson175** [comment]
> Should be fixed with the new docker installation method!

I did try the new docker installation method and still got the same error:
`10:05:47 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 38873 root@host.docker.internal` with the password '558203f6-353e-45d1-88d4-521a788e9db1' and report the issue on GitHub.
10:05:47 - opendevin:ERROR: agent.py:123 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 114, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 47, in __init__
    self.action_manager = ActionManager(self.id, container_image)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 36, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/ssh_box.py", line 90, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/ssh_box.py", line 164, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
`
