### ISSUE TITLE
I am sending you the errors that occur when the application runs.

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#913]
18:52:42 - opendevin:INFO: agent_controller.py:118 - Exited before finishing the task.
18:52:42 - opendevin:ERROR: session.py:43 - Error in loop_recv: cannot call recv while another coroutine is already waiting for the next message
Traceback (most recent call last):
  File "/home/timuc/myproject/myenv/OpenDevin/opendevin/server/session/session.py", line 28, in loop_recv
    data = await self.websocket.receive_json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/myproject/myenv/lib/python3.11/site-packages/starlette/websockets.py", line 157, in receive_json
    message = await self.receive()
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/myproject/myenv/lib/python3.11/site-packages/starlette/websockets.py", line 49, in receive
    message = await self._receive()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/myproject/myenv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 379, in asgi_receive
    data = await self.recv()
           ^^^^^^^^^^^^^^^^^
  File "/home/timuc/myproject/myenv/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 533, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message

ERROR:
AgentThinkAction.__init__() got an unexpected keyword argument 'message'
Traceback (most recent call last):
  File "/home/timuc/myproject/myenv/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/myproject/myenv/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/myproject/myenv/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/myproject/myenv/OpenDevin/opendevin/action/__init__.py", line 40, in action_from_dict
    return action_class(**args)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: AgentThinkAction.__init__() got an unexpected keyword argument 'message'

OBSERVATION:
AgentThinkAction.__init__() got an unexpected keyword argument 'message'

**Comment by rbren** [comment]
@timucindusunur we need more information. Can you open a new bug and fill out the template?

**Comment by siyun319** [comment]
same error
