### ISSUE TITLE
WebSocket disconnected

### ISSUE THREAD

**Issue by techsharma2000** [OpenDevin/OpenDevin#917]
22:21:37 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: 6946d476-8b50-40fe-92db-8fae784c1aee
22:21:42 - opendevin:INFO: sandbox.py:119 - Using workspace directory: /home/sharma/devin/OpenDevin/workspace
22:21:44 - opendevin:INFO: sandbox.py:198 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password 'c756b4f8-bcba-4d4f-8752-1acd4301762f' and report the issue on GitHub.
22:21:44 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/home/sharma/devin/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/sharma/devin/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/sharma/devin/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/sharma/devin/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/home/sharma/devin/OpenDevin/opendevin/sandbox/sandbox.py", line 201, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/sharma/anaconda3/envs/od/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host

**Comment by rbren** [comment]
@techsharma2000 can you tell us about your environment? Are you on Windows? WSL?

**Comment by techsharma2000** [comment]
WSL

**Comment by zhonggegege** [comment]
`git pull`, the situation remains the same.
![image](https://github.com/OpenDevin/OpenDevin/assets/152971528/d2125438-f4dd-4fec-976b-1d706c02d7be)

**Comment by dorbanianas** [comment]
Fixed by : #941 you can now pull the latest changes!

**Comment by PierrunoYT** [comment]
Same here

18:44:05 - opendevin:INFO: sandbox.py:119 - Using workspace directory: /mnt/c/Users/pierr/OpenDevin/workspace
18:44:05 - opendevin:INFO: sandbox.py:210 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password 'ebc61c91-4415-4e5a-b91d-8bfe0b8f9a2e' and report the issue on GitHub.
18:44:05 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/sandbox/sandbox.py", line 213, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/pierre/.cache/pypoetry/virtualenvs/opendevin-lPNnzAY--py3.12/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
INFO:     127.0.0.1:38818 - "DELETE /messages HTTP/1.1" 200 OK

**Comment by dorbanianas** [comment]
@PierrunoYT does the latest changes fixed the pxssh issue?

**Comment by PierrunoYT** [comment]
Help

**Comment by dorbanianas** [comment]
@PierrunoYT you can track this issue from here: #911
