### ISSUE TITLE
Build failure in WSL

### ISSUE THREAD

**Issue by BennyDanielT** [OpenDevin/OpenDevin#922]
#### Make build failure
The build step fails and returns an error with the package `ensurepip`.

#### Setup and configuration
**Current version**:
commit 01c4c4bee4b5d8dc227e3432f585229a7c9d7126 (HEAD -> main, origin/main, origin/HEAD)
Author: ITNerdAZ <158104716+ITNerdAZ@users.noreply.github.com>
Date:   Mon Apr 8 14:56:02 2024 +0000

    Add installation warning to readme (#883)
    
    * Update README
    
    * Update README.md
    
    ---------
    
    Co-authored-by: Robert Brennan <accounts@rbren.io>

**Commands I ran to install and run OpenDevin**:
```
# In WSL
make build 

Poetry is not installed. You can install poetry by running the following command, then adding Poetry to your PATH:
 curl -sSL https://install.python-poetry.org | python3 -

(opendevin-py3.12) danny@DANNY:/mnt/c/Users/benny/OneDrive/Desktop/Projects/AI/OpenDevin$ curl -sSL https://install.python-poetry.org | python3 -
```

**Steps to Reproduce**:
1. Clone the  latest code from github
2. Navigate to the OpenDevin directory through WSL
3. Execute `curl -sSL https://install.python-poetry.org | python3 -` 

**Logs, error messages, and screenshots**:

```
(opendevin-py3.12) danny@DANNY:/mnt/c/Users/benny/OneDrive/Desktop/Projects/AI/OpenDevin$ curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/danny/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.8.2): Creating environment
Traceback (most recent call last):
  File "<stdin>", line 314, in make
ModuleNotFoundError: No module named 'ensurepip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 945, in <module>
  File "<stdin>", line 923, in main
  File "<stdin>", line 560, in run
  File "<stdin>", line 581, in install
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "<stdin>", line 653, in make_env
  File "<stdin>", line 639, in make_env
  File "<stdin>", line 340, in make
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

#### Additional Context
1. Ubuntu 22.04 on WSL
2. Python 3.12.2

**Comment by BennyDanielT** [comment]
I have followed instructions in [https://github.com/OpenDevin/OpenDevin/issues/785](https://github.com/OpenDevin/OpenDevin/issues/785) to install poetry as a workaround. 
Marking this is closed.
