### ISSUE TITLE
FileWriteAction.__init__() missing 1 required positional argument: 'content'

### ISSUE THREAD

**Issue by stratte89** [OpenDevin/OpenDevin#933]
I use Ubuntu, oobabooga webui, cognitivecomputations_dolphin-2.8-mistral-7b-v02, and the latest version (Revert the use of Router, good ole completion works.)

LLM_API_KEY="na"
LLM_BASE_URL="http://0.0.0.0:5000/v1"
LLM_MODEL="openai/Mistral"
LLM_EMBEDDING_MODEL="lokal"
WORKSPACE_DIR="./workspace"
MAX_ITERATIONS=20000

**Logs, error messages, and screenshots**:
STEP 5

PLAN:
tetris game in python pygame

ERROR:
FileWriteAction.__init__() missing 1 required positional argument: 'content'
Traceback (most recent call last):
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/action/__init__.py", line 40, in action_from_dict
    return action_class(**args)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: FileWriteAction.__init__() missing 1 required positional argument: 'content'
07:02:31 - opendevin:ERROR: agent_controller.py:113 - Error in loop
Traceback (most recent call last):
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 111, in start_loop
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/action/__init__.py", line 40, in action_from_dict
    return action_class(**args)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: FileWriteAction.__init__() missing 1 required positional argument: 'content'
![image](https://github.com/OpenDevin/OpenDevin/assets/101955267/cf054bdd-1e69-4fb8-99c5-fd4199d5e713)

**Comment by SmartManoj** [comment]
Please follow the issue template. 🙏

run `git log --format="%h | %cr" -n 1` or the below code and paste the clipboard content here.
```
import subprocess

def run(command):
    return subprocess.run(command, shell=True, capture_output=True).stdout.decode('utf-8')

try: 
    from pyperclip import copy
except ImportError:
    subprocess.run('pip install pyperclip --user', shell=True)
    from pyperclip import copy

commands = {
    'version' : 'git log --format="%h | %cr" -n 1'
}

for command in commands:
    commands[command] = run(commands[command])

output = ''
for command in commands:
    output += f'{command}: {commands[command]}\n'

output = output.strip()
copy(output)
```

**Comment by SmartManoj** [comment]
`print(args)` after line 39 in "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/action/init.py",

**Comment by stratte89** [comment]
> Add `print(action)` after line 39 in "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/action/init.py",.

STEP 0

PLAN:
tetris in python pygame

ERROR:
cannot access local variable 'args' where it is not associated with a value
Traceback (most recent call last):
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/action/__init__.py", line 39, in action_from_dict
    print(action, args)
                  ^^^^
UnboundLocalError: cannot access local variable 'args' where it is not associated with a value
07:46:14 - opendevin:ERROR: agent_controller.py:113 - Error in loop
Traceback (most recent call last):
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 111, in start_loop
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/action/__init__.py", line 39, in action_from_dict
    print(action, args)
                  ^^^^
UnboundLocalError: cannot access local variable 'args' where it is not associated with a value
![image](https://github.com/OpenDevin/OpenDevin/assets/101955267/e2621384-14e8-4280-9e3d-bf293261bca0)

**Comment by stratte89** [comment]
> Add `print(action)` after line 39 in "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/action/init.py",.

STEP 20

PLAN:
tetris in python pygame

{'action': 'think', 'args': {'thought': 'Next, I should work on writing a simple Tetris game in Python with Pygame to implement the logic of Tetris.'}, 'message': 'Next, I should work on writing a simple Tetris game in Python with Pygame to implement the logic of Tetris.'} {'thought': 'Next, I should work on writing a simple Tetris game in Python with Pygame to implement the logic of Tetris.'}

ACTION:
AgentThinkAction(thought='Next, I should work on writing a simple Tetris game in Python with Pygame to implement the logic of Tetris.', action=<ActionType.THINK: 'think'>)


==============
STEP 21

PLAN:
tetris in python pygame


ERROR:
Invalid response: no JSON found
Traceback (most recent call last):
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 154, in parse_action_response
    action_dict = json.loads(response)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/json.py", line 31, in loads
    raise ValueError("Invalid response: no JSON found")
ValueError: Invalid response: no JSON found
07:51:28 - opendevin:ERROR: agent_controller.py:113 - Error in loop
Traceback (most recent call last):
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 111, in start_loop
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 154, in parse_action_response
    action_dict = json.loads(response)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/json.py", line 31, in loads
    raise ValueError("Invalid response: no JSON found")
ValueError: Invalid response: no JSON found

**Comment by SmartManoj** [comment]
> after line 39

not before

**Comment by stratte89** [comment]
> > after line 39
> 
> not before; add at line 40

i did, i realised the mistake and the error above happended after i corrected it and wrote it in like 40

![image](https://github.com/OpenDevin/OpenDevin/assets/101955267/718fa387-0c5b-4af3-911c-fcb73c014ceb)

**Comment by SmartManoj** [comment]
> File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/json.py", line 31, in loads
> raise ValueError("Invalid response: no JSON found")
Change to `raise ValueError(f"Invalid response: no JSON found; Got {s}")`

These errors are due low quality of the LLM.

**Comment by stratte89** [comment]
> > File "/home/stratte/Schreibtisch/AI/OpenDevin/agenthub/monologue_agent/utils/json.py", line 31, in loads
> > raise ValueError("Invalid response: no JSON found")
> > Change to `raise ValueError(f"Invalid response: no JSON found; Got {s}")`
> 
> These errors are due to the low quality of the LLM.

ah ok, just weird that i haven't had that error with earlier versions and the same LLM
