### ISSUE TITLE
It keeps giving errors. 

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#949]
ERROR:
"'action['action']='find'' is not defined. Available actions: dict_keys([<ActionType.KILL: 'kill'>, <ActionType.RUN: 'run'>, <ActionType.BROWSE: 'browse'>, <ActionType.READ: 'read'>, <ActionType.WRITE: 'write'>, <ActionType.RECALL: 'recall'>, <ActionType.THINK: 'think'>, <ActionType.FINISH: 'finish'>, <ActionType.ADD_TASK: 'add_task'>, <ActionType.MODIFY_TASK: 'modify_task'>])"
Traceback (most recent call last):
  File "/home/timuc/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/action/__init__.py", line 36, in action_from_dict
    raise KeyError(
KeyError: "'action['action']='find'' is not defined. Available actions: dict_keys([<ActionType.KILL: 'kill'>, <ActionType.RUN: 'run'>, <ActionType.BROWSE: 'browse'>, <ActionType.READ: 'read'>, <ActionType.WRITE: 'write'>, <ActionType.RECALL: 'recall'>, <ActionType.THINK: 'think'>, <ActionType.FINISH: 'finish'>, <ActionType.ADD_TASK: 'add_task'>, <ActionType.MODIFY_TASK: 'modify_task'>])"
18:44:28 - opendevin:ERROR: agent_controller.py:113 - Error in loop
Traceback (most recent call last):
  File "/home/timuc/OpenDevin/opendevin/controller/agent_controller.py", line 111, in start_loop
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/action/__init__.py", line 36, in action_from_dict
    raise KeyError(
KeyError: "'action['action']='find'' is not defined. Available actions: dict_keys([<ActionType.KILL: 'kill'>, <ActionType.RUN: 'run'>, <ActionType.BROWSE: 'browse'>, <ActionType.READ: 'read'>, <ActionType.WRITE: 'write'>, <ActionType.RECALL: 'recall'>, <ActionType.THINK: 'think'>, <ActionType.FINISH: 'finish'>, <ActionType.ADD_TASK: 'add_task'>, <ActionType.MODIFY_TASK: 'modify_task'>])"

It keeps giving errors. One place is fixed, another part is broken, there is no planned update.

**Comment by timucindusunur** [comment]
I'm wondering, have you ever tried the code?

**Comment by enyst** [comment]
What LLM were you using?

**Comment by rbren** [comment]
@timucindusunur please open a new issue with the template filled out. We need to know which commit you're on, and which LLM/agent you're using.
