### ISSUE TITLE
Error creating controller. Please check Docker is running using `docker ps`.

### ISSUE THREAD

**Issue by vittoriopapa** [OpenDevin/OpenDevin#974]
#### Describe the bug
I run correctly Open Devin and I can see the frontend but I can't send massage to the bot because he sad "starting new task..." "No agent started. Please wait a second...". After the first message "Hi! I'm OpenDevin, an AI Software Engineer. What would you like to build with me today?" he replaced with "Error creating controller. Please check Docker is running using `docker ps`.". Docker is actually running so I can't understen the error. I tried to restart pc and re-install docker, I check the version and if is running with docker ps but it doesn't work enough. 

#### Setup and configuration
**Current version**: 0.1.0

**Commands I ran to install and run OpenDevin**:
make build
make setup-config
make run

<img width="960" alt="Screenshot 2024-04-10 123057" src="https://github.com/OpenDevin/OpenDevin/assets/166405458/e24c05c6-59bf-4891-8337-9eed35b20954">

**Comment by vittoriopapa** [comment]
> #### Describe the bug
> I run correctly Open Devin and I can see the frontend but I can't send massage to the bot because he sad "starting new task..." "No agent started. Please wait a second...". After the first message "Hi! I'm OpenDevin, an AI Software Engineer. What would you like to build with me today?" he replaced with "Error creating controller. Please check Docker is running using `docker ps`.". Docker is actually running so I can't understen the error. I tried to restart pc and re-install docker, I check the version and if is running with docker ps but it doesn't work enough.
> 
> #### Setup and configuration
> **Current version**: 0.1.0
> 
> **Commands I ran to install and run OpenDevin**: make build make setup-config make run
> 
> <img alt="Screenshot 2024-04-10 123057" width="960" src="https://private-user-images.githubusercontent.com/166405458/321199107-e24c05c6-59bf-4891-8337-9eed35b20954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDYzNTAsIm5iZiI6MTcxMjc0NjA1MCwicGF0aCI6Ii8xNjY0MDU0NTgvMzIxMTk5MTA3LWUyNGMwNWM2LTU5YmYtNDg5MS04MzM3LTllZWQzNWIyMDk1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxMDQ3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTFmOTZhOTIxY2YxZjUwNzNlYWFkMmQzOWU2ZWQ4Zjc2NDUzMWRlMDIzNDNmYjk2ZDA0MzAzODliYTQxMzllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZmV5MET3kjF1JthbyqmXa_KtgZquC8ZUYmLSKQBN4oQ">

The ERROR is:

opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/home/vittoriopapa/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/vittoriopapa/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/vittoriopapa/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/vittoriopapa/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/home/vittoriopapa/OpenDevin/opendevin/sandbox/sandbox.py", line 213, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/vittoriopapa/.cache/pypoetry/virtualenvs/opendevin-BgiRA1ye-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host

**Comment by eddienews-dev** [comment]
Thanks for raising. I'm getting a similar issue. I've tried to troubleshoot; here's what I could find:

Confirmed Docker and SSH: Like above, Docker is running (docker ps shows the sandbox), and a manual SSH attempt fails ("Connection refused").
Inside the Sandbox:
I accessed the sandbox with docker exec -it <container-id> /bin/bash.
systemctl is unavailable, suggesting systemd isn't used.
/etc/ssh/sshd_config appears standard.

Questions:

Service Management: How do I check SSH server status, start, stop, and restart it within the OpenDevin sandbox? (Haven't seen this addressed in the thread yet)
Logs: Where would I find logs related to the SSH server within the sandbox environment?

**Comment by sinpsarkar** [comment]
I have run into the exact same issue after a fresh pull and "make build". Please advise!

**Comment by anthonyyoussef01** [comment]
ran into the same error

**Comment by rbren** [comment]
Hey all--we just merged a possible fix. Try adding `SANDBOX_TYPE=exec` to your config.toml

**Comment by enyst** [comment]
All: please update ```git pull```, a solution for these issues has just been merged.
Set SANDBOX_TYPE to 'exec', in the config.toml file, if you need the older version of container which worked for your installation.

**Comment by CypherpunkSamurai** [comment]
thanks. I was just looking for a fix and found out this was updated 1 hour ago lol 👍🏼

**Comment by anthonyyoussef01** [comment]
I am still having the same error:
```
Traceback (most recent call last):
  File "/mnt/c/Users/antho/PycharmProjects/OpenDevin/opendevin/server/agent/manager.py", line 124, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/antho/PycharmProjects/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/mnt/c/Users/antho/PycharmProjects/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/antho/PycharmProjects/OpenDevin/opendevin/sandbox/sandbox.py", line 135, in __init__
    self.restart_docker_container()
  File "/mnt/c/Users/antho/PycharmProjects/OpenDevin/opendevin/sandbox/sandbox.py", line 393, in restart_docker_container
    raise Exception('Failed to start container')
Exception: Failed to start container
```

**Comment by enyst** [comment]
@anthonyyoussef01 add to your config.toml file:
```SANDBOX_TYPE=exec```

**Comment by vittoriopapa** [comment]
File "/home/vittoriopapa/.cache/pypoetry/virtualenvs/opendevin-BgiRA1ye-py3.11/lib/python3.11/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid date or number (line 4 column 1 char 126)

If I start "make run" I have this error

**Comment by buqiuwenda** [comment]
File "/Users/huangzhongxi/Library/Caches/pypoetry/virtualenvs/opendevin-6T71_ruG-py3.12/lib/python3.12/site-packages/docker/api/client.py", line 220, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by vittoriopapa** [comment]
Ok now work. I uninstall Docker on my pc and I re-install on WSL.

**Comment by zhoumzh** [comment]
SANDBOX_TYPE="exec" like this? or SANDBOX_TYPE=exec?  in config.toml

**Comment by enyst** [comment]
> SANDBOX_TYPE="exec" like this? or SANDBOX_TYPE=exec? in config.toml

SANDBOX_TYPE="exec"

Sorry for the confusion!

**Comment by enyst** [comment]
> File "/Users/huangzhongxi/Library/Caches/pypoetry/virtualenvs/opendevin-6T71_ruG-py3.12/lib/python3.12/site-packages/docker/api/client.py", line 220, in _retrieve_server_version raise DockerException( docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

You're on a Mac? You can install Docker Desktop and simply start it, then opendevin can do its thing. If you have more trouble, please open a new issue with the details of your setup.

**Comment by anthonyyoussef01** [comment]
This worked, thank you!

> @anthonyyoussef01 Check out #911 for other solution. Key to get it to work for me was uninstalling Docker and reinstalling via WSL.

This worked Thank you!

**Comment by LeonidUIN** [comment]
Здравствуйте. Запускаю Docker и открываю OpenDevin по адресу "http://localhost:3000/index.html". Сам интерфейс OpenDevin отображается нормально, но при этом пишет  "Error creating controller. Please check Docker is running using `docker ps`.", "No agent started. Please wait a second..." и "I didn't recognize this action:terminal". Увидел, что люди в комментариях пишут, что можно вписать строку "SANDBOX_TYPE=exec" в файл "config.toml" и якобы это должно исправить проблему, но я не могу у себя найти файл "config.toml" (функция поиска не помогает), чтобы это сделать. Помогите пожалуйста. Подскажите где находится данный файл. Если что у меня Мак.

**Comment by LeonidUIN** [comment]
Hello. I launch Docker and open OpenDevin at “http://localhost:3000/index.html”. The OpenDevin interface itself displays normally, but it says "Error creating controller. Check if Docker is running using docker ps.", "Agent is not running. Wait a second..." and "I did not recognize this action: terminal." I saw that people in the comments write that you can write the symbol "SANDBOX_TYPE=exec" in the file "config.toml" and expect that this should fix the problem, but I cannot find the file "config.toml" (the search function does not helps) to do this. Help me please. Tell me where this file is located. If anything, I have a Mac.
