### ISSUE TITLE
openai.APIConnectionError: Connection error.

### ISSUE THREAD

**Issue by pandaupc** [OpenDevin/OpenDevin#987]
#### Setup and configuration
**Current version**:

```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1.
2.
3.

**Logs, error messages, and screenshots**:

#### Additional Context

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_base_client.py", line 931, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/litellm/llms/openai.py", line 373, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_base_client.py", line 1213, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_base_client.py", line 902, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_base_client.py", line 955, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_base_client.py", line 1026, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_base_client.py", line 955, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_base_client.py", line 1026, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/shouwangzhe/anaconda3/envs/opendevin/lib/python3.11/site-packages/openai/_base_client.py", line 965, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

**Comment by enyst** [comment]
Please do ```git log -n 1``` and paste the result here. Best if you update anyway, too

**Comment by pandaupc** [comment]
(opendevin) shouwangzhe@shouwangzhe:~/code/OpenDevin$ git log -n 1
commit 78858c18b5c42ab8f2a424457a5d1c02acc2b0c2 (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Tue Apr 9 15:37:33 2024 -0500

    Update README.md (#956)

**Comment by DXLgpt** [comment]
We have the same issue #1008

**Comment by DXLgpt** [comment]
Is it working?
