### ISSUE TITLE
Unable to use a Local LLM using OpenDevin, Value changes to Null

### ISSUE THREAD

**Issue by vader113** [OpenDevin/OpenDevin#988]
#### Describe the bug

Unable to use the Local LLM. I have provided the exact values from the LiteLLM Documentation but everytime the model name value  changes to Null and I am unable to use or request with OpenDevin

#### Setup and configuration
**Current version**:

```bash
Author: AbhisekOmkar <67184718+AbhisekOmkar@users.noreply.github.com>
Date:   Sun Apr 7 00:00:58 2024 +0530
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="stable-code-instruct-3b-Q4_K_S"
LLM_API_KEY="anything"
API_BASE="http://localhost:5001/v1/"
LLM_EMBEDDING_MODEL="openai"
WORKSPACE_DIR="./workspace"

```

**My model and agent** (you can see these settings in the UI):
* Model: stable-code-instruct-3b-Q4_K_S
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

**Steps to Reproduce**:
1.  Setup the Frontend and BAckend and launch it.

**Logs, error messages, and screenshots**:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/home/kingslayer/Downloads/OpenDevin/opendevin/server/listen.py", line 42, in websocket_endpoint
    await session_manager.loop_recv(sid, agent_manager.dispatch)
  File "/home/kingslayer/Downloads/OpenDevin/opendevin/server/session/manager.py", line 37, in loop_recv
    await self._sessions[sid].loop_recv(dispatch)
  File "/home/kingslayer/Downloads/OpenDevin/opendevin/server/session/session.py", line 33, in loop_recv
    await dispatch(action, data)
  File "/home/kingslayer/Downloads/OpenDevin/opendevin/server/agent/manager.py", line 74, in dispatch
    await self.create_controller(data)
  File "/home/kingslayer/Downloads/OpenDevin/opendevin/server/agent/manager.py", line 127, in create_controller
    llm = LLM(model=model, api_key=api_key, base_url=api_base)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kingslayer/Downloads/OpenDevin/opendevin/llm/llm.py", line 36, in __init__
    self._router = Router(
                   ^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/litellm/router.py", line 309, in __init__
    self.set_model_list(model_list)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/litellm/router.py", line 2176, in set_model_list
    deployment = self._add_deployment(deployment=deployment)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/litellm/router.py", line 2212, in _add_deployment
    ) = litellm.get_llm_provider(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 5774, in get_llm_provider
    raise e
  File "/root/.cache/pypoetry/virtualenvs/opendevin-R00s8Ula-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 5761, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=null
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
INFO:     connection closed
INFO:     ('127.0.0.1', 47600) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIxYmIyZWJjOS03MTRhLTQ1YzItYTk2Ny0yYWQwYzA1ZjQxOGEifQ.IynrxEC9l9RaEfqwCEXVe9gys84Ec_c6H7gtCY69U-k" [accepted]
Starting loop_recv for sid: 1bb2ebc9-714a-45c2-a967-2ad0c05f418a, False
INFO:     connection open

Provider List: https://docs.litellm.ai/docs/providers

**Comment by enyst** [comment]
Please update with ```git pull``` to get the latest version. It matters, three days ago or so we changed precisely some of the things in your error trace and no longer use the Router class there. I'll close this topic because you won't see the same, but if you still have errors feel free to open another.
